### ISSUE TITLE
ES6 Module support

### ISSUE THREAD

**Issue by prettydiff** [prettydiff/prettydiff#101]
https://github.com/Glavin001/atom-beautify/issues/362

Syntax is as follows:

    import {
        //block
    } from 'path';

Like many blocks in JavaScript the curly braces are optional here. As part of this feature curly braces must be inserted. The insertion is either explict (as in `{ }` with the `correct` option) or implicit (as in pseudo characters `x{ x}` for internal analysis).  Curly brace insertion will be extended so that:

* If the keyword `import` is not followed by a curly brace one will be inserted
* If the `from` keyword is not preceded by a closing curly brace one will be inserted
* Although module code does not likely seem to accept nested module code there is no indicate that its block could not contain other blocks (each with their own optional curly braces). This must be accounted for.
* Logic must be added to ensure inserted braces for `import` do not interfere with inserted braces for containing blocks (regression bug).

**Comment by CumpsD** [comment]
The curly braces are not optional if I understand correctly from the spec.

eg:
```
import { Store } from 'marty';
import Store from 'marty';
```
These 2 are not the same. The first imports the `Store` class from marty, while the other imports all of marty.

http://www.2ality.com/2014/09/es6-modules-final.html check number 5 for some examples

**Comment by CumpsD** [comment]
It would be nice to simply have an option to ignore import statements, if that exists? (I am an atom-beautify user who wishes to not constantly have to reformat my imports on every beautify)

**Comment by prettydiff** [comment]
@CumpsD Thanks for that. Fixed as v1.12.0
