### ISSUE TITLE
LESS/Sass beautification has intermittently different output

### ISSUE THREAD

**Issue by Glavin001** [prettydiff/prettydiff#106]
So this is a weird one, and I need your help @prettydiff.

- I have Travis CI and AppVeyor for CI testing.
- Both builds are failing right now:
  - Travis CI (Mac): https://travis-ci.org/Glavin001/atom-beautify/builds/66280307
  - AppVeyor (Windows): https://ci.appveyor.com/project/Glavin001/atom-beautify/build/64

Let's take a closer look at the first test: 
- Travis CI: https://travis-ci.org/Glavin001/atom-beautify/builds/66280307#L2190
- AppVeyor: https://ci.appveyor.com/project/Glavin001/atom-beautify/build/64#L426

It is this test: https://github.com/Glavin001/atom-beautify/blob/master/examples/nested-jsbeautifyrc/less/expected/test3.less

**Input:** https://github.com/Glavin001/atom-beautify/blob/master/examples/nested-jsbeautifyrc/less/original/test3.less

```less
// Breaks (fixed now)
.mixin(@variable, @anotherVariable) {
}
// Works
.mixin(@variable; @anotherVariable) {
}
// Ok
.mixin(@variable) {
}
```

**Expected Output:** https://github.com/Glavin001/atom-beautify/blob/master/examples/nested-jsbeautifyrc/less/expected/test3.less

```less
// Breaks (fixed now)
.mixin(@variable, @anotherVariable) {
  
}
// Works
.mixin(@variable; @anotherVariable) {
  
}
// Ok
.mixin(@variable) {
  
}
```

The Travis CI (Mac) diff is as follows:

```
--- /Users/travis/build/Glavin001/atom-beautify/examples/nested-jsbeautifyrc/less/expected/test3.less	beautified
+++ /Users/travis/build/Glavin001/atom-beautify/examples/nested-jsbeautifyrc/less/expected/test3.less	expected
@@ -1,14 +1,12 @@
 //␣Breaks␣(fixed␣now)⏎
 .mixin(@variable,␣@anotherVariable)␣{⏎
 ␣␣⏎
 }⏎
-⏎
 //␣Works⏎
 .mixin(@variable;␣@anotherVariable)␣{⏎
 ␣␣⏎
 }⏎
-⏎
 //␣Ok⏎
 .mixin(@variable)␣{⏎
 ␣␣⏎
 }
\ No newline at end of file
With options:
{
    "indent_size": 2,
    "indent_char": " ",
    "selector_separator_newline": false,
    "newline_between_rules": false,
    "preserve_newlines": true,
    "wrap_line_length": 0,
    "indent_comments": true,
    "force_indentation": false,
    "convert_quotes": "none",
    "align_assignments": false
}
```

AppVeyor (Windows) diff:

```
--- C:\projects\atom-beautify\examples\nested-jsbeautifyrc\less\expected\test3.less	beautified
+++ C:\projects\atom-beautify\examples\nested-jsbeautifyrc\less\expected\test3.less	expected
@@ -1,14 +1,12 @@
 //␣Breaks␣(fixed␣now)⏎
 .mixin(@variable,␣@anotherVariable)␣{⏎
 ␣␣⏎
 }⏎
-⏎
 //␣Works⏎
 .mixin(@variable;␣@anotherVariable)␣{⏎
 ␣␣⏎
 }⏎
-⏎
 //␣Ok⏎
 .mixin(@variable)␣{⏎
 ␣␣⏎
 }
\ No newline at end of file
 
 
With options:
{
    "indent_size": 2,
    "indent_char": " ",
    "selector_separator_newline": false,
    "newline_between_rules": false,
    "preserve_newlines": true,
    "wrap_line_length": 0,
    "indent_comments": true,
    "force_indentation": false,
    "convert_quotes": "none",
    "align_assignments": false
}
```

On my computer (Mac) the tests pass (generate expected output) with the same options:

```
With options:
{
"indent_size": 2,
"indent_char": " ",
"selector_separator_newline": false,
"newline_between_rules": false,
"preserve_newlines": true,
"wrap_line_length": 0,
"indent_comments": true,
"force_indentation": false,
"convert_quotes": "none",
"align_assignments": false
}
```

It looks like what is wrong with Travis CI and AppVeyor's beautified outputs are that they have an extra newline character (indicated by `⏎`), where my local builds do not. It seems like `newline_between_rules` is somehow being enabled. Pretty Diff is updated to `^0.11.21` so it should not be a version issue.

Is there any chance that Pretty Diff's beautification could be using something other than the options passed into `prettydiff.api(options)`, such as some external config file in a nearby directory (`.editorconfig`, etc).

Any help would be greatly appreciated. Thanks!

**Comment by Glavin001** [comment]
What is also strange is that most of the other tests still pass. See any test without `_` prefix: https://github.com/Glavin001/atom-beautify/tree/master/examples/nested-jsbeautifyrc/less/original

**Comment by prettydiff** [comment]
I think this one is a bug on my end. The final empty line is only preserved if it is actually two empty lines. This is a bug that I need to fix, because it produces recursive problems.  If it takes two empty lines to preserve one empty line at the end of the file then what happens when the same code is beautified a second time... no final empty line is preserved.
