### ISSUE TITLE
Option to treat self-closing tags as equal to empty tags

### ISSUE THREAD

**Issue by murrayju** [prettydiff/prettydiff#114]
According to the [xml spec](http://www.w3.org/TR/REC-xml/#dt-eetag), `<tag></tag>` should be considered equal to `<tag/>`. It would be useful for the diff tool to consider these to be equal (could be an option, but seems like a reasonable default).

**Comment by prettydiff** [comment]
I could do this. I would exclude tags named `div` and `span` in order to safely support older versions of IE though.

**Comment by murrayju** [comment]
It would be nice to distinguish an html mode from an xml mode. I'm doing strict xml comparisons, and don't care about html quirks like that.

**Comment by prettydiff** [comment]
I just moved this under an option named tagmerge - http://prettydiff.com/documentation.xhtml#tagmerge

I was getting some complaints from people who use strange template schemes.
