### ISSUE TITLE
Test automation

### ISSUE THREAD

**Issue by prettydiff** [prettydiff/prettydiff#115]
1. Create a test runner specifically for the prettydiff node support.
2. Create unit tests specifically for command line execution.
    1. test all input/output schemes
    2. test all supported "modes"
    3. test each supported option is passed from input to prettydiff.js library
3. Report pass/fail and a description of the test unit to command line
4. Create a git hook to run this test. Test failure halts a push to the repo
5. Provide test groups for each of prettydiff's major libraries each with unit tests

**Comment by prettydiff** [comment]
It is underway at https://github.com/prettydiff/cliTester

**Comment by prettydiff** [comment]
cliTester application is now in a reliable, structured, extensible, and semi-recursive state.  I am ready to start populating unit tests.

**Comment by Glavin001** [comment]
I recommend using the public/open-source version of https://travis-ci.org/ for free testing.

**Comment by prettydiff** [comment]
This issue is the biggest priority and the focus is shifted away from the API files and to the application files.  Here will be the process:

1. NPM Scripts - The test runner will be a file at http://prettydiff.com/test/lint.js that will run with `test` and `prepublish` NPM events.
2. Linting - Find all JS files in the project automatically, pass them through Pretty Diff beautification, and pass the result through the latest version of JSLint with white-space checking on.  I have a mechanism in place to check for the latest edition of JSLint no more than once each day the test is run.
3. Unit testing - I will have a directory for raw test samples that get passed through Pretty Diff beautification and compared to a known good state of same file name in a clean directory.

The testing approach mentioned in the first, second, and third comments is for testing interaction, options, and dependability of the node-local.js API file.  This sort of unit testing remains important, but it is less imperative.  I will circle back on automating API interaction once I have this complete.

**Comment by prettydiff** [comment]
Interactive tests to stress test the various API files will remain absent for the time being.  Application test automation is complete as described above and will launch tonight.

**Comment by prettydiff** [comment]
Done.  I failed to add this to the documentation, so I will do that in the next update.  Pretty Diff can be independently stress tested in this manner:

    npm install jslint
    npm test

I am including the tests in the NPM package.  This makes the tests portable and reproducible by everybody without a build process.  Unfortunately, it also increases the size of the NPM package by 8.9mb.

**Comment by Glavin001** [comment]
Great to hear there are tests!

@prettydiff do you have tests running with [Travis CI](https://travis-ci.org/)? Also add the Travis CI badge to prettydiff README.

> I am including the tests in the NPM package. This makes the tests portable and reproducible by everybody without a build process. Unfortunately, it also increases the size of the NPM package by 8.9mb.

I think the disadvantage of having a much larger package to install from npm outweighs the benefit of having the tests included and removing the build process. If someone wants to run the tests for Pretty Diff they should clone the prettydiff repo and follow the instructions. Just my thoughts :smile:.

**Comment by prettydiff** [comment]
@Glavin001 you are probably right.  I should probably remove the test cases from NPM and instead pull them down at execution time, if they are not present locally.  This would increase the execution time of the tests by waiting this download, but would eliminate the down from installing/updating the package.

The primary benefit of using NPM to run the tests is the `prepublish` state, which will halt publication if there are defects.

I don't have any tests on Travis yet.  I don't have any build processes for this application, so I haven't figured out to make Travis work with test samples directly.  I probably just need to spend more time looking at Travis and wrap my head around their process.  It is likely something simple and I just haven't put in the minimal effort yet.
