### ISSUE TITLE
Tag released versions for Bower's sake

### ISSUE THREAD

**Issue by murrayju** [prettydiff/prettydiff#116]
I'm currently using [Bower](http://bower.io) to pull down prettydiff as a dependency, but without some of the convenience that comes with versioned releases.

All this would require is to tag your commits with the version number.

**Comment by prettydiff** [comment]
I will change my commit process to the following

    git commit -m "stuff"
    git tag -am "V1.12.8"
    git push origin

**Comment by murrayju** [comment]
Agreed. Doesn't have to be for every commit, just the ones that you consider a new (production ready) release (maybe you don't make that distinction).

You could also tag the current version as a starting point (you can do this directly in GitHub on the releases page).

Thanks!
