### ISSUE TITLE
Empty li mess up indentation

### ISSUE THREAD

**Issue by filipesilva** [prettydiff/prettydiff#118]
Empty `li` are replaced with their self closing tags, but mess up indentation.

Input
```
<ul>
    <li>something</li>  
    <li></li>
    <li>something</li>
    <li></li>
    <li>something</li>
</ul>
```

Output
```
<ul>
    <li>something</li>
    <li/>
<li>
    something</li><li/>
<li>something
</li>
</ul>
```

**Comment by prettydiff** [comment]
Line of 8832 of [prettydiff.js](http://prettydiff.com/prettydiff.js) needs to go from

    } else if (types[types.length - 2] === "start" && tname !== "/span" && tname !== "/div" && tname !== "/script" && tname === "/" + tagName(token[token.length - 1])) {

to

    } else if (types[types.length - 2] === "start" && tname !== "/span" && tname !== "/div" && tname !== "/script" && tname !== "/li" && tname === "/" + tagName(token[token.length - 1])) {

I will publish the change in about 6 hours.

**Comment by filipesilva** [comment]
Cheers!
