### ISSUE TITLE
document-element should not be altered due to markup beautification

### ISSUE THREAD

**Issue by kaizer200** [prettydiff/prettydiff#119]
By beautification (due to line wrapping & indentation), 
the following:
```<xml>this is the document element</xml>```
result into the following:
`<xml>this is the`
`       document`
`    element</xml>`
looks good, but this is false behavior – since it changed the document-element content.
Beautification should not apply to document-element.

**Comment by prettydiff** [comment]
Isn't the text node that is being wrapped a child of the document element? I am thinking the document element would just be `<xml>`.

**Comment by kaizer200** [comment]
if the document element would just be `<xml>` then it won't  be a valid xml. Any xml element (also the document) must have a start and end tags (or no end-tag if its an empty element). 
`<xml>text</xml>` is valid.

But in any case,
for the sake of this bug, also the following example manifest the problem:
`<!--this is comment-->`
`<book>`
`<name>  here comes   </name></book>`
Beautify it, and you'll see for the following false behaviors for the text-node: trimming of spaces from the beginning, indenting the node, adding new lines, trimming spaces from the end.

My PR #120 takes care of this

**Comment by prettydiff** [comment]
I have something at http://prettydiff.com/ignore/testlocation/prettydiff.com.xhtml

I put this feature behind an option `textpreserve`.  By putting this enhancement behind an option I was able to get this in very little change to the parser and without impacting other users.

**Comment by kaizer200** [comment]
Missing documentation for the `textpreserve` option.
Functionality works ok

**Comment by prettydiff** [comment]
yeah, I still have to do that.  If it works as intended I will write up the documentation.  I am still waiting on feedback from https://github.com/prettydiff/prettydiff/issues/108 before I release.

**Comment by kaizer200** [comment]
OK, it works as intendent
