### ISSUE TITLE
Problem with <p> tag in ERB 

### ISSUE THREAD

**Issue by iashanmugavel** [prettydiff/prettydiff#122]
if ``<p>`` has an `id` and `class` then the `class` value is misplaced after the beautification 

For example:

before:
```html
<p id="notice" class ="success">
```
after: 
```html
<p ="success" class id="notice">
```

I have moved  this issue from https://github.com/Glavin001/atom-beautify/issues/445

**Comment by prettydiff** [comment]
Fixed on my local.  Waiting on https://github.com/jshint/jshint/issues/2528 for https://github.com/prettydiff/prettydiff/issues/121
