### ISSUE TITLE
paragraphs truncated all over the website and the Git repo's XHTML files

### ISSUE THREAD

**Issue by guillaume-d** [prettydiff/prettydiff#124]
For example http://prettydiff.com/documentation.xhtml#beau_markup resp. https://github.com/prettydiff/prettydiff/blob/f0c944098f167e47581378d53cdf8114867516eb/documentation.xhtml#L1618 (master's newest version as of now).

Maybe this was caused by beautification bug #113?
This makes reading the documentation a very frustating! Just hoping not much text was lost on the last faulty checkins.

**Comment by prettydiff** [comment]
Yeah, that is completely broken.  I am looking into this.

**Comment by prettydiff** [comment]
I updated the documentation so that it is more legible.  If you notice any problems or find that it is not helpful just let me know and I will get it updated.

**Comment by guillaume-d** [comment]
It looks OK so far (I could read a few paragraphs here and there that I previously could not). If I see some other problems I will let you know.

Thanks for fixing it and for the new 1.12.15 release! :+1:
