### ISSUE TITLE
Seemingly Broken Prettydiff HTML Output

### ISSUE THREAD

**Issue by Markavian** [prettydiff/prettydiff#125]
https://gist.github.com/Markavian/59703b63b2b70904335e

![image](https://cloud.githubusercontent.com/assets/1431385/8709958/206b9732-2b3e-11e5-9988-a9ea6aa0c554.png)

**Comment by prettydiff** [comment]
Would you mind telling the steps you went through to produce that corrupted output.  I have heard of this problem a few times in the past so it is likely a very common issue.  Once I can reproduce the problem I will I work on an enhancement to make saving down report output easier.

To save diff reports in the mean time try one of these two approaches:

* If using the web tool look at the red `S` icon in the top right corner of the report window.  If you click this button in Firefox the file will be generated for you and prompt for a save location on your local file system, but you will need to change the file extension from `.part` to `.xhtml`.  If you are using any other browser clicking the `S` will produce a textarea containing all the text already put together for an independent file.  You will just need to open a new file copy/paste the text in and save as a .xhtml file.
* From the command line use the `api/node-local.js` file with something like `node api/node-local.js source:"my source file path" diff:"my diff file path" output:"path to write the report" readmethod: "file"`

**Comment by Markavian** [comment]
Well, aside from the code used to harness prettydiff in the original Gist, here's a snapshot of the `build` and `canned` directories I was diffing together: https://github.com/connected-web/web-component-js/tree/9d2fd828f23f6fe65ae751e01836231ccdb97ba9/tests/compiler

I've switched to using `dirdiff` for the moment to highlight immediate differences between the canned and compiled directories. I don't know if that helps or not.

**Comment by p3l** [comment]
It happens if you try to do it inside an html document like this:
```html
<html>
  <head>
    <title>ar.conf diff</title>
    <link rel="stylesheet" type="text/css" href="prettydiff-master/diffview.css" media="all"/>
    <script type="text/javascript" src='prettydiff-master/prettydiff.js'></script>
  </head>
  <body>
    <div id="diffoutput">
    </div>
    <script type="text/javascript">
      var args = {
                   source: "f1",
                   diff  : "f2",
                   lang  : "text"
                 }
      var output = prettydiff(args);
      document.getElementById("diffoutput").innerHTML = output[0];
    </script>
  </body>
</html>
```
Since the output variable contains javascript (actually it is an xhtml document) it is not evaluated.
I noted from the example code that this was not likely to work, but I tried it (restrictions for my usecase).

**Comment by prettydiff** [comment]
That makes sense. I would have to create an option to support this.  The option would likely be something like:

    htmlInjectionPoint: "diffoutput"

The option would take a string as its value where that string represents an id value in the page and then insert the diff output into that element with innerHTML.  The consequence is that if such an id value is not present the innerHTML property would throw an error.  For default operation I would just give this option an empty string value.

I will think on this.  I may not get to this quickly as I am currently in an isolated military training environment have only my cell hotspot for connectivity.

**Comment by prettydiff** [comment]
Try this out and let me know if this is closer to what you are looking for:  http://prettydiff.com/ignore/testlocation/prettydiff.com.xhtml

If you scroll down the page one of the first options is *Save Preference*.  Click the radio button under that for *Diff Report Only*.  Then perform your code comparison.  In the report window that comes up click the red "S" icon.

If this is closer to what you are looking for then I will refine this process and add the steps to the documentation.
