### ISSUE TITLE
xml beautification doesn't take place if apostrophe or quote sign inside a comment

### ISSUE THREAD

**Issue by kaizer200** [prettydiff/prettydiff#126]
Hi,
**(I will solve this problem and issue pull request)**

if a comment at xml file, contain odd number of either the apostrophe sign ( ' ) or quote sign ( " ),
no beautification of the xml is done
if the number of  the apostrophe sign ( ' ), or quote sign ( " ) is even - the beautification is taking place.
placing such chars inside an xml comment doesn't bare any syntactic meaning according to xml spec-thus, the bug.

example un-beautified xml:
`<!--this is" comment-->`
`<xml>    <nodeB el="33"> abc t</nodeB>`
`    </xml>`

**Comment by prettydiff** [comment]
Yeah..... to provide you some hints I am using a variable named `quote` in the `tag` function to trap quotes.  I should not be applying this logic (any other advanced parsing logic) if `types[types.length - 1] === "comment"`

**Comment by kaizer200** [comment]
thanks man :+1:

**Comment by kaizer200** [comment]
have you solved it?

**Comment by kaizer200** [comment]
but I wrote I will do a pull request...
???

**Comment by prettydiff** [comment]
I am sorry.  I noticed a bunch of other problems with support for Dust.js template language and bug 127 so I threw this fix in.  All I did was create a boolean variable named `comment` that is assigned true every time a comment tag is encountered and then I bypass some additional logic by setting

    if (quote === "" || comment === true)

I was going to look at additional stuff today in case my fix missed anything.  Please feel free to continue working a pull request as I could always merge in the code over my fix.

**Comment by kaizer200** [comment]
Hi,
thanks for your attentiveness :-) 
please close the issue

It took me some time to re-visit the issue and see your latest comment, as I was highly occupied at other suff.

Thanks
