### ISSUE TITLE
Is it possible to have the output actually format the HTML?

### ISSUE THREAD

**Issue by karabijavad** [prettydiff/prettydiff#13]
I would like to compare 2 HTML documents,
but in the output diff, I would like the HTML to be rendered. Is this an option that is available?

**Comment by Todd1561** [comment]
I'm also looking for this capability, where the output is marked up with something like <del> and <ins> tags that can be styled with CSS, as in the screen shot above.  I'm not seeing how "inline mode" can produce that.  Everything seems to produce a comprehensive report with changes in a table.  I don't need that, I just want the HTML so I can use it in a CMS.

**Comment by prettydiff** [comment]
I am starting work on this right now and hope to have it available before Monday.  It will be available on github for people to test, but I cannot promise when Pretty Diff 3 will be production ready.  I have been working on version 3 since the beginning of January.

**Comment by prettydiff** [comment]
First draft just pushed to the 3.0.0 branch.  The responsible code is largely: https://github.com/prettydiff/prettydiff/blob/3.0.0/prettydiff.ts#L379-L510

Known issues:

* the build is breaking.  this seems unrelated, but I have to look into it
* exposes a defect in the diff algorithm that improperly highlights in the index prior to an insert or after a deletion as a replacement.

**Comment by prettydiff** [comment]
This feature should now be ready for evaluation in the 3.0.0 branch.  You can either clone that branch down to test it locally in your browser or on the command line.  You can also test it online at https://prettydiff.com/3/

This feature is hidden behind an option `diff_rendered_html`.  Please let me know if this isn't helpful and how it can be improved.  If you notice any errors please open a new issue.

**Comment by rreynier** [comment]
I will try and take a look at it later today or tomorrow, thanks!
