### ISSUE TITLE
JSX: sometimes it uses two spaces

### ISSUE THREAD

**Issue by luisrudge** [prettydiff/prettydiff#133]
I created the issue in the wrong place: https://github.com/Glavin001/atom-beautify/issues/496

![jsx](https://cloud.githubusercontent.com/assets/941075/9100126/7523e214-3bad-11e5-9299-cc316e7148e9.gif)

**Comment by Glavin001** [comment]
I believe 0.12.8 was working as expected and now 0.12.17 is not (doing this).
See https://github.com/Glavin001/atom-beautify/commit/eea0fb63ae1e09ba7269a1a3cddc52eb8247283e for when I updated Atom Beautify to this latest version of Pretty Diff, which is broken.

**Comment by prettydiff** [comment]
@luisrudge would you mind providing a code sample for me to reproduce the problem?

**Comment by Glavin001** [comment]
@prettydiff I changed the Atom Beautify example code to account for this defect. The commit is https://github.com/Glavin001/atom-beautify/commit/eea0fb63ae1e09ba7269a1a3cddc52eb8247283e
You can see the change to each of those lines is an extra space. You can click `View` on any of those changed files in that commit and use those as example code. Hope that helps! Thank you!

**Comment by luisrudge** [comment]
this is an example:
```javascript
class App extends React.Component {
  render() {
    return (
      <div className="div1">
        <div  className="div2"/>
      </div>
    );
  }
}
```

**Comment by luisrudge** [comment]
if you close the second div, it works as expected.

```javascript
class App extends React.Component {
  render() {
    return (
      <div className="div1">
        <div className="div2"></div>
      </div>
    );
  }
}
```

**Comment by Glavin001** [comment]
Oh interesting! It only occurs on elements that are self-closing! Looking at files changed in https://github.com/Glavin001/atom-beautify/commit/eea0fb63ae1e09ba7269a1a3cddc52eb8247283e it appears to be consistent!

So the test case is specifically:

```html
<div  className="div2"/>
```

**Comment by Glavin001** [comment]
You are incredible, @prettydiff. Thank you!

**Comment by luisrudge** [comment]
Thanks!
