### ISSUE TITLE
Destructuring formatting

### ISSUE THREAD

**Issue by luisrudge** [prettydiff/prettydiff#134]
Hey, is there a way to have Destructuring formatting being in one line?

Currently, it's being formatted to this:
```javascript
import {
  Foo,
  Bar
}
from 'FooBar';
```

I want this:

```javascript
import { Foo, Bar } from 'FooBar';
```

**Comment by prettydiff** [comment]
Would this be something that only occurs after the `import` keyword?

**Comment by luisrudge** [comment]
no. It happens in every destructuring

```javascript
const {
  DefaultRoute,
  Route,
  Redirect
} = Router;
```

**Comment by prettydiff** [comment]
Looking at the following example it seems the block representing a destructured object may be a comma separated list or an object literal: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment#Nested_object_and_array_destructuring

This said destructuring may resemble the following three examples:

    var [one, two, three] = number;
    var {one, two, three} = number;
    var {one: "one", two: "two", three: "three"} = number;

Notice that the third one is actually an object literal with assigned properties.  I am not going to flatten that third example whether or not it is a destructured object.

**Comment by luisrudge** [comment]
can you put that into one line like the examples you gave?

```javascript
var [one, two, three] = number;
var {one, two, three} = number;
```

**Comment by luisrudge** [comment]
What's the expected result here?
I'm still seeing this:

```javascript
import {
  BladeContainer, LoadingBlade, Blade
} from 'Components/Shared/Blade';
```

**Comment by prettydiff** [comment]
I am thinking there are 4 kinds of lists:

* arrays
* destructured object
* object literal
* method arguments

In all but the last one I want to spell out that a list is present by providing indentation.  For instance consider the following:

    import {Router, Route, Redirect} from 'react-router';

This example is pretty easy to read on a single line, but what if there were 50 items in the list instead of 3?  Then it would be more challenging to read.  The most important parts of that line of code are the items outside of the list.

**Comment by luisrudge** [comment]
I agree with you. 50 items would be terrible. Maybe have a config to say how many items you want per line? The common use case is to use just a few items, but 50 could happen every once in a while. What do you think?

**Comment by prettydiff** [comment]
It looks like I may be introducing a new option to flatten lists like this: https://github.com/Glavin001/atom-beautify/issues/495

**Comment by luisrudge** [comment]
Awesome. That would be great!

**Comment by iksose** [comment]
Destructuring is currently the biggest feature I'm waiting for from beautifiers.


In re: the 50 item import, after about four items you'd be best just doing ```import * from x```

**Comment by luisrudge** [comment]
@iksose Agree. The common case will always be just a few items, but it's nice to have an option for the edge cases
