### ISSUE TITLE
Flatten lists if arguments of methods or destructuring

### ISSUE THREAD

**Issue by prettydiff** [prettydiff/prettydiff#140]
Create option to flatten lists if arguments of methods or if expressed as destructuring.

    foo({a:"a", b:"b", c:"c"});
    import (a, b, c) from "wherever";

**Comment by prettydiff** [comment]
I am including this change directly opposed to hiding it behind some option. Please test this out in the following beta location and let me know if you find any code examples that fail to perform as desired.

http://prettydiff.com/ignore/testlocation/prettydiff.com.xhtml

I used this code to develop against:

    var a = 1;
    foo({a:"a", b:"b", c:"c"});
    foo(t,["a", "b", "c"]);
    import ("a", "b", "c") from "wherever";
    import ({a:"a", b:"b", c:"c"}) from "wherever";
    import (["a", "b", "c"]) from "wherever";

**Comment by luisrudge** [comment]
what I have to do with this xhtml?

**Comment by luisrudge** [comment]
is this the expected behavior? 
![image](https://cloud.githubusercontent.com/assets/941075/9265165/bc7fec26-4205-11e5-9ad2-4158bc17a4bf.png)

**Comment by prettydiff** [comment]
There is not enough code there for it to auto-detect JavaScript as the language.  The blue text in the top of the screen shot indicates the tool thinks of this as CSS.  Put `var a=1;` on the first line and you be just fine.

**Comment by luisrudge** [comment]
oh, ok. thanks! here's the result:

![image](https://cloud.githubusercontent.com/assets/941075/9267304/ff4a4232-4222-11e5-90b9-6091cbd1a702.png)

**Comment by prettydiff** [comment]
Thanks for catching that.  I updated the code for the `import` keyword immediately followed by a `{`.

**Comment by prettydiff** [comment]
I have also chosen to scale back this flattening logic in the case of method arguments containing multiple items.  For example this first sample will be flattened because it contains only 1 argument:

    foo({a:"a", b:"b", c:"c"});

This one will not be flattened:

    foo(t, {
        a:"a",
        b:"b",
        c:"c"
    });

My goal is to make code easier to read.  If there is more than a single dimension of depth then this should be immediately clear with indentation, but otherwise I agree that the code is easier to read with objects on a single line.

**Comment by luisrudge** [comment]
Awesome!!!!!!!!! I like this way! Just tested again and it put everything in one line. Thanks!

**Comment by luisrudge** [comment]
@prettydiff any ETA on the new release? THanks!

**Comment by prettydiff** [comment]
I am waiting on feedback for issue #125.  I will launch the next release Monday evening at the latest.

**Comment by luisrudge** [comment]
Ok! Thank you veeeeeery much! :)

**Comment by luisrudge** [comment]
Thanks!

**Comment by luisrudge** [comment]
@prettydiff awesome work. I just tested and it's working great. There's one missing case though:

```
import React,
{
  PropTypes
} from 'react';
```

**Comment by prettydiff** [comment]
This should be resolved now.  http://prettydiff.com/ignore/testlocation/prettydiff.com.xhtml  I will launch this with the next update.

**Comment by luisrudge** [comment]
awesome! let me know when you publish a new version! Thanks!

**Comment by pkerschbaum** [comment]
I think this functionality is broken: the object literal gets never flattened even if it is the only argument passed to a method.
Am I doing something wrong?
<img width="945" alt="2015-10-31 19_29_11" src="https://cloud.githubusercontent.com/assets/13141109/10865242/bb1d0240-8005-11e5-8f5d-4397c6fecc62.png">

**Comment by prettydiff** [comment]
@pkerschbaum Thanks for pointing out that regression bug.  It is fixed now in v1.15.4.
