### ISSUE TITLE
Rule declaration should be prefixed with new line after SCSS import

### ISSUE THREAD

**Issue by ArekSredzki** [prettydiff/prettydiff#143]
This applies to the new line between rules setting.

Original:
'''scss
@import 'angular';
body {}
'''

Expected:
'''scss
@import 'angular';

body {}
'''

Actual:
'''scss
@import 'angular';
body {}
'''

**Comment by prettydiff** [comment]
I will include this as a mandatory feature under the cssinsertlines option.
