### ISSUE TITLE
Add CSS option to remove leading 0 before a decimal

### ISSUE THREAD

**Issue by prettydiff** [prettydiff/prettydiff#146]
Create a new CSS only option to remove leading 0s before CSS beautification.

    width: 0.5em;

Would become

    width: .5em;

**Comment by ArekSredzki** [comment]
:+1:

**Comment by prettydiff** [comment]
You can try this out at http://prettydiff.com/ignore/testlocation/prettydiff.com.xhtml?m=beautify  Scroll down the page to the CSS options and play around with it.

**Comment by ArekSredzki** [comment]
Perfect!
