### ISSUE TITLE
Make the command-line tool more intuitive

### ISSUE THREAD

**Issue by joeytwiddle** [prettydiff/prettydiff#150]
I think I shared this before, but I can't find it now.

I had difficulty working out how to use the `prettydiff` tool from the shell after installing it via npm.

In the end I wrote [a user-friendly wrapper](https://github.com/joeytwiddle/jsh/blob/master/code/shellscript/node/nodepretty.sh) for it, which I have recently updated.

Now it works really nicely!  In Vim I can easily reformat a Javascript or HTML file by doing `:%!nodepretty`

**Comment by prettydiff** [comment]
Yeah, I need to update the documentation to better explain the features and capabilities of running prettydiff CLI.

This is awesome.  I want to do more with this so that configurations and options can be written against a global shell command.

**Comment by prettydiff** [comment]
What if I created support for a `.prettydiffrc` file to store option configurations by mode or language support?  Would that simply the command-line use?  If the configurations are stored somewhere you would only need to specify a few arguments each time.

**Comment by joeytwiddle** [comment]
That sounds like it might be useful to devs who want to configure certain things like spaces-per-indent or indent-with-tabs or curly-brackets-on-same-line or space-after-function-name.

However, that's not a big concern for me, and not what I was hoping to address in this issue.

What I actually meant when I wrote "more intuitive" is for the cmdline tool to adhere to some standard interface, either Unix-like ~~or DOS-like~~.  I would like to use this tool like I use all the other tools on my system, but I find the current cmdline arguments quite alien!

For example, taking inspiration from `man grep`:

    prettydiff [OPTIONS] [INFILE [OUTFILE]]

        If OUTFILE is not provided, output is sent to standard out.
        If INFILE is not provided, input is taken from standard in.

    OPTIONS

        -m MODE, --mode MODE
                ..........................

        -i COUNT, --spaces-per-indent COUNT
                Set the number of spaces prettydiff uses when indenting.  Default 4 for JS, 2 for HTML.

That would be Unix-like. It would allow me to do things like:

    curl "${url}" | prettydiff > "result-${n}.html"

But that's just my suggestion, and for now I am very happy using my wrapper script `nodepretty` to achieve that.

I don't know if there is any convention for the cmdline arguments of Node apps.  But I suppose `npm --help` could be inspiration.

So you may want some feedback from other users before deciding whether to change the cmdline argument structure or offer a configuration file in future.

If you do create a config file (which might deserve a new issue), things to consider are:

- It should be possible to override options from the cmdline. The easy way to implement that is

        -o OPTION=VALUE
                Override the configured option.  (See CONFIGURATION FILE below.)

- Users should be able to point to a different config file for different projects.

- Perhaps the local config file could be applied *after* (not instead of) the system and user config files.

Oooh, I have *just* seen the help on `prettydiff` (I was initially looking for it on `prettydiff --help`).  Even the help is pretty!  :smile: 

If there are a lot of users out there using your existing cmdline arguments in scripts, then maybe it's better not to change the structure. That functionality could still be provided by a wrapper script, for those who need it.

**Comment by prettydiff** [comment]
I think the safest thing at this time would be to focus on a wrapper script like you have provided and extend it to support the tools complete functionality.  Are shell scripts somewhat universal?  It seems bash is a more common terminal interface, but do bash scripts translate to shell scripts other than bash?

I will also be testing native shell script support in Windows 10 today.

**Comment by joeytwiddle** [comment]
Although `bash` is the most widely available shell on Unix systems, unfortunately it is not installed by default on Windows, which instead has its own `cmd.exe` and PowerShell.

Therefore for a portable wrapper script, I think it would be best written in Javascript.

The old DOS programs used to accept `/option` and `/?` rather than the Unix `--option` and `--help`, but I think in the Node world, the `-` leader is more conventional (albeit not universally).

**Comment by prettydiff** [comment]
Here is what I have come up with:

* http://prettydiff.com/ignore/testlocation/api/node-local.js
* http://prettydiff.com/ignore/testlocation/.prettydiffrc

The way it works is that first the application looks for a `.prettydiffrc` file in the current directory (from the console).  If not present it will such a file from application root `../.prettydiffrc`.  It does not look for this file until after the application has evaluated the command line arguments.

The `.prettydiffrc` file is a little JS function that outputs new options.  By default it is blank thereby making no changes to the options.  In this file you can assign new values to options directly or conditionally so as to allow a variety of possible configurations for a variety of scenarios as determined by the options this little file receives.

Play around with it and let me know what you think.  I have tested this approach against the local and global install on my windows system.

**Comment by prettydiff** [comment]
I also allow JSON format for the .prettydiffrc file as well.

**Comment by joeytwiddle** [comment]
Just for reference: http://programmers.stackexchange.com/questions/307467/what-are-good-habits-for-designing-command-line-arguments

**Comment by prettydiff** [comment]
Thank you Joey.  I will consider a better alternate presentation for writing arguments.
