### ISSUE TITLE
wrong jsx formatting

### ISSUE THREAD

**Issue by luisrudge** [prettydiff/prettydiff#153]
```js
export default class MyComponent extends React.Component {
  render() {
    const options = {a:1};
    return (
      <div>
        <div {...options} />
      </div>
    );
  }
}
```

is being beautified to this:

```js
export default class MyComponent extends React.Component {
  render() {
    const options = {
      a: 1
    };
    return (
      <div>
        <div </div {...options}/> >
    );
  }
}

```

**Comment by prettydiff** [comment]
Fixed. http://prettydiff.com/ignore/testlocation/prettydiff.com.xhtml

**Comment by luisrudge** [comment]
Awesome! Thanks very much!

**Comment by luisrudge** [comment]
hey @prettydiff. Any ETA on the new version? Thanks!

**Comment by prettydiff** [comment]
Yesterday I found a massive regression bug from this that I have closed on my local.  I want to have it up tonight.  In addition I am also fixing a serious Node.js bug and closing out an algorithmic bug on my auto-correction feature. I am estimating a release in about 4-8 hours.

**Comment by luisrudge** [comment]
ok. THaaaanks! :)

**Comment by luisrudge** [comment]
You're a machine! Thanks!
