### ISSUE TITLE
A new readmethod for passing text

### ISSUE THREAD

**Issue by setzer17** [prettydiff/prettydiff#154]
Hello,
I would like to use Pretty Diff command line version, and directly pass code to it as text without the need for a file. This can be useful when there is a script that needs to call prettydiff without writing any files to the disk first.

Example in PHP:
```php
<?php
$src =
"<html>
<b>not standard</b>
</html>";
$src = escapeshellarg($src);

$diff =
"<html>
<b>not standard</b>
</html>";
$diff = escapeshellarg($diff);

exec("prettydiff readmethod:'text' source:$src diff:$diff"); // output: *No differences*
?>
```

Another suggestion is to simply return the count of differences without outputting anything. This can also be useful if used with scripting languages.
Example:
```php
<?php
$src =
"<html>
<b>not standard</b>
</html>";
$src = escapeshellarg($src);

$diff =
"<html>
<b>not standard</b>
</html>";
$diff = escapeshellarg($diff);

$diff_count = 0;
$output = []; // this is here just because it's required by exec()... it should be empty

exec("prettydiff readmethod:'text' source:$src diff:$diff", $output, $diff_count);

echo "There are {$diff_count} differences.";
?>
```

**Comment by setzer17** [comment]
Well, after some research, I found out that there will be problems with doing this :p

**Comment by prettydiff** [comment]
The node module does have a readmethod value of `screen` where code input can be passed in directly on the command line without need for a file.  I am not sure if this is helpful to your problem though.

I am still focused on delivering a solution for your issue #151.

> Well, after some research, I found out that there will be problems with doing this :p

If you no longer wish to pursue this matter would you mind closing the issue?  I am not sure how to move this forward.
