### ISSUE TITLE
Unable to implement PrettyDiff locally in a <div> element

### ISSUE THREAD

**Issue by bpromasmb** [prettydiff/prettydiff#156]
I want to render a view in my Rails app that loads up two json strings from my database and then diffs them with PrettyDiff. This sounds like a very simple task but I'm having a lot of trouble doing it so. My view (html) looks like this:

    <div id="div1"><%= @project1.jstring %></div>
    <br/>
    <div id="div2"><%= @project2.jstring %></div>
    <br/>
    <div id="diff"/>

Quite simple. Then my javascript looks like this:

    var div1 = document.getElementById('div1').innerHTML;
    var div2 = document.getElementById('div2').innerHTML;
    
    var args   = {
            source: div1,
            diff  : div2,
            mode : "diff",
            lang  : "json"
        };
    output = prettydiff(args);

    document.getElementById("diff").innerHTML = output[0];

I am importing the `prettydiff.js` and `api/dom.js` assets to my web app. With that, PrettyDiff is capable of processing the strings correctly, but the output looks strange and not as functional:

![sem titulo](https://cloud.githubusercontent.com/assets/12829571/9588435/bc8c13b4-4ffe-11e5-9ce3-7f66fa264114.jpg)

There is no visual element (such as colorization) to the generated div, I cannot click to collapse/expand lines, and there is a whole bunch of undesirable text rendered above the diff. (Also - not pictured - it messes with my header navbar, making it a lot taller. But I think this will go away if the implementation is done correctly.)

I don't know what I am missing in my implementation and I don't know what else to try, so I am coming here for help.

**Comment by prettydiff** [comment]
Check this issue out: https://github.com/prettydiff/prettydiff/issues/125#issuecomment-131292786

Let me know if that works.

I suspect you are generating a diff want to directly implant it into a section of a different existing HTML document.  The diff report generated by Pretty Diff is formatted and interactive HTML, which means CSS and JavaScript code are required in addition to the raw HTML table.  Right now I am providing a means to generate these as separate code assets so that you can simply take what you need for your larger HTML document.

The current solution is not immediately clear or efficient.  I am more than open to additional creative direction to better address this problem.

**Comment by bpromasmb** [comment]
> If you scroll down the page one of the first options is Save Preference. Click the radio button under that for Diff Report Only. Then perform your code comparison. In the report window that comes up click the red "S" icon.

That looks like what I want. Is this implemented as a functionality of PrettyDiff?

It's still messing up my header navbar for some reason, I'll look into what causes this and maybe fix it on my end

![messed](https://cloud.githubusercontent.com/assets/12829571/9589298/c84d014a-5003-11e5-95ba-ad062001c098.jpg)
(The messed up navbar, in case you know what it could be. I suspect conflicting .css)

**Comment by prettydiff** [comment]
I agree with your assessment.  I will let you know once I have new and more specific CSS.

**Comment by bpromasmb** [comment]
The css conflict that breaks my header in this case is happening on <li> elements.

**Comment by prettydiff** [comment]
Thanks for looking to that.  Aside from the current CSS conflicts is this approach working for your needs?

**Comment by bpromasmb** [comment]
Yes, very much so. Thanks for the support.

**Comment by prettydiff** [comment]
Test it out at http://prettydiff.com/ignore/testlocation/prettydiff.com.xhtml

In my tests I have fixed all CSS and JavaScript problems with the saved code.  It should be far more durable now.  Please try it out and let me know if you are continuing to experience problems.
