### ISSUE TITLE
cssinsertlines option value false ignored

### ISSUE THREAD

**Issue by prettydiff** [prettydiff/prettydiff#157]
https://github.com/Glavin001/atom-beautify/issues/531

cssinsertlines option is operating with a value of `true` even when set to false.

          p {
            color: red;
            strong {
              font-weight: bold;
            }
          }
          .foo {
            position: absolute;
          }

Becomes:

          p {
            color: red;

            strong {
              font-weight: bold;
            }
          }

          .foo {
            position: absolute;
          }

**Comment by janwerkhoven** [comment]
:+1:

**Comment by prettydiff** [comment]
Please review at http://prettydiff.com/ignore/testlocation/prettydiff.com.xhtml?m=beautify

**Comment by janwerkhoven** [comment]
Seems to work for me, I copied my entire SCSS file into your tool and all white lines were correctly removed.
