### ISSUE TITLE
css !important on repeated property

### ISSUE THREAD

**Issue by prettydiff** [prettydiff/prettydiff#159]
.example {
        margin: 0 0 1em 0 !important;
        margin: 0 0 1em 0 !important;
        padding: 0 0 1em 0 !important;
    }

Becomes

    .example {
        margin : 0 0 1em 0 !important;
        margin : 0;
    }

**Comment by prettydiff** [comment]
Please review at http://prettydiff.com/ignore/testlocation/prettydiff.com.xhtml?m=beautify

**Comment by davidscotson** [comment]
Looks fixed to me, fast work!
