### ISSUE TITLE
New JS option to inject trialing commas in object literals

### ISSUE THREAD

**Issue by prettydiff** [prettydiff/prettydiff#160]
var a = {
        cat: "meow",
        dog: "ruff"
    };

Should become

    var a = {
        cat: "meow",
        dog: "ruff",
    };

This option **will only be applied to object literals** and not any other kinds of lists, such as: arrays, function arguments, or expression lists.

**Comment by Bodhiz** [comment]
Hi @prettydiff,

Why could you not apply the option to array as well ? 

Thanks.

**Comment by prettydiff** [comment]
Try it out http://prettydiff.com/ignore/testlocation/prettydiff.com.xhtml?m=beautify

I have it working for both arrays, object literals, and destructured objects.  Just scroll all the way down and look for a new option "endcomma" and set the value "Add trailing commas".

Here is a code sample that I was experimenting with

    var a = {
        cat: "meow",
        dog:"ruff",
    }, b = [cat, dong];
    
    import {
      Foo,
      Bar
    }
    from 'FooBar';
    
    const {
      DefaultRoute,
      Route,
      Redirect
    } = Router;
    
    var [
        one, two, three
    ] = number;
    var {
        one, two, three
    } = number;
    var {
        one: "one",
        two: "two",
        three: "three"
    } = number;

Just play around with it and let me know what you think.  If there are missing features or defects then let me know what you find and I will work out a solution.

**Comment by Bodhiz** [comment]
Hi,

Thank you for your quick fix. 

I tried out the option with the following code : 

```javascript
class DtNoticesList extends Polymer.Class({
  is: 'dt-notices-list',
  properties: {
    url: {
      type: String,
      notify: true,
    },
  },
}) {
  attached() {
    console.log(this.url);
  }
}

document.registerElement(DtNoticesList.prototype.is, DtNoticesList);

```

but it removes commas after the notify property and the two closing curly brackets after.
Here is the output I get : 

```javascript
class DtNoticesList extends Polymer.Class({
  is: 'dt-notices-list',
  properties: {
    url: {
      type: String,
      notify: true
    }
  }
}) {
  attached() {
    console.log(this.url);
  }
}

document.registerElement(DtNoticesList.prototype.is, DtNoticesList);
```

**Comment by prettydiff** [comment]
I was not able to reproduce the error, but I did make an update to ensure I am catching objects with only 1 property.

**Comment by prettydiff** [comment]
https://github.com/Glavin001/atom-beautify/issues/534

**Comment by prettydiff** [comment]
I failed to mention this, but the tool has a styleguide feature to set a collection of options in alignment with a particular styleguide.  I have added this option to the `airbnb` value of the `styleguide` option.  Read about it at http://prettydiff.com/guide/styleguide.xhtml

**Comment by Bodhiz** [comment]
Hi @prettydiff,

Is the trailing comma addition supported in JSX files ?
