### ISSUE TITLE
break chain method

### ISSUE THREAD

**Issue by bigyuki** [prettydiff/prettydiff#161]
before:

    gulp.task('webpack', ['clean'], function () {
        return gulp.src(paths.scripts)
            .pipe(webpack(webpackConfig))
            .pipe(uglify())
            .pipe(gulp.dest(paths.scriptsDest));
    });

after:

    gulp.task('webpack', ['clean'], function () {
        return gulp.src(paths.scripts).pipe(webpack(webpackConfig)).pipe(uglify()).pipe(gulp.dest(paths.scriptsDest));
    });

this is not i want.

**Comment by prettydiff** [comment]
You can test it out now. http://prettydiff.com/ignore/testlocation/prettydiff.com.xhtml

Just let me know if the code looks better or weird things happen to your code.  I made this the default and provided an option `methodchain` for users who want to force chains of methods onto a single line.

Some fair warning in that the code is looking for a `.` (period) following a `)` (closing paren) instead of looking to verify if its actual chains of methods.

**Comment by prettydiff** [comment]
Hold on and don't test yet.  I am getting some serious regression from this.

**Comment by prettydiff** [comment]
Patterns I am thinking about:

    var a = location.href.toLowerCase().split("/")[3].toUpperCase().split("%20");
    var a = location
        .href //split on properties as well
        .toLowerCase() //ensure comments in the middle don't break things
        .split("/")[3]
        .toUpperCase()
        .split("%20");
    
    var b = func(myMethod().property.otherMethod() > 5);
    var b = func(myMethod()
        .property
        .otherMethod() > 5); //splitting methods inside a higher method looks odd

**Comment by prettydiff** [comment]
Now you should be able to test away: You can test it out now. http://prettydiff.com/ignore/testlocation/prettydiff.com.xhtml

**Comment by prettydiff** [comment]
Testing against JSLint.  Must look more at lists

    function q() {
        "use strict";
        var all = 0,
            value = 0,
            auto = 0,
            pd = 0,
            dateList = 0,
            componentArea = 0,
            lang = 0,
            table = 0,
            token = 0,
            a = 0;
        if (all === true && lang === "") {
            value = auto(pd.ace.beauIn.getValue());
            pd.o.langvalue = value;
        }
        all
            .ace
            .beauIn
            .getSession()
            .setMode("ace/mode/" + value[0]);
        dateList = dateList
            .sort(function dom__load_sort_forward(componentArea, row) {
                return componentArea[1] === row[1];
            })
            .reverse()
            .sort(function dom__load_sort_reverse(componentArea, row) {
                return componentArea[0] - row[0];
            });
        table.push(token[a]
            .replace(/&/g, "&amp;")
            .replace(/</g, "&lt;")
            .replace(/>/g, "&gt;"));
        return [
            all
                .join("")
                .replace(all, "<pd>")
                .replace(all, "</pd>"),
            all
                .join("")
                .replace(all, "<pd>")
                .replace(all, "</pd>")
        ];
    }

**Comment by bigyuki** [comment]
@prettydiff Hi, I test my code, is ok, thank you.

**Comment by prettydiff** [comment]
I am looking at what to do with the following code.

    var c,
        k = function q(u
                .big()
                .method,
            j
                .small()
                .ethod()) {
            a
                .big()
                .method;
            b
                .small()
                .ethod;
        };

I am probably going to scale this feature back so that it is never applied inside `(` and `)` type containers.

**Comment by prettydiff** [comment]
var a,
        result = (function jspretty__resultScope() {
            for () {}
            build = [
                    "</em> unnecessary instances of the keyword <strong>new</strong> counted.</p>", data, last
                ];
            }()).replace(/(\s+)$/, "")
            .replace(/\u009f/g, "");
        };

Found a problem with functions

**Comment by prettydiff** [comment]
I have this all squared away now and I plan to launch tonight.  This enhancement will come with these limitations:

* Method chains originating from a `}` will not be broken.  This just looks weird to read.
* Method chains whose immediate container is parenthesis will not be broken.  Breaking here makes the code very confusing to figure out.
* Indentation inside functions, such as functions wrapped in parenthesis, will not be altered so long as the method chain originates from something directly wrapping the function.
* The first property/method in the method chain will not be broken.  This visually indicates that a property is directly riding on something and that following (line broken) properties are associated (and indented), as in a chain.
