### ISSUE TITLE
Es6 class beautify problem

### ISSUE THREAD

**Issue by bigyuki** [prettydiff/prettydiff#164]
Before:

    class App extends Component {

        render() {
            return (
                <div>Hello World</div>
            );
        }
    }

After:

    class App extends Component {render() {
            return (
                <div>Hello World</div>
            );
        }
    }

I think the method should not like that.

**Comment by prettydiff** [comment]
Looks like a destructuring regression.

**Comment by prettydiff** [comment]
This problem should be resolved at http://prettydiff.com/ignore/testlocation/prettydiff.com.xhtml
