### ISSUE TITLE
Start in beautify mode

### ISSUE THREAD

**Issue by m1ga** [prettydiff/prettydiff#167]
Is it possible to have a link that will start on the beautify section on the webpage? Would save one radio-button click if you just want to quickly beautify some code

**Comment by prettydiff** [comment]
Try using the `m` parameter, for instance:  http://prettydiff.com/?m=beautify

http://prettydiff.com/documentation.xhtml#parameters

If I have failed to answer the question please reopen the issue.

**Comment by m1ga** [comment]
thanks! haven't looked into the doc, my bad :blush:
