### ISSUE TITLE
expose the xml parser as a standalone utility

### ISSUE THREAD

**Issue by kaizer200** [prettydiff/prettydiff#168]
Hello,
exploring through the prettyDiff code, I saw that it has its own xml parser.
I haven't found maintained, JS open-source xml parsers **which also validate**, out there.

please expose the xml-parser as a standalone (API etc.), consumable via requireJS.
...consider if you want to publish it as a new open-source...

**Comment by kaizer200** [comment]
Adding requirment- consumable also from nodeJS

**Comment by prettydiff** [comment]
Here is the plan:

* Each library will contain the boilerplate required for Node and require.js
* There will still be no build process.
* The HTML tool will require each library using a script tag
* The node file will request each library through the standard `require` convention

**Comment by prettydiff** [comment]
This is launched and the XML parser/beautifier /lib/markuppretty.js is now independent of the prettydiff.js application file.  It is a true module now, but I am not going to be supplying custom HTML for the libraries, because I don't want to maintain that.
