### ISSUE TITLE
Minify and chain-js-code

### ISSUE THREAD

**Issue by faiwer** [prettydiff/prettydiff#169]
simple example:
```js
if(1)
	f(1)
	.f(5)
```
=>
```js
if(1)f(1);.f(5);
```
need without ";"
```js
if(1)f(1).f(5);
```

**Comment by prettydiff** [comment]
ASI defect.

**Comment by prettydiff** [comment]
To what is happening to cause the defect set the `correct` option to `true` and you get this output:

    if (1) {
        f(1);
    }.f(5);

The inserted characters need to account for operators and separators as the next non-white space characters.

**Comment by prettydiff** [comment]
Semicolons will not be inserted if the following character is any of: `=<>+*?|^:&%~,.()]`

**Comment by faiwer** [comment]
```js
if (1)
	a = fn1(2)
	// 3
	.fn2(3)
```
=>
```js
if(1)a=fn1(2);.fn2(3);
```
With ";:" again. Without "// 3" working normally. Original code https://gist.github.com/faiwer/b9c92b52ab9de6a45f1d

**Comment by faiwer** [comment]
similar code https://gist.github.com/faiwer/2f26a309c63fc06597a4
but with `else` and `/**/` comment

**Comment by prettydiff** [comment]
I think I have everything fixed, but in case I have continued to miss anything I have put the solution online for you to try.  Please try it out at http://prettydiff.com/ignore/testlocation/prettydiff.com.xhtml

**Comment by prettydiff** [comment]
All items should be resolved now. http://prettydiff.com/ignore/testlocation/prettydiff.com.xhtml

**Comment by faiwer** [comment]
Now all right. Thank you!
