### ISSUE TITLE
Minify and ternarius-js-code

### ISSUE THREAD

**Issue by faiwer** [prettydiff/prettydiff#170]
simple example:
```js
if(1)
    var a = 1
		? 2
		: 3;
```
=>
```js
if(1)var a=1;?2:3;
```
need without ";"
```js
if(1)var a=1?2:3;
```

**Comment by prettydiff** [comment]
Ternary ASI defect.

**Comment by prettydiff** [comment]
Semicolons will not be inserted if the following character is any of: `=<>+*?|^:&%~,.()]`

**Comment by faiwer** [comment]
```js
if (2) a = 1 ? 2 // 3
: 3;
```
=>
```js
if(2)a=1?2;:3;
```
With ";:" :( Without "// 3" working normally.

Original code https://gist.github.com/faiwer/a3402478114fac44608c

**Comment by prettydiff** [comment]
I think I have everything fixed, but in case I have continued to miss anything I have put the solution online for you to try.  Please try it out at http://prettydiff.com/ignore/testlocation/prettydiff.com.xhtml

**Comment by faiwer** [comment]
I'm testing my finally code by your test-link. And get new bug (was not see that on previous version). Prettydiff output code:
```js
b-1in a
```
Firefox throw of it syntax error: `SyntaxError: identifier starts immediately after numeric literal`. Browser wanna `b-1 in a`.

This code from minified jquery. Originally `b-1 in a`. After prettydiff `b-1in a`. I thnik better using spaces always.
firefox error: http://ftp.faiwer.ru/img_22_09_19:13:10_d3e7e86ce41.png
chromium: http://ftp.faiwer.ru/img_22_09_19:14:30_08c02173581.png

**Comment by faiwer** [comment]
Also (from already minified jquery):
```js
function e(a){return y.DocumentFragment?a instanceof
DocumentFragment:a&&11===a.nodeType}
```
=>
```js
function e(a){return y.DocumentFragment?a instanceof;DocumentFragment:a&&11===a.nodeType}
```
after `instanceof` symbol `;`.

**Comment by prettydiff** [comment]
All items should be resolved now. http://prettydiff.com/ignore/testlocation/prettydiff.com.xhtml

**Comment by faiwer** [comment]
Now all right. Thank you!
