### ISSUE TITLE
Less no indenting properly

### ISSUE THREAD

**Issue by prettydiff** [prettydiff/prettydiff#171]
https://github.com/Glavin001/atom-beautify/issues/557

    header {
      .inner {
        h1 {
          float: left;
          margin: 15px 0 15px -3px;
          img {
            @include transition(all 500ms ease);
            @media (max-width: 400px) {
              width: auto;
              height: 33px;
            }
            nav {
              float: right;
              margin: 10px -10px 0 0;
              @include transition(all 500ms ease);
            }
          }
        }
      }
    }

Becomes

    header {.inner {h1 {
                float : left;
                margin: 15px 0 15px -3px;
                img {
                    @include transition(all 500ms ease);
                    @media (max-width: 400px) {
                        width : auto;
                        height: 33px;
                    }
                    nav {
                        float : right;
                        margin: 10px -10px 0 0;
                        @include transition(all 500ms ease);
                    }
                }
            }
        }
    }

**Comment by prettydiff** [comment]
This defect appears to evident when setting option `cssinsertlines` to `false`

**Comment by janwerkhoven** [comment]
All works!

I have reinstalled `atom-beatify` to pull in the latest `Pretty Diff`, beautified all my SCSS files and seems to work as intended. Job well done. Thanks for the quick respons both @Glavin001 and @prettydiff . I don't mind bugs at all when knowing you guys tackle them quickly, happy user :)

**Comment by prettydiff** [comment]
Thanks @janwerkhoven
