### ISSUE TITLE
Prettydiff fails under Node 4.1.0

### ISSUE THREAD

**Issue by MikeThomas64** [prettydiff/prettydiff#172]
I recently upgraded to Node v4.1.0 and prettydiff (from the command line) fails with "ReferenceError: options is not defined" within .prettydiffrc.

The problem is that line 15 is using "options" rather than "option" as the variable name. 

For some reason, this doesn't fail under Node 4.0.0.

**Comment by prettydiff** [comment]
I will have this resolved when I publish a patch tonight.
