### ISSUE TITLE
Feature request - max line length of minified code

### ISSUE THREAD

**Issue by faiwer** [prettydiff/prettydiff#173]
Currently prettydiff make 1 string with js-code. It's hardly testing (all text-editors freezing), bad for debugging. Will be better if prettydiff will have this nice option :)

P.S. sorry for my bad english

**Comment by prettydiff** [comment]
I will create a new option so that the `wrap` value is applied to strings when minifying code.

http://prettydiff.com/documentation.xhtml#wrap

I want to publish the fix to the bugs you provided, so I plan to have this published this evening.

**Comment by prettydiff** [comment]
Please try it out at http://prettydiff.com/ignore/testlocation/prettydiff.com.xhtml?m=minify

Just scroll all the way down to set the option for "Wrap code to value specified with option wrap" and put any integer into the following text field.

**Comment by faiwer** [comment]
Try it https://gist.githubusercontent.com/faiwer/cbcf4197bc6970d0a31b/raw/9ac71c30d04f7ced60e26d0aec8649286f64b132/gistfile1.txt 
It's jquery minified. Output code hasn't syntax error, but incorrect. Browser throw `Uncaught TypeError: Cannot use 'in' operator to search for 'length' in blur focus focusin focusout load resize scroll unload click dblclick mousedown mouseup mousemove mouseover mouseout mouseenter mouseleave change select submit keydown,keypress,keyup,error,contextmenu(…)`. Withour wrapping code working normally

**Comment by prettydiff** [comment]
Bah, found the problem.  A long string gets split into string concatenation:

    var a = "a really long string";

Would get split into (if provided a width of 10):

    var a = "a really l" +
            "ong string";

This is fine unless the string has a method attached, because then the method only operates on the last string segment, which is causing the JQuery error.  If a string has a method I need to wrap it in parens before splitting it.

    var a = ("a really l" +
            "ong string").someMethod();

**Comment by prettydiff** [comment]
I think I got it nailed this time: Please try it out at http://prettydiff.com/ignore/testlocation/prettydiff.com.xhtml?m=minify

**Comment by faiwer** [comment]
Working good. Thank you!
