### ISSUE TITLE
Sample page has really huge icon

### ISSUE THREAD

**Issue by filipesilva** [prettydiff/prettydiff#182]
This is all I see when opening it up on a browser:

![image](https://cloud.githubusercontent.com/assets/4172079/10487438/dcdf3970-728b-11e5-98ee-7e0ef2d75a88.png)

I checked and it's just some missing css, so I'll do a PR for it. You might have more missing css than that though.

**Comment by prettydiff** [comment]
I will be accepting your pull request just after I push my next commit.

**Comment by filipesilva** [comment]
Happy to be able to help, man.
