### ISSUE TITLE
Create new option, CSS selector list on one line

### ISSUE THREAD

**Issue by prettydiff** [prettydiff/prettydiff#189]
https://github.com/Glavin001/atom-beautify/issues/599

    a,
    input,
    button {
        color: red;
    }

Should become:

    a, input, button {
        color: red;
    }

**Comment by prettydiff** [comment]
Ready for review at http://prettydiff.com/ignore/testlocation

**Comment by prettydiff** [comment]
New option is named `selectorlist`

**Comment by paperrobots** [comment]
I'm trying to setup a .prettydiffrc file along side Atom Beautify so I can take advantage of this new selectorlist option. Kind of confused as to what to do though. I setup my .prettydiffrc file, I put it in the atom-beautify package folder. Is that correct? Where should I be placing the file? I'm on a mac if that helps. 

And as far as the contents of the file is this all I need? 

    {
      "selectorlist" : true
    }


Sorry for the stupid questions, first time setting something like this up. Really love it so far though!

**Comment by prettydiff** [comment]
I don't think Atom Beautify uses the .prettydiffrc file.  You are going to have to use the settings GUI provided by Atom Beautify.  You might be able to put this into the .jsbeautifyrc file, which I am pretty sure Atom Beautify does use.
