### ISSUE TITLE
Pretty Diff - simplify option sharing between libraries

### ISSUE THREAD

**Issue by prettydiff** [prettydiff/prettydiff#191]
Options are not being shared between Pretty Diff libraries:

    var New = React.createClass({
        render() {
            return (
                <InputText valid={validate} value={this.state} onChange={this.handleSalaryChange} label='test' onValidationError='test2' placeholder='test3' ref='test4'/>
            );
        }
    });

This sample code illustrates that JSX code is not wrapping in Pretty Diff because an option is not being passed from jspretty library to markuppretty library.

https://github.com/Glavin001/atom-beautify/issues/613
https://github.com/Glavin001/atom-beautify/issues/591

**Comment by prettydiff** [comment]
jspretty.js is corrected for this issue in an experimental file at http://prettydiff.com/ignore/testlocation/lib/jspretty.js

**Comment by prettydiff** [comment]
csspretty.js is corrected for this issue at http://prettydiff.com/ignore/testlocation/lib/csspretty.js

**Comment by prettydiff** [comment]
csvpretty.js is corrected for this issue at http://prettydiff.com/ignore/testlocation/lib/csvpretty.js

**Comment by prettydiff** [comment]
markuppretty is corrected for this issue at http://prettydiff.com/ignore/testlocation/lib/markuppretty.js

**Comment by prettydiff** [comment]
diffview.js is corrected for this issue at http://prettydiff.com/ignore/testlocation/lib/diffview.js

**Comment by prettydiff** [comment]
This effort is done and ready for testing at http://prettydiff.com/ignore/testlocation

**Comment by jmlv** [comment]
Very well
