### ISSUE TITLE
command line doesn't like certain files that work with the web app

### ISSUE THREAD

**Issue by davidscotson** [prettydiff/prettydiff#194]
Some files seem to make the command line version go crazy, but work when I paste them into the web app.

Running version 1.14.8, on, for example, the file `variables.less` from Bootstrap 3 (https://github.com/twbs/bootstrap/blob/master/less/variables.less) , I get an output full of things like:

```
//** Global textual link color.
@link - color : @brand - primary;
//** Link hover color set via `darken()` function.
@link - hover - color : darken(@link - color, 15 %);
//** Link hover decoration.
@link - hover - decoration : underline;
```
Where spaces have been inserted either side of hyphens in variable names and (not shown in the snippet above) indentation is messed up and comments and code become entangled.

Yet all the files I've had problems with work perfectly when pasted into the web app on prettydiff.com, which also reports it is version 1.14.8

**Comment by prettydiff** [comment]
I am thinking this is a language detection problem.  When I paste the raw file into the web tool I get similar defects, because the application guesses its JavaScript instead of CSS.  When you use the web tool do have a specific language set or is it using the default value `auto`?

**Comment by davidscotson** [comment]
I've tried it both with and without, and seem to see the same thing. Both the following commands produce identical, broken, output:

```
 prettydiff  source:"/Users/dscotson/github/bootstrap/less/variables.less" mode:"beautify"

prettydiff  source:"/Users/dscotson/github/bootstrap/less/variables.less" mode:"beautify" lang:"less"
```
