### ISSUE TITLE
Arrow function arguments formatting

### ISSUE THREAD

**Issue by animecyc** [prettydiff/prettydiff#199]
Seeing some strangeness with arrow function arguments:

```javascript
let filter = (state, action) => {
   // ...
};
```

becomes: 

```javascript
let filter = (state,
action) => {
   // ...
};
```

I would imagine the arguments should remain on the same line no?

**Comment by rishitank** [comment]
I can confirm that this issue is still alive and well...

**Comment by prettydiff** [comment]
@rishitank Could you please provide me with a code sample?  The code sample at the top of this issue works for me.

**Comment by rishitank** [comment]
Hi,

After some more experimentation I've found that it has something to do with the wrap option. I use these options:
`/*prettydiff.com brace_style: "none", braceline: false, bracepadding: false, commline: false, correct: true, crlf: false, dustjs: false, elseline: false, endcomma: "never", force_attribute: false, force_indent: false, formatArray: "default", formatObject: "indent", functionname: false, html: true, inchar: " ", jekyll: false, jsscope: "none", methodchain: "none", mode: "beautify", nochainindent: false, objsort: "all", quoteConvert: "none", spaceclose: true, style: "indent", tagmerge: true, tagsort: false, ternaryline: false, textpreserve: false, unformatted: true, varword: "none", vertical: "none", wrap: "0" */`

If I enter this on the online prettydiff editor:
`import React, { Component } from 'react';

class BookingSummaryView extends Component {

render() {
        return (
                                   <div className="content panel-body padding-t-0">
                                       {
                                          segments.map((segment, index) => {
                                             return (
                                                <div key={segment.flightNumber} className="section">
                                                   <div className="divider" />
                                                   <div className="header">
                                                      <Label>{moment(segment.departDateTime).format('ddd, D MMM YYYY')}</Label>
                                                      <Label>{segment.flightNumber}</Label>
                                                   </div>
                                                   <div className="journey">
                                                      <div className="depart text-left">
                                                         <Label>Depart</Label>
                                                         <Label className="airport-code">{segment.origin.airportCode}</Label>
                                                         <Label>{departTime}</Label>
                                                      </div>
                                                      <i className={departing ? 'plane-birdseye-right' : 'plane-birdseye-left'} />
                                                      <div className="return text-right">
                                                         <Label>Arrive</Label>
                                                         <Label className="airport-code">{segment.destination.airportCode}</Label>
                                                         <Label>{arriveTime}</Label>
                                                      </div>
                                                   </div>
                                                   <div className="addons">
                                                      <Label>Add-ons</Label>
                                                      <div className="toggle-icon btn btn-default btn-yellow" onClick={() => {this.addonsToggle(segment)}}
                                                         data-toggle="collapse" data-target={`#${addonsCollapse}`} aria-expanded={departing ? true : false} aria-controls={addonsCollapse}>
                                                         <i className={`fa fa-fw ${toggled ? 'fa-minus' : 'fa-plus'}`}></i>
                                                      </div>
                                                   </div>
                                                   <div className={`addons-list ${returning ? 'collapse' : 'collapse in'}`} id={addonsCollapse} aria-expanded={departing ? true : false}>
                                                      {
                                                         data.passengers.map(passenger => {
                                                            DataUtils.fullName(passenger);
                                                            const addonsTotal = passenger.addons.reduce((sum, obj) => {
                                                               sum += obj.price;
                                                               return sum;
                                                            }, 0);
                                                            total += addonsTotal;
                                                            return (
                                                               <div key={passenger.fullName} className="passenger">
                                                                  <Label className="highlight">{passenger.fullName}</Label>
                                                                  <div className="passenger-addons">
                                                                     <div className="items">
                                                                        {
                                                                           passenger.addons.map((addon, index) => {
                                                                              return (
                                                                                 <Label key={`${addon.name}-${index}`} className="text-left">{addon.name}</Label>
                                                                              );
                                                                           })
                                                                        }
                                                                     </div>
                                                                     <Label className="price text-right">{`SGD ${numeral(addonsTotal).format('0.00')}`}</Label>
                                                                  </div>
                                                               </div>
                                                            );
                                                         })
                                                      }
                                                   </div>
                                                </div>
                                             );
                                          })
                                       }
                                    </div>
        );
    }
}

export default BookingSummaryView;`

it produces this:
`import React, {
    Component
} from 'react';

class BookingSummaryView extends Component {

    render() {
        return (
            <div className="content panel-body padding-t-0">
                {
                    segments.map((segment, index) => {
                        return (
                            <div key={segment.flightNumber} className="section">
                                <div className="divider" />
                                <div className="header">
                                    <Label>{moment(segment.departDateTime).format('ddd, D MMM YYYY')}</Label>
                                    <Label>{segment.flightNumber}</Label>
                                </div>
                                <div className="journey">
                                    <div className="depart text-left">
                                        <Label>Depart</Label>
                                        <Label className="airport-code">{segment.origin.airportCode}</Label>
                                        <Label>{departTime}</Label>
                                    </div>
                                    <i className={departing ? 'plane-birdseye-right' : 'plane-birdseye-left'} />
                                    <div className="return text-right">
                                        <Label>Arrive</Label>
                                        <Label className="airport-code">{segment.destination.airportCode}</Label>
                                        <Label>{arriveTime}</Label>
                                    </div>
                                </div>
                                <div className="addons">
                                    <Label>Add-ons</Label>
                                    <div className="toggle-icon btn btn-default btn-yellow" onClick={() => {this.addonsToggle(segment)}}
                                                         data-toggle="collapse" data-target={`#${addonsCollapse}`} aria-expanded={departing ? true : false} aria-controls={addonsCollapse}>
                                        <i className={`fa fa-fw ${toggled ? 'fa-minus' : 'fa-plus'}`} />
                                    </div>
                                </div>
                                <div className={`addons-list ${returning ? 'collapse' : 'collapse in'}`} id={addonsCollapse} aria-expanded={departing ? true : false}>
                                    {
                                        data.passengers.map(passenger => {
                                            DataUtils.fullName(passenger);
                                            const addonsTotal = passenger.addons.reduce((sum, obj) => {
                                                sum += obj.price;
                                                return sum;
                                            }, 0);
                                            total += addonsTotal;
                                            return (
                                                <div key={passenger.fullName} className="passenger">
                                                    <Label className="highlight">{passenger.fullName}</Label>
                                                    <div className="passenger-addons">
                                                        <div className="items">
                                                            {
                                                                passenger.addons.map((addon, index) => {
                                                                    return (
                                                                        <Label key={`${addon.name}-${index}`} className="text-left">{addon.name}</Label>
                                                                    );
                                                                });
                                                            }
                                                        </div>
                                                        <Label className="price text-right">{
                                                                `SGD ${numeral(addonsTotal).format('0.00')}`;
                                                            }</Label>
                                                    </div>
                                                </div>
                                            );
                                        });
                                    }
                                </div>
                            </div>
                        );
                    });
                }
            </div>
        );
    }
}

export default BookingSummaryView;`

If I set wrap to 80 or some higher value then you can see that arguments in an arrow function do not wrap on the next line... In the docs it says that setting wrap to 0 should disable text wrapping though.

**Comment by prettydiff** [comment]
I see.  Thank you for the code samples.  This is due to an update from last release: https://github.com/prettydiff/prettydiff/issues/397

In this case the code is looking at a parenthesis as a container and wrapping on commas if the contents of that container plus spaces are wider than the specified wrap limit.  In this case the application is operating correctly, because the block following the fat arrow is far wider than the wrap limit.

Although the application is operating correctly, this behavior could still be producing undesired results.  If you believe this enhancement makes the code harder to read or is in any way confusing please let me know.  I am also open to any suggestions or ideas you have for improved clarity.

I just verified and there is certainly some kind of defect when specifying a wrap value.  I am investigating now.

**Comment by prettydiff** [comment]
The defect is related to legacy code to wrap method arguments for JSX when they exceed the wrap limit.  I failed to remove this logic as it is no longer valid thanks to #397.  I am pushing the fix now to branch 2.1.17 and will push it to master once I resolve #268.

**Comment by rishitank** [comment]
Thanks for the quick response! Looking forward to the fix, having gone through many different beautification libraries for JS/JSX, prettydiff is definitely the closest to perfection. Keep up the great work 👍

Since I'm here, there was another thing I noticed. When writing JSX expressions inside some JSX tags it also gets wrapped onto separate lines and is given a semi-colon as you can see from my previous example:

```
<Label className="price text-right">{
    `SGD ${numeral(addonsTotal).format('0.00')}`;
 }</Label>
```

is this normal or is this related to some property I've set? (it happens regardless of what wrap is set to) It would be great if there were some options regarding customising the behaviour of how JSX expressions are shown, thanks.

**Comment by rishitank** [comment]
Upon further inspection I've found the issue with JSX expressions wrapping onto new lines to be a result of the 'correct' property. Although in some cases this can be useful, but in some cases it might be that the above behaviour might not be desirable, would it be possible to separate JSX expression handling from the behaviour of the 'correct' property as a separate property?

**Comment by prettydiff** [comment]
Is the semicolon there invalid?  It looks valid.  If it were an error it would this decision a whole lot easier.  On the other hand if this behavior is correct I would have to decide if I wanted to allow the `correct` changes in some contexts but not others, which is a hard decision to make that could complicate testing and mask some errors.

The `correct` option inserts missing semicolons, missing parenthesis (this doesn't exist in JavaScript but it does in Java), and missing curly braces.  When `correct` is set to false I am still actually creating these tokens internally and just not allowing them in the final output as this helps to manage evaluation of code statements and structures.

**Comment by rishitank** [comment]
I see, the semicolon is valid, however it might be intentional in some contexts to have it all on one line like this:
```
<Label className="price text-right">{`SGD ${numeral(addonsTotal).format('0.00')}`}</Label>
```

which may feel more concise. If the JSX expression were intentionally multiline however, then it would make sense to add semicolons where necessary. I also think that correcting a JSX expression to multiple lines may not keep the outer JSX tags aligned due to the placement of the curly braces.
