### ISSUE TITLE
it shouldn't break dot chain into multiple lines for properties

### ISSUE THREAD

**Issue by zachguo** [prettydiff/prettydiff#200]
in atom-beautify, it transforms 

```
let routes = this.context.router.getCurrentRoutes();
```

into

```
let routes = this.context
     .router
     .getCurrentRoutes();
```

but i think it's better to keep properties in one line and only break lines for consecutive method calls

```
let a = b.c.d.e.f;

let a = b.c.d.e.f();

let a = b.c.d()
           .e().f;

let a = b.c()
         .d()
         .e()
         .f();
```

your thought?

**Comment by prettydiff** [comment]
For the sake of simplicity I am going to change this slightly.

At this time the first property/method is retained on the same line as its object.  In the next release (that I am launching in about 10 minutes) I am going to either break everything or nothing (with the option `methodchain`).

    let a = b.c().d().e().f();

Will become

    let a = b
        .c()
        .d()
        .e()
        .f();

The one problem is your approach is that methods and flat properties can be intermixed:

    let a = b.c().d.e.f();

In this case a different behavior for properties versus functional methods becomes increasingly more complicated in both the code and for humans to read.  The difference in behavior can lead to errors of assumption when reading code where there are several steps of depth in one of those methods and the methods have long names that can hide short named properties at the end of the line.

I do appreciate the input very much though.  I will close the issue at this time, but please feel free to reopen this issue or create additional issues as you continue to think on this.
