### ISSUE TITLE
xml parse functionality: not reporting problem on misplaced document element

### ISSUE THREAD

**Issue by kaizer200** [prettydiff/prettydiff#207]
**_example**_

``` xml
<?xml version="1.0" standalone="yes" ?>
<!DOCTYPE PARENT>blabla
<foo>Hello World.</foo>
```

**_expected result**_
There should be an error on the second line, stating that document/content element (the 'blabla' string) is not valid before the root start tag( <foo>)
**_result**_
no error is thrown

**Comment by prettydiff** [comment]
I need to be much better about parsing errors and I am looking into that now.  This issue, though, is about a structure/grammar violation but the syntax looks well formed.  Pretty Diff 3 will not be performing code analysis so I am closing this for now.
