### ISSUE TITLE
xml parse functionality: error location and coherent messages

### ISSUE THREAD

**Issue by kaizer200** [prettydiff/prettydiff#213]
**_example**_

``` xml
<zz1>
   <!--comment1-->
<ns1 "aa"="3" >ddd</ns1>bbb
</zz1>
```

The problem is the attribute "aa" (should be without the quotes)
**result**
1) three error messages on the forth line.
2) error messages:
element parse error: Error: attribute value must after "="
end tag name: ns1 doe not match the current start tagName: zz1
end tag name not fuond for: zz1

**expected result**
1) one message on third line
2) message should be: error parsing attribute name

**Comment by prettydiff** [comment]
Pretty Diff 3 appears to be parsing this without issue.  Although this code sample is an XML violation it is still syntax well formed enough for clean parsing.  Since Pretty Diff 3 will not performance analysis I am closing this issue.
