### ISSUE TITLE
xml parse functionality recommendation: supply new token types

### ISSUE THREAD

**Issue by kaizer200** [prettydiff/prettydiff#214]
Hi,
I suggest new token types: attribute-name, attribute value.

**example**

``` xml
<zz1 a1='2'>
</zz1>
```

**result**
the <zz1 a1=2> is reported as one token, type start

**expected / recommended result**

| index | types | token |
| --- | --- | --- |
| 0 | start | zz1 |
| 1 | attrib | a1 |
| 2 | attributeValue | 2 |
| 3 | end | /zz1 |

**Comment by prettydiff** [comment]
In Pretty Diff 2 I did break out attribute values from attribute names.  In Pretty Diff 3 I am not doing this because it was causing problems with template engines that use attributes as pre-processor instructions within tags.  I may come back to this later though.
