### ISSUE TITLE
Expose xml parsing errors by parse functionality

### ISSUE THREAD

**Issue by kaizer200** [prettydiff/prettydiff#215]
Hi,
I would like prettydiff's **XML** parse functionality to  return also the parsing problems it found.
This can be independent property of the parse(args) return object, from the tokens & types 

minium info for parsing-problem object: {line: , message: } 

enhanced parsing problem object: {line: ,message: , column: , relatedToken: }  - column is the problematic token's starting char relative to **line** start.
another option for enhanced problem object: {line: ,message: , index: , relatedToken: }  - index is the problematic token's starting char, relative to the start of the **parsed** source start.

**Comment by prettydiff** [comment]
Yes, this is happening now.
