### ISSUE TITLE
Using prettydiff in browser

### ISSUE THREAD

**Issue by mattanbi** [prettydiff/prettydiff#216]
Hi,
Currently to use models, like "markupretty" or "safeSort" with requireJs in the browser 
1. the code needs to be wrapped 
2. the variable "global" needs to be defined
3. the method needs to be returned
- for example

define([], function(){

var global = {};

......original model safesort.js goes in here....

return safesort;

})

this will be very hard to maintain and upgrade. 
Is it possible to get these AMD modules from your build each time a new version is released?
thanks

**Comment by prettydiff** [comment]
> Is it possible to get these AMD modules from your build each time a new version is released?

I do not understand.  Each time a new version is released the code is updated on the website, Github, and NPM.  The easiest way to get the latest and freshest code is from NPM.

Honestly, the way the libraries come together is insanity.  I built it like this for modularity in a way that works without any build process in the browser, with Node, and with Require.js all simultaneously.  Just a couple of months ago everything, aside from the API files, was in a single file at about 12000 lines of code.  It's unfortunate that I have to go through so much boilerplate and decoration just to make the code more modular.  I am hoping ES6 modules will solve this problem, but currently this isn't supported anywhere.

**Comment by prettydiff** [comment]
At the bottom of each library file there is code like this:

    define(function requirejs(require, exports) {
        "use strict";
        exports.api     = function requirejs_export(x) {
            return markuppretty(x);
        };
        //worthless if block to appease RequireJS and JSLint
        if (typeof require === "number") {
            return require;
        }
        return exports.api;
    });

Is that code ineffective for you?  The code file should be immediately ready for import by require.js..... aside from creating an object named *global*.
