### ISSUE TITLE
prettydiff and rails

### ISSUE THREAD

**Issue by kelvix** [prettydiff/prettydiff#221]
I'm actually using this via atom-beautify the results of attempting to apply a beautify on the following rails code is a bit interesting

    <div class="container">
      <% flash.each do | key, value | %>
        <div class="alert alert-"<%= key %>>
          <%= value %>
        </div>
      <% end %>
      <%= yield %>
    </div>

The previous gets turned into

    <div class="container">
      <% flash.each do | key, value | %>
      <div % <%= class="alert alert-" key>>
        <%= value %>
      </div>
      <% end %>
      <%= yield %>
    </div>

First mentioned at https://github.com/Glavin001/atom-beautify/issues/693

**Comment by prettydiff** [comment]
The problem, I believe, is that you are expecting `<% flash.each do | key, value | %>` to be a start tag that applies an extra step of indentation.  From only looking at the syntax I have no idea this would be a start tag.

The other issue is the embedded tag in: `<div class="alert alert-"<%= key %>>`.  That is a defect that can be fixed.

**Comment by prettydiff** [comment]
Try testing out a bunch of code samples at http://prettydiff.com/ignore/testlocation/index.xhtml

I believe I fixed the embedded tag mutilation issue.

**Comment by kelvix** [comment]
These are the current results

        <div class="container">
          <% flash.each do | key, value | %>
            <div class="alert alert-"<%= key %>>
              <%= value %>
            </div>
          <% end %>
          <%= yield %>
        </div>

Gets turned into 

    <div class="container">
        <% flash.each do | key, value | %>
        <div <%= key %> class="alert alert-">
            <%= value %>
        </div>
        <% end %>
        <%= yield %>
    </div>

Rails will at the least not cause an evil looking stack trace. Styling that relied on ```key``` to follow ```alert-``` would be off. As the resulting html from rails would look like.

    <div class="container">
      <div error class="alert alert-">
          Invalid email/password combination
      </div>
      <div class="row">
        <div class="large-12 columns">
            ...

**Comment by prettydiff** [comment]
I changed the application so that tags containing embedded ruby tags as attributes will not have their attributes sorted: http://prettydiff.com/ignore/testlocation/index.xhtml

**Comment by kelvix** [comment]
That works!

**Comment by prettydiff** [comment]
Version 1.16.1 will launch soon.  I am going through some final QA for upcoming ColdFusion support.  I suspect this will launch in the next two days or soon.
