### ISSUE TITLE
Sometimes, prettydiff cannot generate output results but should generate results

### ISSUE THREAD

**Issue by puchang** [prettydiff/prettydiff#222]
prettydiff 2 directory for 100 times, there are about 5 times when there are no result files in output directory.

**Comment by prettydiff** [comment]
This is a defect in async file read in api/node-local.js

**Comment by prettydiff** [comment]
Out of curiosity were any of the files in those directories binaries?

**Comment by prettydiff** [comment]
Also, is this on Windows, OSX, or Linux?

**Comment by puchang** [comment]
No binary files in thoese directory
This happened on Linux

**Comment by prettydiff** [comment]
This is challenging.  It will demand a unique application to cycle a simulation over and over looking for timing descrepencies between my api/node-local.js file, Node's file system bindings, and the actual artifacts represent on the file system.

I am getting closer though with an artifact that hints at symptoms to this problem.  I can provide steps to reproduce once I publish the next release.

**Comment by prettydiff** [comment]
Pretty Diff is rewritten from scratch.  Closing this issue.
