### ISSUE TITLE
Unexpected space between name and arg list in ES6 class methods

### ISSUE THREAD

**Issue by amacdougall** [prettydiff/prettydiff#228]
ES6 classes are beautifying with an unexpected space before the `()`. Other function types are not.
```javascript
class Foo {
  doStuff () {}

  get propName () {
    return this._propName;
  }
}

function doStuff() {} // fine

var doStuff = function() {} // fine; controlled by a flag

var obj = {
  shorthandFunction() {} // fine, somewhat surprisingly
}
```
If this is not a bug, it would be nice to control the behavior with an option. I'm happy to do the work and make a pull request.

**Comment by prettydiff** [comment]
You can test out the solution at http://prettydiff.com/ignore/testlocation/index.xhtml?mode=beautify

**Comment by amacdougall** [comment]
That appears to resolve it! Amazing turnaround. I usually offer to patch the code and PR, because I know that open-source maintainers are usually very busy with other projects, but you're really on top of this project. :beers:

**Comment by prettydiff** [comment]
Thanks, I will see if I can complete the two new options tonight.  If so I will launch these once my ColdFusion support is complete in issue #158.

**Comment by amacdougall** [comment]
ColdFusion support is beyond the call of duty. You have my respect!
