### ISSUE TITLE
Wishlist: Upload diff files

### ISSUE THREAD

**Issue by fzakaria** [prettydiff/prettydiff#232]
I'd love to be able to upload already generated diff/patch files from either git/svn/etc..

Sometimes colleagues send me diffs over emails and I'd love to just visualize the diffs easier

**Comment by prettydiff** [comment]
Are you suggesting like a gist or pastebin type site for code diffs that can be referenced by address?

**Comment by fzakaria** [comment]
I guess I was thinking:

```
diff --git a/man.xml b/man.xml
index d27e6e9..088c661 100644
--- a/man.txt
+++ b/man.txt
@@ -1 +1,2 @@
 this old man
+she said three

If it was saved into the file (diff.patch and uploaded) you could view the diffs with some nicer colors or inline view or w/e

**Comment by prettydiff** [comment]
I am going to close this for now.  The terminal tool can already resolve code as strings from URIs.  If the terminal has shared keys to access code stored in an online repository the code is stored somewhere and Pretty Diff can locally execute against it.
