### ISSUE TITLE
JS error while diffing 2 files

### ISSUE THREAD

**Issue by ddehghan** [prettydiff/prettydiff#233]
This website does not run for me when I try to compare 2 minified versions of my file. 

![screenshot 2015-12-11 23 43 38](https://cloud.githubusercontent.com/assets/717686/11760858/719e20e6-a061-11e5-852a-61231cc71e8e.png)

**Comment by ddehghan** [comment]
More debugging info for you:

![screenshot 2015-12-12 00 03 26](https://cloud.githubusercontent.com/assets/717686/11760929/d9dbe286-a063-11e5-8df2-ac416cbf5428.png)

**Comment by prettydiff** [comment]
I am taking out my window.onerror event handler, because it has been suppressing valid error messages since I have made the code more modular.  Would you mind attempting to briefly retrace your steps at http://prettydiff.com/ignore/testlocation

There you might be able to generate the problem with a better error message.  Thanks so much for the bug report.

**Comment by ddehghan** [comment]
ok. i tried. still the same problem .

![screenshot 2015-12-12 06 40 41](https://cloud.githubusercontent.com/assets/717686/11762445/691ec076-a09b-11e5-8c24-dbf257cb7942.png)

**Comment by ddehghan** [comment]
Hi Austin- I emailed you my 2 files to info@prettydiff.  That will make it easier for you to repro the problem yourself.

**Comment by prettydiff** [comment]
Thank you so very much @ddehghan I will keep this thread updated as I investigate further.

**Comment by prettydiff** [comment]
@ddehghan I did not get your email. info@prettydiff.com is the correct email address.  I still look forward to identifying and solving this issue.  Thank you for your assistance.

**Comment by prettydiff** [comment]
Would you be able to create a gist with the two files?

**Comment by ddehghan** [comment]
Sorry. I think email keeps removing the attachment.

Here the 2 files:

https://dl.dropboxusercontent.com/u/25328977/Archive.zip

**Comment by prettydiff** [comment]
Got them!  Thanks so much!

**Comment by prettydiff** [comment]
The problem is with lib/jspretty.js line 3108: `varlen[varlen.length - 1].push(a - 1);`  That array had no child elements to push things into.  A fix is available at http://prettydiff.com/ignore/testlocation/lib/jspretty.js
