### ISSUE TITLE
Conditions in tags get rearranged in twig templates

### ISSUE THREAD

**Issue by EisFrei** [prettydiff/prettydiff#236]
I've been using atom-beautify on twig templates, only to realize that it messed up some logic parts of the templates.

When beautifying twig templates, conditions inside of tags get interpreted as attributes, changing **if [...] endif** to **endif [...] if**.

```twig
<html>
  <body>
    <a href="/linktarget.html" {% if active %}class="active"{% endif %}>linktext</a>
  </body>
</html>
```

turns into

```twig
<html>
  <body>
    <a class="active" href="/linktarget.html" {% endif %} {% if active %}>linktext</a>
  </body>
</html>
```

**Comment by prettydiff** [comment]
In the next release tags containing Twig template tags as attributes will no longer have their attributes sorted.  http://prettydiff.com/ignore/testlocation/index.xhtml?m=beautify
