### ISSUE TITLE
npm install of version 1.6.1 is missing prettydiff.js file?

### ISSUE THREAD

**Issue by leslc** [prettydiff/prettydiff#237]
I'm not sure why this would be happening, but installing version 1.6.1 with "npm install prettydiff@1.6.1" is missing the "prettydiff.js" file.  Installing at version 1.6.0 has the file.  This is causing compile issues in packages that depend on prettydiff. 

However I see the file in the repo.  Is this a publishing error?  Can someone verify and possibly republish?

Thank you!

**Comment by leslc** [comment]
Seems like others are experiencing a missing main file on publish: https://github.com/npm/npm/issues/5082.  If you see the same issue running "npm install prettydiff@latest", can you republish at 1.6.2 to see if that fixes the issue?

**Comment by prettydiff** [comment]
Bumping version to 1.16.2 and republishing....

**Comment by prettydiff** [comment]
Appears to be fixed now.  Thank you so much for bringing this to my attention!

**Comment by leslc** [comment]
Thank you @prettydiff!
