### ISSUE TITLE
File your V8 bugs at https://bugs.chromium.org/p/v8/

### ISSUE THREAD

**Issue by caitp** [prettydiff/prettydiff#240]
The spurious/inconsistent CI failures do look like an issue, either with V8 or with the embedder. It's possible there's a bug with lexical declarations in one or more of the compilers, or something similar.

Please file this at https://bugs.chromium.org/p/v8/, so that it can be looked at. Thanks for your patience!

**Comment by prettydiff** [comment]
Thank you very much!  Issue filed: https://bugs.chromium.org/p/v8/issues/detail?id=4635

**Comment by prettydiff** [comment]
Closing as resolved with Node v5.4.1.  I can no longer reproduce the defect after updating Node.
