### ISSUE TITLE
Error: Cannot find module 'prettydiff'

### ISSUE THREAD

**Issue by davestevens** [prettydiff/prettydiff#242]
I'm seeing this error when trying to require prettydiff, v1.16.0 and below works, v1.16.1 & v1.16.3 throw an error.

I've tried with node v5.1.1 and npm v3 and v2.14.14.

**Comment by retallicka** [comment]
+1

**Comment by stephanedemotte** [comment]
+1

**Comment by stephanedemotte** [comment]
for quick fix npm install prettydiff@1.16.4

**Comment by prettydiff** [comment]
For the past few months I have been trouble getting the latest version by just using

    npm install prettydiff

What seems to work is

    npm update prettydiff

Also

    npm install prettydiff@latest

It makes me wonder if NPM 3 has some sort of cache mechanism.  This morning I bumped up to 1.16.5 to help troubleshooting of this issue: https://bugs.chromium.org/p/v8/issues/detail?id=4635

If 1.16.4 or 1.16.5 still contain this problem please let me know.

**Comment by mrak** [comment]
It appears that the `main` file is pointing to `prettydiff.js`, which does not exist under `node_modules/prettydiff`.

There might be a broken deployment somewhere that is leaving this file out. I've seen it happen before with `index.js` files being left out of an `npm publish`

**Comment by prettydiff** [comment]
Yeah.... https://github.com/prettydiff/prettydiff/issues/237

**Comment by prettydiff** [comment]
I just realized this problem is also related to the current version 1.16.5.  I am publishing to 1.16.6 now.

**Comment by prettydiff** [comment]
I just verified prettydiff.js is there in 1.16.6.

**Comment by davestevens** [comment]
Just installed the latest and it works now, thanks a lot!
