### ISSUE TITLE
where is the change log.

### ISSUE THREAD

**Issue by peterma** [prettydiff/prettydiff#243]
Hi, I can't find the change log. Please provide the address, thanks in advance.

**Comment by prettydiff** [comment]
I don't have one.  Would you have a good example for one?

**Comment by peterma** [comment]
Here is a good example: 
https://github.com/pheuter/essential-react/blob/master/CHANGELOG.md

**Comment by prettydiff** [comment]
I should be doing something exactly like that.  I will integrate this into the workflow.

**Comment by peterma** [comment]
Thanks for your work!

**Comment by jerone** [comment]
If you need a little automation, you could try [pr-changelog](https://github.com/benogle/pr-changelog).
