### ISSUE TITLE
Wishlist: providing an ignore space option.

### ISSUE THREAD

**Issue by peterma** [prettydiff/prettydiff#245]
Like subversion comparison, we can set "ignore space", then new or deleted spaces will be ignored.

**Comment by prettydiff** [comment]
That is a great idea that should have been there all along.

**Comment by prettydiff** [comment]
You can test this out at http://prettydiff.com/ignore/testlocation/index.xhtml

You need to scroll down the page a little bit and look for the option `diffspaceignore`.  You will also most likely need to change the language option to *Plain Text* to really take advantage of this.
