### ISSUE TITLE
Option - force indent attributes

### ISSUE THREAD

**Issue by ThePlenkov** [prettydiff/prettydiff#255]
Dear developers,

Thanks for the service - it's great.

However there is an issue that I can't solve just by choosing valid parameter.

Let's say I have a file that represents a view:

<mvc:View
   xmlns="sap.m"
   xmlns:mvc="sap.ui.core.mvc"
    controllerName="sap.ui.demo.wt.controller.App"
   displayBlock="true">
</mvc:View>

Now I want to beautify it with your service and the result is like this::

<mvc:View xmlns="sap.m" xmlns:mvc="sap.ui.core.mvc" controllerName="sap.ui.demo.wt.controller.App" displayBlock="true">
   
</mvc:View>

You see - in the xml file we have all the attributes in the same line.

To be honest - it's not suitable for porgramming - the file should be easily readable.

Now the question is: Is it possible somehow to split attributes into separate lines? If you don't have such an option yet - could you please provide? 

Thanks!

**Comment by prettydiff** [comment]
I have completed this locally and it will go out in the next update.

**Comment by prettydiff** [comment]
Completed with the `force_attribute` option - http://prettydiff.com/documentation.xhtml#force_attribute
