### ISSUE TITLE
Fails if there is a comment is the XML

### ISSUE THREAD

**Issue by mrchess** [prettydiff/prettydiff#257]
**Description:**
Fails to diff there is a comment is the XML

**Steps to reproduce:**
1. Go to prettydiff.com
2. Put in the following information
3. Click "Execute"

base
```
<person>
    <!-- comment -->
    <name>bob</name>
</person>
```

new
```
<person>
    <!-- comment -->
    <name>alice</name>
</person>
```

**Expected**

Detects the change from "bob" to "alice"

**Actual**

Does not detect change. Says there are no diffs.

**Comment by prettydiff** [comment]
Its a parse failure in the lib/markuppretty.js file.  Continuing to examine.

**Comment by prettydiff** [comment]
I need to add the flag `comment` before or after line 576: https://github.com/prettydiff/prettydiff/blob/master/lib/markuppretty.js#L576

You can demo the solution at http://prettydiff.com/ignore/testlocation

I hope to publish the solution tonight.  The next publication is waiting behind issue #253.  The rest of the issues scheduled for v1.16.13 will be pushed to v1.16.14.

**Comment by prettydiff** [comment]
Fix released in v.1.16.13
