### ISSUE TITLE
Fails if there is a Script tag in XML

### ISSUE THREAD

**Issue by sakazuki** [prettydiff/prettydiff#258]
**Steps to reproduce:**
1. Go to prettydiff.com
2. Put in the following information
3. Click "Execute"

base
```
<A>
    <B>1</B>
    <script1>b</script1>
    <script>b</script>
    <Script>123</Script>
</A>
```

diff
```
<A>
    <B>1</B>
    <script1>c</script1>
    <script>c</script>
    <Script>456</Script>
</A>
```

**Expected**
* Show all lines
* Detect the change in line 4 and 5.

**Actual**
* Don't show all lines
* line 4, does not detect change .
* line 5, break

**Comment by prettydiff** [comment]
Thank you.  I have a fix at http://prettydiff.com/ignore/testlocation/lib/markupprettydiff.js

I will publish this correction once I conclude issue #253, which will likely be today.

**Comment by prettydiff** [comment]
Fix released in v.1.16.13
