### ISSUE TITLE
jsx classnames being made lower case 

### ISSUE THREAD

**Issue by tnrich** [prettydiff/prettydiff#259]
This
`classnames('twistCircularButton secondary downloadTemplateButton', `
Goes to this: 
`classnames('twistcircularbutton secondary downloadtemplatebutton',`

Is there any way to turn it off?

**Comment by prettydiff** [comment]
No that would be a bug and not a feature.  I am having trouble reproducing the problem though.  Would you be able to provide some additional code?

**Comment by prettydiff** [comment]
Closing potential defect due to an inability to reproduce.
