### ISSUE TITLE
Convert project to CC0 license

### ISSUE THREAD

**Issue by prettydiff** [prettydiff/prettydiff#269]
Dependent upon completion of https://github.com/prettydiff/prettydiff/issues/268

I need to verify and remove existing license text from all locations including:
- readme.md
- documentation.xhtml
- all JS and CSS files

New license text will only occur in license.txt document.  readme.md and documentation.xhtml will refer claim project is under MIT license and point to the license.txt for the text of the license.

**Comment by prettydiff** [comment]
#268 is the immediate priority.  All other work on this project and all other projects is blocked pending completion of #268.  Pretty Diff will not publish any further work, accept as git commits to branch 2.1.17, until #268 and #269 are resolved.  Once these two issues are resolved Pretty Diff will immediately merge branch 2.1.17 to master as the next version named 2.2.0.

In response to https://github.com/prettydiff/prettydiff/issues/291#issuecomment-277391248 I will be writing a new and original open source license.  The primary points are as follows:

* The license will proclaim the software (which includes its source code, APIs, documentation, execution contexts, and all artifacts included or implied) are free and open.
* The software may be copied, manually redistributed, executed, or modified without the permission or knowledge of the owner, author, or publisher.
* The software is published as is without any warrant express or implied.  Use at your own risk.  The author, owner, and publisher accept no fault or liability for defects or harms incurred from the use or presence of this software whether direct or indirect.
* The software may be published in any form or method that allows immediate access to said software by protocol or address.  Intermediary access means will be expressly forbidden, which may constitute proxies, named registries, address redirection, or other means that does not result in immediate access upon request.  Examples of allowed publication are an address to file(s) that comprise the software, or a URI/ISBN that returns the software from a library.  In that case URI and ISBN identifiers obfuscate an artifact behind an identifier that comprises a standard protocol.  Examples of forbidden publication would be HTTP 301, which is a redirection in a proxy like fashion.  Another example of forbidden publication would be Yarn and NPM with obfuscate access behind a named identifier much like URI or ISBN, except this identifier comprises a commercial registry opposed to a standard protocol.
* The software is free from forms of payment and favor as well as free from royalty directly and from derivatives.
* This license grants the protected artifact to enter the public domain with immediate sacrifice to all protections and rights contrary to public domain access.

**Comment by prettydiff** [comment]
I will need somebody smarter than me to review the above points to certify that they are not contradictory.

**Comment by prettydiff** [comment]
https://github.com/prettydiff/liberty-license

**Comment by ljharb** [comment]
I'm pretty sure your license can't be valid because it excludes distribution on Github, because Github relies exclusively on named identifiers (you also haven't defined "equitable", which I'd expect any lawyer would tell you makes the entire license unenforceable). Named registries are pretty indistinguishable from URLs, or github usernames, based on how you've described them.

**Comment by prettydiff** [comment]
Internally to Github that is completely true, but externally its still git which uses URI.  I was thinking about the language I wrote this morning and it has a lot of problems that need further thought.

The biggest problems:

* Many of the points are begging collections of evidence in determination of potential violations.  That is basically an invitation for subpoenas and search warrants, which is a horrid thought.
* The part about the license self-destructing in the case where IP violations occur is bad, because thoughtless stupidity in a distant derivative shouldn't provide an excuse to potentially poison everybody else.  Violations should be limited to the smallest contained area.

How did you come across this so quickly?

**Comment by ljharb** [comment]
npm uses URIs too, exclusively, and in all respects you won't be able to restrict npm while allowing Github, I suspect.

Writing a license takes being a lawyer with many years of training, so I'd suggest retaining one if you seriously want to slap a new license on this project (as opposed to using one of the many pre-existing, vetted, understandable, reliable ones)

**Comment by alanshutko** [comment]
I believe the republication clauses make it impossible for this license to be open source according to the OSI (https://opensource.org/osd) or free software according to the FSF (https://www.gnu.org/philosophy/free-sw.en.html).

**Comment by prettydiff** [comment]
I will abandon this attempt and just convert it to ISC license once I change out the diff library. https://opensource.org/licenses/ISC

**Comment by prettydiff** [comment]
I have chosen to go with a CC0 license (almost public domain).  I will merge this soon.
