### ISSUE TITLE
Repeated beautification deletes code

### ISSUE THREAD

**Issue by filipesilva** [prettydiff/prettydiff#272]
Heya,

Trying to beautify this piece of angular html template leads to code being deleted:

```
<dd>
  {{ vm.data.contractTypes | filter: {value: vm.data.jobOffer.contract_type} | first | property:'label' }}
</dd>
```

It seems to be related to the inner brackets (it's still valid angular syntax). Happens on the web interface as well.

Here is a gif, using Atom
![beautify-delete](https://cloud.githubusercontent.com/assets/4172079/13258552/80789794-da4b-11e5-86ce-c8a3b133695b.gif)
:

**Comment by prettydiff** [comment]
Publishing resolution to v1.16.19 right now.

**Comment by filipesilva** [comment]
Cheers!
