### ISSUE TITLE
Log data sent to stdout after minify with readmethod:"filescreen"

### ISSUE THREAD

**Issue by dpoggi** [prettydiff/prettydiff#273]
Hi! I primarily use prettydiff as a JS minification tool, and while that may not be its primary use case, I've been having a problem lately:

Since 1.6.13, with the addition of "enderflag" in node-local.js ([line 1540](https://github.com/prettydiff/prettydiff/blob/master/api/node-local.js#L1540)), prettydiff sends log output at the end of the minified code to stdout, even with `readmethod:"filescreen"`. What this means in practice is that if I pipe the minified JS to some other program, or send it through sed then into a file, I have:

Pretty Diff minified 1 file. Executed in 0.062 seconds.

At the end of something I *really* don't want it at the end of. Sure, I could pipe it to `head -n-3` first, but doesn't that defy the point? I'm more than happy to put in a PR with a solution, but there's a few ways I can think of to go about this, and I'd like to solicit opinions first:

* Send all log data to stderr always (not a bad option considering that `readmethod:"filescreen"` exists)
* Send all log data to stderr only when `readmethod:"filescreen"`
* Set `enderflag = true` early in execution when `readmethod:"filescreen"`
* Offer "quiet" or similar as a CLI flag to silence this type of output

Other suggestions or thoughts on the four above? The third and fourth are probably the easiest to implement, the other two require replacing all usages of the global `console` with a custom-initialized instance of `console.Console`, but may be more "Unix correct," if that's a thing.

Oh, in case it matters - tested with Node v5.7.0 / npm v3.6.0 on OS X 10.11.3 and Node v5.6.0 / npm v3.7.3 on CentOS 7.

**Comment by prettydiff** [comment]
I am not going to be sending anything to stderr as this would crush my unit test runner.  I have completely removed the terminal logging when readmethod is screen or filescreen and I added the option http://prettydiff.com/documentation.xhtml#endquietly

This option accepts a string type of these three values

* quiet - forcefully suppress terminal logging
* log - override the new default behavior for screen and filescreen readmethods and force the messaging to screen
* anything else is simply default behavior.

I just published as v1.16.20.
