### ISSUE TITLE
JS: preserve array literal indentation

### ISSUE THREAD

**Issue by jackocnr** [prettydiff/prettydiff#276]
I would also love to see this. Equivalent to JS Beautify's `keep_array_indentation`. So if I define my array literal on one line it is preserved e.g.
```js
var a = ["one", "two", "three"];
```
(currently this gets split up into multiple lines)

**Comment by jackocnr** [comment]
Oh no I see: `preventflatten` can only prevent flattening, it can't prevent expanding!

**Comment by jackocnr** [comment]
Anyway some feedback on your proposed solution: I don't think it works to have a single `flatten` option that applies to array literals, object literals and more. What I personally want (and I understand this doesn't apply to everyone) is: for array literals to be on one line (including square brackets) if they fit (i.e. less than 80 chars), else each array item on it's own line. For object literals: always a new line for each property.

**Comment by amacdougall** [comment]
I made the request that originally led to the `neverflatten` option. My concern was ES6 object destructuring. For instance, say we have a large `options` hash with many properties, but I only care about a few. In ES6, I can do this:
```javascript
var {username, password} = user;

// or as function params:
function login({username, password}) {
  // do the login
}
```
In both those cases, I would prefer to have a single line instead of:
```
function login({
  username,
  password
}) {
  // implementation
}
```
I get that it's a sticky problem.

**Comment by prettydiff** [comment]
I will probably modify `neverflatten` to have something like a: `always`, `never`, and default option.  Based upon both of your feedback I will keep this behavior related only to objects and create an identical option/behavior exclusively for arrays.  That they can be regulated independently.

**Comment by jackocnr** [comment]
@amacdougall that's interesting. Couldn't we treat the two situations differently? My use case is for object literals (with values): 
```js
{
   a: 1,
   b: 2
}
```
Whereas @amacdougall's use case is for ES6 destructuring statements (without values):
```js
{a, b}
```

**Comment by amacdougall** [comment]
Yep—one easy way is to simply distinguish between the two syntaxes.

**Comment by prettydiff** [comment]
This is done and in the 2.0.1 branch.  This is just pending unit tests.  I expect to publish this tomorrow.

**Comment by prettydiff** [comment]
Merged to master.
