### ISSUE TITLE
JS: preserve object literal indentation

### ISSUE THREAD

**Issue by jackocnr** [prettydiff/prettydiff#277]
Currently if I have this:
```js
var selectedFlag = $("<div>", {
    "class": "selected-flag"
});
```
It gets formatted to a single line:
```js
var selectedFlag = $("<div>", {"class": "selected-flag"});
```
It would be great to have a way to preserve the original formatting of the object literal.

**Comment by prettydiff** [comment]
This is done and in the 2.0.1 branch.  This is just pending unit tests.  I expect to publish this tomorrow.

**Comment by prettydiff** [comment]
Merged to master.
