### ISSUE TITLE
JSX Beautify

### ISSUE THREAD

**Issue by sizeon** [prettydiff/prettydiff#279]
Is it possible to have the attributes on tags on separate lines while preserving order? 

Sometimes it gets ridiculously long and hard to read.

From

` <Test x={x} a={a} d={d} g={w} />`

To
`<Test `
`   x={x} `
`  a={a} `
`  d={d} `
`  g={w}`
`  />`

**Comment by prettydiff** [comment]
Try setting the [force_attribute](http://prettydiff.com/documentation.xhtml#force_attribute) option to true.  Let me know the outcome so that I can provide you a better answer.

**Comment by sizeon** [comment]
@Galvin001
I am using Atom Beautify on jsx.  I can't find an option in atom beautify that has force_attribute. Can you add it?

**Comment by prettydiff** [comment]
@sizeon Yeah, this is really new option to Pretty Diff, so it doesn't exist yet in Atom Beautify.  Glavin has been moving at light speed lately with various different pull requests in the backlog.  This will happen much faster if you author the pull request.
