### ISSUE TITLE
Add support for Apache Velocity language

### ISSUE THREAD

**Issue by rediris** [prettydiff/prettydiff#280]
> Atom Beautify could not determine a supported beautifier to handle this file with grammar "Velocity (HTML)" and extension "vtl" or "vm". If you would like to request support for this file and its language, please create an issue for Atom Beautify at https://github.com/Glavin001/atom-beautify/issues.

I have already opened an issue in Atom Beautify: https://github.com/Glavin001/atom-beautify/issues/522

### Velocity reference guide
* http://velocity.apache.org/engine/devel/vtl-reference-guide.html

I have tried running this through http://prettydiff.com/?m=beautify

While there wasn't a specific selection for Velocity in prettydiff, it seemed to work... somewhat using with **markup (non-specific)**, **force indent**, and **preserve white space** in text. Without those settings enabled, it seems to take the `#` used in velocity and attempt to put it all on the same line. It still needs some additional work for velocity, it seems.

Here's the original sample I submitted:
```
## THIS IS A VELOCITY SINGLE-LINE COMMENT

#if($this)
  #set($that = true)
#end

#* 
 THIS IS A VELOCITY COMMENT BLOCK
 LET'S SEE WHAT HAPPENS
*#

#foreach( $item in $list )
  <article>
    <h1>$item.title</h1>
    <p>$item.copy</p>
    <a href="$item.url" class="$item.class">$item.buttonText</a>
  </article>
#end
```

The results using markup (non-specific) only:
```
## THIS IS A VELOCITY SINGLE-LINE COMMENT #if($this) #set($that = true) #end #*
THIS IS A VELOCITY COMMENT BLOCK LET'S SEE WHAT HAPPENS *# #foreach( $item in
$list )
<article>
    <h1>
        $item.title
    </h1>
    <p>
        $item.copy
    </p>
    <a class="$item.class" href="$item.url">
        $item.buttonText
    </a>
</article>
```
Obviously, that is hardly what I started with.

Here's the same example with **force indent** and **preserve white space**:
```
## THIS IS A VELOCITY SINGLE-LINE COMMENT

#if($this)
  #set($that = true)
#end

#* 
 THIS IS A VELOCITY COMMENT BLOCK
 LET'S SEE WHAT HAPPENS
*#

#foreach($item in $list)
  
<article>
    <h1>$item.title
    </h1>
    <p>$item.copy
    </p>
    <a class="$item.class" href="$item.url">$item.buttonText
    </a>
</article>
```

It's still missing the closing `#end` in the `#foreach`, unfortunately.

**Comment by prettydiff** [comment]
I am thinking that `#` is far to generic to identify as a tag delimiter apart from normal text content.  To be safe I will likely hide Velocity support behind an option so that I can mandate these conventions without regression fear.

**Comment by rediris** [comment]
Sure, makes sense.

**Comment by prettydiff** [comment]
Notes:

Tags delimited as follows:

* #word ... end of line - logic or command
* $word ... end of line - variable
* $!word ... end of line - silent variable
* ${word} ... end of line - formal variable
* $!{word} ... end of line - formal silent variable
* #* ... *# - block comment
* ## ... end of line - single line comment
* #[[ ... ]]# - block comment (cdata expression)
* #(space) will be treated as regular unparsed text content

* #if and #foreach will be template_start types
* #end will be template_end type
* #else and #elseif will be template_else types

**Comment by prettydiff** [comment]
Support is added to branch 2.1.0 and will be published to master soon.
