### ISSUE TITLE
Error: Cannot find module 'prettydiff'

### ISSUE THREAD

**Issue by fdubost** [prettydiff/prettydiff#288]
Hello,
Since v1.16.30, I have this error (I use sprity v1.0.8). With v1.16.29, it passes.
Thank you for your help :relaxed:

**Comment by prettydiff** [comment]
Try again.  I just bumped to version v1.16.31 and verified its health.  I got burned by https://github.com/npm/npm/issues/5082 second time this week.

I am going to write a new NPM module to check for this and automatically republish in a loop until verified the problem is resolved.

**Comment by fdubost** [comment]
It passes with v1.16.31 :+1: 
Thanks.

**Comment by prettydiff** [comment]
Here is my attempt to an automated mitigation: https://github.com/prettydiff/5082

**Warning!! I have not tested this in production yet**

**Comment by prettydiff** [comment]
Package 5082 is tested in production and added to Pretty Diff.  Hopefully this problem is put to bed.
