### ISSUE TITLE
`readmethod:file` makes a directory on CLI

### ISSUE THREAD

**Issue by rosshinkley** [prettydiff/prettydiff#290]
This might be a painfully newbie question, so apologies in advance.  I'm using v1.16.37, for what it's worth.

Consider:
```bash
prettydiff source:somefile.html output:output.html mode:beautify readmethod:file
```
Based on the documentation for `readmethod`:
```
* file         - reads a file and outputs to a file
               - file requires option 'output'
```

... and the documentation for `output`:
```
* output       - string  - The path of the directory, if readmethod is value
                           'directory', or path and name of the file to write
                           the output.
```

... I would expect the beautified version of `somefile.html` to be output to `output.html`.  Instead, PD creates a directory called `output.html` and puts the beautified version + report in the subdirectory.  Is that the correct behavior?  What am I missing?

**Comment by prettydiff** [comment]
Yeah, that is absolutely broken.  You interpreted the documentation correctly.  I am looking into this.

**Comment by prettydiff** [comment]
Would you also be able to provide the operating system and version of Node?

**Comment by rosshinkley** [comment]
Sure!  This happened on an Ubuntu 14.04 box running Node v4.2.3.

**Comment by prettydiff** [comment]
Resolution in the 2.0.1 branch and will launch soon. https://github.com/prettydiff/prettydiff/tree/2.0.1

**Comment by prettydiff** [comment]
This is done and in the 2.0.1 branch.  The behavior, documentation, and unit tests are all updated.  If in `readmethod:file`  then the `output` option will point to a file location instead of a directory location.

**Comment by prettydiff** [comment]
Resolved and merged to master.

**Comment by rosshinkley** [comment]
Thank you!
