### ISSUE TITLE
Electron

### ISSUE THREAD

**Issue by trusktr** [prettydiff/prettydiff#298]
Publishing with [Electron](http://electron.atom.io/) might be nice.

Most of your code can remain the same, except you can use Node.js API to access the file from the user's system directly.

You can do a check. If not in electron, then do as you do now, if in Electron, use the Node.js API (perhaps let the user specify a file path or something). You could even add a file explorer for choosing the file.

**Comment by prettydiff** [comment]
Awesome, I will look into this further very soon.  At the moment my first priority is to ship v2.0.0.  It sounds really exciting to able to run this in Electron directly as a native desktop app.

**Comment by trusktr** [comment]
Yeah! Plus, since Electron is cross platform you can package it for all the
OSes. :)

On Friday, April 15, 2016, Austin Cheney <notifications@github.com> wrote:

> Awesome, I will look into this further very soon. At the moment my first
> priority is to ship v2.0.0. It sounds really exciting to able to run this
> in Electron directly as a native desktop app.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/prettydiff/prettydiff/issues/298#issuecomment-210622347>
>


-- 
/#!/JoePea

**Comment by prettydiff** [comment]
I will generate a download page for this that will contain various download points including an Electron binary and zlib package.

Tasks:

* I will need to search for or write a zlib utility written for Node's zlib library and without NPM dependency.
* I will need to write a distribution script to run the unit tests, automate publication to supported distribution points, create the binaries, post to github, and publish an RSS beacon of the new version.

**Comment by prettydiff** [comment]
I will defer this effort to the Unibeautify project: https://github.com/Unibeautify/
