### ISSUE TITLE
JSX Format changes case!

### ISSUE THREAD

**Issue by rkhayat** [prettydiff/prettydiff#305]
Love the tool, but formatting JSX/React code turns camelCase => noncamelcase

**Comment by prettydiff** [comment]
Would you mind providing me a brief code sample so that I can reproduce the problem?  If I cannot demonstrate the problem I will have no idea if I am actually solving it.

**Comment by prettydiff** [comment]
I am going to close this issue for the moment.  Please reopen the issue if you encounter the problem again.
