### ISSUE TITLE
Add option to keep indentation in LESS/SCSS/CSS

### ISSUE THREAD

**Issue by poacher2k** [prettydiff/prettydiff#306]
First off, thanks for all the great work!

Nesting selectors can be awesome, but it's not always necessary. Readable code on the other hand, is always a good thing.

Instead of writing the following:
```
.tabs {
    ...
    .tab {
        ...
    }
}
```
one could write
```
.tabs {
    ...
}

    .tab {
        ...
    }
```
which has a comparably good visual hierarchy and nicer looking selectors.

The latter code example loses its indentation when running prettydiff, though. 

Would it be possible to have an option that allowed keeping the indentation?

**Comment by prettydiff** [comment]
I am currently away at a military school and will return home this weekend.  I will begin examination of this idea at that time.

**Comment by prettydiff** [comment]
I have thinking about this issue and have chosen to not complete this work.  This one is will be a huge amount of work.  I would have to store white space definitions for each parsed token in the lexer.  I am currently only summarizing white space at this point to know if empty lines should be preserved.

Thank you for the suggestion!

**Comment by poacher2k** [comment]
Thank you for considering it, and keep up the great work :-)
