### ISSUE TITLE
beautify css adds bad space in less-css syntax: &:extend(.class)

### ISSUE THREAD

**Issue by guymguym** [prettydiff/prettydiff#31]
I saw it while using Atom with the Atom Beautify package, and then tested also in prettydiff.com.

Here is the input:

```
.animal {
    color: red;
}
.dog {
    &:extend(.animal);
    &:hover {
        color: green;
    }
}
```

And prettydiff generates a space in "&: extend(..." which makes the output an illegal less-css:

```
.animal {
    color: red;
}
.dog {
    &: extend(.animal);
    &:hover {
        color: green;
    }
}
```

Can I help to make a quick fix?
Thanks!

**Comment by Glavin001** [comment]
Thanks, works great!
