### ISSUE TITLE
Using JS ES6 "export defaults" syntax with styleguide causes extra semi-colon to be erroneously added

### ISSUE THREAD

**Issue by liamcurry** [prettydiff/prettydiff#317]
It seems that using the Javascript ES6 `export defaults {}` syntax along with the `styleguide` option is causing an extra semi-colon to be added within the object.

For example, using `styleguide: 'google'` will format these examples...

```js
export default {
    foo: 'bar'
}
```
```js
export default {
    foo: 'bar',
}
```

...into:

```js
export default {
    foo: 'bar';
}
```

**Comment by prettydiff** [comment]
Fixed in branch 2.0.5.
