### ISSUE TITLE
Autocorrect for tags ending with ">>"

### ISSUE THREAD

**Issue by clockwork82** [prettydiff/prettydiff#318]
Hi there, when I try beautifying this file it seems to break when I have 2 lots of jsx in the file

Cheers

```
import React from 'react';

class Details extends React.Component {

	render() {
		let description;

		if (this.props.description) {
			description = (
				<div>
					<h3 className="small-title grey-5">
						About this service
					</h3>
					<p>
						{this.props.description}
					</p>
				</div>
			);
		}

		return (
			<div className="details-component">
				<h3 className="small-title grey-5">Location</h3>
				<p className="gamma">{this.props.address}</p>
				{description}
				<h3 className="small-title grey-5">Opening Hours</h3>
				<div className="opening-hours">
					<p className="indicator-wrapper">
						<span className="indicator open">Currently Open</span>
					</p>
					<div className="time-wrapper">
						<h4 className="small-title">Weekdays:</h4>
						<ul className="mon-fri">
							{

								this.props.hours.map((item) => {

									item = item.split(':');

									return (
										<li>
											<span className="day">{item[0]}</span>
											<span className="time">>{item[0]}</span>
										</li>
									);

								})

							}
						</ul>
					</div>

				</div>
			</div>
		);
	}
}

Details.propTypes = {
	address: React.PropTypes.string,
	description: React.PropTypes.bool,
	hours: React.PropTypes.object
};

Details.defaultProps = {
	address: '',
	description: false
};

export default Details;

```

**Comment by prettydiff** [comment]
It appears there is a typo in the code sample: `<span className="time">>{item[0]}</span>` appears to have two closing delimiters on the opening span tag.  Once I remove the second `>` everything appears correct.

Perhaps there are additional concerns that I am not seeing.  Just let me know where to look for any additional concerns.

**Comment by clockwork82** [comment]
Fair call, I guess I could argue that although it did have an extra > it shouldn't break the page but Its really a judgment call, which I'll leave to you. Thanks for taking a look regardless.

Cheers

**Comment by prettydiff** [comment]
I might be able to correct for this.  I will need to run some tests to look for regression and interference with other template schemes.

**Comment by prettydiff** [comment]
This is done in the 2.0.5 branch and will merge to the master branch soon.  This auto-correction is hidden behind the *correct* option.  It is applied to both the front and end of a tag, but only if the delimiter on one end is a single angle brace.  This correction could be problematic in the rare case of a template tag using `<<` and `>>` delimiters and misses one of the angle brace characters as that tag will now be auto-corrected to regular XML syntax.
