### ISSUE TITLE
Support for classic ASP files

### ISSUE THREAD

**Issue by lenilsondc** [prettydiff/prettydiff#321]
Would like to add support for ASP pages, mainly for code beautification.

ASP uses `<% ...... %>` like engine syntax, similar to php, jsp and other language engines, and the code between the ebeded code usually is VBScript. However, like in php, it may have html, css and js outside the asp markup like the example below.

````asp
<%@LANGUAGE="VBSCRIPT" CODEPAGE="1252"%>
<!--#include file="../libs/Db.asp" -->
<!--#include file="../libs/i18n.asp" -->
<%
	Dim something, somethingElse

	something = "something"
	somethingElse = "somethingElse"

	Function Foo()
		Foo = "Bar"
	End Function
%>
<!DOCTYPE html>
<html>
<head>
	<title>ASP Page 1</title>
</head>
<body>
	<h1><%= something %></h1>
	<p><% Response.Write(somethingElse) %></p>
	<p><%= Foo() %></p>
</body>
</html>
````

Thus, assuming that Prettydiff has html, css and js already implemented, it would be much more easy to add asp support.
Is it possible for prettydiff?

**Comment by prettydiff** [comment]
This should be a really simple enhancement and I am surprised this isn't currently working.  I will be working on this today.

**Comment by prettydiff** [comment]
This is not an enhancement as ASP support is already available.  This code sample proved three defects:

* `<!--#` were not being closed properly
* White space is in ASP tags `<%` was not being preserved
* Template else tags were not pushing to the `presv` array thereby breaking certain white space formatting considerations.

All these issues are fixed in branch 2.1.0.

**Comment by lenilsondc** [comment]
Awesome!
Makes sense.
Is it going to be available on atom-beautify package too?

**Comment by prettydiff** [comment]
Not yet. Atom Beautify is using version 1.16.37 until I can come up with an automated distribution scheme

**Comment by lenilsondc** [comment]
Ok!
I think I can deal with a quick fix using the branch 2.1.0 until there. And also, if necessary, I am able to add local support for HTML (ASP) to [atom-beatutify](https://github.com/prettydiff/atom-beautify) using this branch.

Anyway, thanks a lot Sir!
Let me know if I can help with anything else, otherwise, I guess this issue might be marked as closed.

:{D

**Comment by prettydiff** [comment]
What you can do is over write the file prettydiff/lib/markuppretty.js inside your Atom install location with the one from github branch 2.1.0 and you can instantly receive all the bug fixes.

**Comment by lenilsondc** [comment]
I did it but anyway I have to add ASP and HTML (ASP) grammar support to atom-beautify, haven't I?
In that case, I have to add asp language for the package and change prettydiff beautifier to support asp as well.

Am I missing something?

By the way I have to specify a language for the argument, should I use an especific language name (for example, `{lang: "html_asp"}`) or using `{lang: "auto"` is ok?

**Comment by prettydiff** [comment]
Nope, just beautify as HTML.  The ASP support is automatic.  Just ensure that in the Atom Beautify settings Pretty Diff is the beautifier for HTML.

**Comment by lenilsondc** [comment]
All right, very nice, it worked like a charm!

BUT :{D
I have to report that I found another issue with ASP.

As you may know, vbscript comment style consists on a single quotation mark char (`'`) that make the rest of the line a comment.
Somehow the VBScript empty comments are preventing the prettydiff beautifying the rest of the html properly. But other normal comments don't create this behavior, just when it's empty.

For example, if I add an empty comment to the previous example it won't be able to beautify anymore.

````asp
<%@LANGUAGE="VBSCRIPT" CODEPAGE="1252"%>
<!--#include file="../libs/Db.asp" -->
<!--#include file="../libs/i18n.asp" -->
<%
    '
    'non-empty comment, previous line is empty comment and prevent all the prettydiff's awesome beautify
    Dim something, somethingElse

    something = "something"
    somethingElse = "somethingElse"

    Function Foo()
        Foo = "Bar"
    End Function
%>
<!DOCTYPE html>
<html>
<head>
    <title>ASP Page 1</title>
</head>
<body>
    <h1><%= something %></h1>
    <p><% Response.Write(somethingElse) %></p>
    <p><%= Foo() %></p>
</body>
</html>
````

**Comment by lenilsondc** [comment]
I tested some cases more, and I think I figured out what is happening.

Quoted mark is being considered string opening and the next quoted mark is considered the string closing.
Because when I tested a code with two comments it was beautified correctly, but with one, three, five, etc. it is not.
I guess with odd numers of comments found it will not beautify becaus always will miss a string closing char.

**Comment by prettydiff** [comment]
You are completely correct.  I just pushed a resolution.  Quotes are now ignored inside ASP tags.

**Comment by lenilsondc** [comment]
Awesome, it worked.
I've made some tests and the comments doesn't look to be an issue anymore.

Original
````asp
<%@LANGUAGE="VBSCRIPT" CODEPAGE="1252"%>
<!--#include file="../libs/Db.asp" -->
<!--#include file="../libs/i18n.asp" -->
<%
    '
    'non-empty comment, previous line is empty comment and prevent
    'all the prettydiff's awesome beautify
    Dim something, somethingElse

    something = "something"
    somethingElse = "somethingElse"

    Function Foo()
        Foo = "Bar"
    End Function
%>
<!DOCTYPE html>
<html>
<head>
<title>ASP Page 1</title>
</head>
<body>
<h1><%= something %></h1>
<p><% Response.Write(somethingElse) %></p>
<p><%= Foo() %></p>
<%
Dim Foo
Foo = "Bar"

If something = "something" Then
Foo = "Foo Bar"
End If
%>
</body>
</html>
````

Beautified
````asp
<%@LANGUAGE="VBSCRIPT" CODEPAGE="1252"%>
<!--#include file="../libs/Db.asp" -->
<!--#include file="../libs/i18n.asp" -->
<%
    '
    'non-empty comment, previous line is empty comment and prevent
    'all the prettydiff's awesome beautify
    Dim something, somethingElse

    something = "something"
    somethingElse = "somethingElse"

    Function Foo()
        Foo = "Bar"
    End Function
%>
<!DOCTYPE html>
<html>
    <head>
        <title>ASP Page 1</title>
    </head>
    <body>
        <h1><%= something %></h1>
        <p><% Response.Write(somethingElse) %></p>
        <p><%= Foo() %></p>
        <%
Dim Foo
Foo = "Bar"

If something = "something" Then
Foo = "Foo Bar"
End If
%>
    </body>
</html>
````

**Comment by prettydiff** [comment]
Thank you so very much for your help and support with this!  It is because of people like you that I continue to maintain this software.

**Comment by lenilsondc** [comment]
Well I'm glad to help you somehow.

And also, I have to say thank you so much for your support and for maintaining this software. Prettydiff is awesome, seriously, nice work.

From now, I'm going to implement a vbscript beautifyer to beautify inside the asp tags template.
Do you have any sugestion for which approach I should use to integrate my beautifier with Prettydiff? Like an adapter or a driver maybe?
You may have a better ideia for me to take as a starting point.

**Comment by prettydiff** [comment]
I am not sure.  I will have to think about that.  In the meantime I do have a parse mode which you can use to get the ASP tags directly and automatically from the rest of the code.  This may or may not be helpful.

**Comment by lenilsondc** [comment]
Similar to javascript and css I guess.
Using an external beautifier should be a good idea, like `extlib('vbscript')` or something.
In that case is just necessary choose the proper place to call the external beautifyer being sure that it wouldn't affect other languages, for example, ruby and jsp use the same markup syntax that ASP.

I think this is a good approach to extend prettydiff properly.

**Comment by prettydiff** [comment]
I opened a new issue for that: #323
