### ISSUE TITLE
Ignoring specified tags from markup for diff mode

### ISSUE THREAD

**Issue by schmfr** [prettydiff/prettydiff#322]
I diff xml files that contain elements (e.g. a timestamp) that should be ignored in the comparing process.
Unfortunately, the data-prettydiff-ignore attribute does not work in diff mode. Would be great if you could implement this feature.

Frank

**Comment by prettydiff** [comment]
Work is complete.  The attribute `data-prettydiff-ignore="true"` is retained for clarity.  When in `diff` mode all other attributes and child elements are completely suppressed.

**Comment by schmfr** [comment]
Wow, very quickly. Thanks a lot.
