### ISSUE TITLE
Brace Style options?

### ISSUE THREAD

**Issue by PolGuixe** [prettydiff/prettydiff#326]
It would be nice to have Brace-Style similar to JSBeuatify.

**Comment by prettydiff** [comment]
Pretty Diff beautifies braces using multiple options for greater customization:

* [braceline](http://prettydiff.com/documentation.xhtml#braceline)
* [bracepadding](http://prettydiff.com/documentation.xhtml#bracepadding)
* [formatObject](http://prettydiff.com/documentation.xhtml#formatObject)
* [neverflatten](http://prettydiff.com/documentation.xhtml#neverflatten)

**Comment by PolGuixe** [comment]
Could it be set-up like: 

```
//.prettydiffrc
{
"neverflatten": true, 
}
```

I'am missing a `.prettydiffrc` example.

**Comment by prettydiff** [comment]
The .prettydiffrc file can take a JSON exactly like your example or you can take the default code in the provided .prettydiffrc file and simply drop options and login into that blank area in the middle of the file.  I am fairly certain that Atom Beautify does not make use of the .prettydiffrc file though.

**Comment by PolGuixe** [comment]
So is there a way to set-up those options in Atom Beautify?

**Comment by prettydiff** [comment]
I will create a new option to bundle these other options together in a way that more closely matches the behaviors of JSBeautify.

**Comment by prettydiff** [comment]
@PolGuixe Would you mind providing a brief description of what the JSBeautify options for the `brace-style` option do?

I see the option has these 4 values:

* collapse-preserve-inline
* collapse
* expand
* end-expand
* none

I am looking this up now and the documentation does now specific what these options do.  I am having trouble producing unique results using http://jsbeautifier.org/

**Comment by prettydiff** [comment]
The online tool for JSBeautifier was not apply the brace style changes very effective, but after reading over past issues and documentation online this is what I have gathered:

* collapse-preserve-inline - This will put the opening brace on the same line as the preceding token and inline small single dimensional objects
* collapse - the default value will put the opening curly brace on the same line as the preceding token
* expand - will move the curly brace onto the next line where appropriate
* end-expand - will move the token following the end curly brace, as appropriate, onto a new line, such as `else` keyword
* none - Maintains newlines preceding or following braces as suggested by the sample code

I would like accomplish this by setting the currently existing Pretty Diff options for these values:

* collapse-preserve-inline
  - braceline:false
  - bracepadding:true
  - braces:"knr"
  - formatObject: "inline"
  - neverflatten: false
* collapse
  - braceline: false
  - bracepadding: false
  - braces:"knr"
  - formatObject: "indent"
  - neverflatten: true
* expand
  - braceline: false
  - bracepadding: false
  - braces: "allman"
  - formatObject:"indent"
  - neverflatten:true
* end-expand/none - I would likely not provided this support

**Comment by prettydiff** [comment]
The option is added to branch 2.1.1.  The default value will be `none`, which just ignores this option.
