### ISSUE TITLE
Formatting of SCSS Maps

### ISSUE THREAD

**Issue by thejamespower** [prettydiff/prettydiff#338]
Is there a way to get PrettyDiff to play nicer with SCSS maps?

Would expect the format of a map to look something like this:
```
$grid: (
  'max-width': (40 * $u),
  'columns': 12,
  'gutter': (.5 * $u)
);
```
Yet PrettyDiff places it all on one line with strange spacing:
```
$grid: ( 'max-width': (40 * $u), 'columns': 12, 'gutter': (.5 * $u) );
```

If I'm missing something, any help would be appreciated 😅

**Comment by thejamespower** [comment]
Also extra problematic where comments are involved:

Valid SCSS:
```
$opacity: (
  'light': .8, // opacity used with lighter colors 
  'dark' :.4, // opacity used with darker colors 
   // ... etc.
);
```
Becomes invalid:
```
opacity: ( 'light': .8, // opacity used with lighter colors 'dark' :.4, // opacity used with darker colors // ... etc. );
```

**Comment by prettydiff** [comment]
Yeah, I am not currently parsing this properly at all.  I am extending the parser right now to extend support for various structures (so far just blocks and maps).  I will have something for you to demo soon.

**Comment by prettydiff** [comment]
I just added support in the 2.1.3 branch.  Check it out and let me know what you think.  If you are new to git or have trouble accessing this just let me know and I can walk you through it.

**Comment by thejamespower** [comment]
Awesome! Speedy work. I'll try and break it and get back to you.
