### ISSUE TITLE
objsort adds newlines? question

### ISSUE THREAD

**Issue by laduke** [prettydiff/prettydiff#345]
Hi,
I want to use objsort for css. It's a cool feature. But it adds new lines in some places (between groups of similar css parameters) which makes style-guide/linter mad. Is there an option to turn off the new lines?

**Comment by prettydiff** [comment]
Since you already closed the question you probably found the option you were looking for, but if not check out these:

* http://prettydiff.com/documentation.xhtml#preserve
* http://prettydiff.com/documentation.xhtml#cssinsertlines

Out of curiosity how did you hear about Pretty Diff?

**Comment by laduke** [comment]
I was using js-beautify in atom. Because of the style guide I'm beholden to and can't modify I need an option to not put spaces between commas in CSS like: `rgb(10,10,10.5)`, but js-beautify doesn't have an option for that. Anyways, I saw prettydiff mentioned in the atom-beautify settings. 

I was flipping around between this, js-beautify, and csscomb and atom was acting weird and I was getting mixed up. 
Thanks for asking.
