### ISSUE TITLE
Atom.io extension

### ISSUE THREAD

**Issue by prettydiff** [prettydiff/prettydiff#36]
Add an extension to Atom.io so as to provide full integration of Prettydiff into the IDE with support for PrettyDiff options.

https://atom.io/

**Comment by Glavin001** [comment]
I intend to fully support Prettydiff's beautification with https://github.com/Glavin001/atom-beautify

**Comment by prettydiff** [comment]
Wow! I am truly blessed for your assistance. Please let me know of any questions you encounter.

**Comment by Glavin001** [comment]
Thanks again for providing such an incredible beautifier with `prettydiff`! Please let *me* know if there is anything I can do for *you*! :smiley:

**Comment by prettydiff** [comment]
Do I have you to thank for the recent burst in NPM package traffic?  

http://npm-stat.com/charts.html?package=prettydiff

If so thank you very much. I guess I should close this issue.

**Comment by Glavin001** [comment]
Great teamwork. Glad I could help with Atom Beautify. Pretty Diff is awesome! :smiley:

**Comment by prettydiff** [comment]
Thanks so much!  I need to update the readme.md file to provide a link to atom-beautify.
