### ISSUE TITLE
your demo page doesn't work when comparing

### ISSUE THREAD

**Issue by rpanjwani** [prettydiff/prettydiff#367]
markuppretty.js:95 Uncaught TypeError: Cannot read property 'wrap' of undefined

**Comment by prettydiff** [comment]
Thanks for letting me know.  Do you have a code sample that could help me reproduce this defect?

**Comment by rpanjwani** [comment]
ahhh hey sorry I can't give you the sample because it's company data. But it was a very long xml template with 43k characters.  My browser is Chrome 52.0.2743.116 m on Windows 10

**Comment by prettydiff** [comment]
Thanks, but I am having trouble reproducing.  In my unit tests I have a HTML code sample that is half a meg.  I tested it in the same version of Chrome on OSX and it beautified correctly in 2.1 seconds.  I will try on Windows in a bit.

**Comment by prettydiff** [comment]
Working this from https://github.com/prettydiff/prettydiff/issues/371
