### ISSUE TITLE
React/JSX features

### ISSUE THREAD

**Issue by klaaz0r** [prettydiff/prettydiff#368]
I would really love to see more features for use with JSX /React 

Currently it looks like this
```
import {Menu} from 'stardust'

const Navbar = React.createClass({
  render: function () {
    const {activeItem} = this.state
    return (
      <Menu>
        <Menu.Item name="editor" active={activeItem === "editor"} onClick={this.handleItemClick} as={Link} to="/stage">
          Editor
        </Menu.Item>
      </Menu>
    )
  },
})
```

But something like this would be great and more clean
```
import { Menu } from 'stardust'

const Navbar = React.createClass({
  render: function () {
    const { activeItem } = this.state
    return (
      <Menu>
        <Menu.Item 
             name="editor" 
             active={activeItem === "editor"} 
             onClick={this.handleItemClick} 
             as={Link} 
             to="/stage">
          Editor
        </Menu.Item>
      </Menu>
    )
  },
})
```

Maybe I missed some thing and object destructuring / wrap html attributes is possible to configure, and if there are no plans to add these features in the near future hopefully someone can point me to the right directions to create a PR

**Comment by prettydiff** [comment]
You want these options:

* `force_attribute: true`
* `bracepadding: true`

I am currently working on an enhancement for bracepadding in issue #363 and I will publish this update very soon.
