### ISSUE TITLE
ignoring whitespace when comparing xml produces an error

### ISSUE THREAD

**Issue by rpanjwani** [prettydiff/prettydiff#371]
was trying to compare two xml templates and it works fine if I don't ignore whitespace. Following is the screenshot of the error:
![image](https://cloud.githubusercontent.com/assets/4108676/18758820/7e6f90d8-80ae-11e6-989a-b8c67d6975e3.png)

Amendment: Seems like it only happens if I have also selected "compare inline". Side-by-side works fine.

**Comment by prettydiff** [comment]
Thanks that is certainly helpful information, but I still cannot reproduce.  The error is absolutely related to the diff algorithm's interpretation of the code samples, so I cannot reproduce without some similar code.  I can suppress the errors based upon your screenshot, but I am scared the problem will still be there causing unexpected output.

There is an option, `content`,  on the tool to convert all markup text to "text".  If that is enough to suppress the confidential parts of the code and you can continue to reproduce the problem then you might have some code to share.

Before sharing any code with me also verify that the tag names and attribute names aren't confidential.  You might also need to remove any code comments as a just in case before exposing the code.  Thanks for informing me of this.
