### ISSUE TITLE
Twig issue. Part of twig code disappears after beautify.

### ISSUE THREAD

**Issue by johanneslamers** [prettydiff/prettydiff#373]
Hi

I'm seeing the following issue. Try beautifying this code: 
http://prettydiff.com/ignore/testlocation/index.xhtml?m=beautify

```` 
{% include [
    "item/" ~ entry.section.handle ~ "/" ~ entry.type,
    "item/" ~ entry.section.handle ~ "/default",
    "item/default"
] %}

% set seo = {
    seoTitle: seo.seoTitle,
    seoDescription: seo.seoDescription,
    seoKeywords: seo.seoKeywords,
    seoImage: seo.seoImage,
    canonicalUrl: seo.canonicalUrl,
    twitter: {
        card: seo.twitter.card,
        site: seo.twitter.site,
        creator: seo.twitter.creator,
        title: seo.seoTitle,
        description: seo.seoDescription,
        image: seo.seoImage
    },
    og: {
        type: seo.og.type,
        locale: seo.og.locale,
        url: seo.canonicalUrl,
        title: seo.seoTitle,
        description: seo.seoDescription,
        image: seo.seoImage,
        site_name: seo.og.site_name,
        see_also: seo.og.see_also
    }
} %}

````

The second part of the code (set seo) disappears. Also would love to have the first part beautified like the input.

**Comment by prettydiff** [comment]
The code sample appears broken.  `% set seo = {` should probably be `{% set seo = {`, as in the first curly brace is missing.  This partially solves the problem of the second missing code element.

Remaining concerns:

1. The contents inside the Twig tags should be beautified as JavaScript, which they aren't, at least for the first code element.
2. Even when the opening curly brace is absent the remaining code should not be excluded.  At a minimum it should be included as text content even if broken.

I am continuing to examine this.

**Comment by prettydiff** [comment]
Beautification is occurring properly, but the output is not the desired output.  Instead of beautifying as an array the code is beautifying as a notation, like certain types of SGML structures or structures that may occur in Java or C#.  I will have to think about the most simple way of solving this problem that does not require support for additional options, regression, or architecture bloat.

**Comment by prettydiff** [comment]
Fixed in the branch and I will merge to master soon!
