### ISSUE TITLE
Prettydiff : Beautify diff output from command line in linux

### ISSUE THREAD

**Issue by kernelfreak** [prettydiff/prettydiff#378]
Hello friends,

I have installed the prettydiff node module on our debian server and currently calling it via command line as diff file1.txt file2.txt > output.txt. As I see the difference between two files is shown in a more technical way, but I am looking how I can get a better output or beautify it for displaying in front-end. 

The 2nd thing I am looking for is, can the diff command above compare html files as well, and show the output not as text which has changed but the effective html which was modified. Thank you.

**Comment by prettydiff** [comment]
Do you mean rendering the HTML in a browser and drawing outlines over the changed areas of the page?

**Comment by kernelfreak** [comment]
Once I have the html I can render it in browser, but yes drawing outlines. Thank you.

**Comment by prettydiff** [comment]
This has been requested a few times in the past, so it is definitely a valued and demanded request.  At this time Pretty Diff only works with code and has no graphical rendering component.  What I wouldn't give to have some funding to work on this stuff full time.

**Comment by prettydiff** [comment]
I will tackle this in the near future as I now have a technical plan.  I will be logging notes to issue #387

**Comment by kernelfreak** [comment]
This feature is found in daisyDiff, perhaps you can pull some code from it. Thank you.

**Comment by prettydiff** [comment]
Rolling up output format issues into #454
