### ISSUE TITLE
Atom plugin?

### ISSUE THREAD

**Issue by rr20eid10** [prettydiff/prettydiff#382]
Hi,

Is this a plugin available in Atom?  I'm new to Atom and atom-beautify doesn't work for JSX code and I'd like to use prettyDiff  in Atom editor if possible.

Thanks.

**Comment by prettydiff** [comment]
Sorry, the Atom Beautify is the supported plugin to get Pretty Diff into Atom.  I can see you recently commented on an issue in Atom Beautify.  I recommend opening a new issue for the specific problem you are encountering and include the debug.md file that Atom Beautify generates.
