### ISSUE TITLE
Anonymous function parameters on single line

### ISSUE THREAD

**Issue by alizahid** [prettydiff/prettydiff#383]
My code

	const parser = parse({
		delimiter: ','
	}, (err, data) => {
		console.log(data)
	})

My Pretty Diff configuration

	mode: 'beautify',
	lang: 'jsx',
	brace_style: 'collapse',
	objsort: 'none',
	endcomma: 'multiline',
	methodchain: 'chain',
	vertical: 'none',
	formatArray: 'indent',
	formatObject: 'indent',
	functionname: true,
	neverflatten: true

It's turning my anonymous function into

	const parser = parse({
		delimiter: ','
	}, (err,
	data) => {
		console.log(data)
	})

With `neverflatten` set to `false`, it becomes (without the anonymous function)

	const parser = parse({delimiter: ','})

Both are undesired. I want my object, even with one key (I've noticed it only collapses if there's less than 4 keys in the object) to be on multiple lines. I also want the anonymous function parameters to be on the same line.

Is my configuration busted?

**Comment by prettydiff** [comment]
Out of curiosity what version of Pretty Diff are you using?

**Comment by alizahid** [comment]
Ah, I see what you mean. I'm using 99.0.1 from [NPM](https://www.npmjs.com/package/prettydiff). Should I install from this repo instead?

**Comment by alizahid** [comment]
Now I'm at 2.1.14, and I see this weird bug. This code

	export default {
		deactivate() {
			this.subscriptions.dispose()
		}
	}

becomes

	export default {
		deactivate() {
			this.subscriptions.dispose()x;,
		},
	}

1. I think it's taking the body for `deactivate` as an object because there's no `function` keyword.
2. That `x;` has to be a bug, right? I saw that on the [website](http://prettydiff.com/), too.
3. Anonymous function parameters are still getting split onto multiple lines

My Pretty Diff call

	let output = prettydiff({
		source: text,
		mode: 'beautify',
		lang: 'jsx',
		brace_style: 'collapse',
		insize: indent_size,
		inchar: indent_char,
		quoteconvert: 'single',
		objsort: sort ? 'all' : 'none',
		wrap: 0,
		endcomma: 'multiline',
		methodchain: 'chain',
		vertical: 'none',
		ternaryline: true,
		formatArray: 'indent',
		formatObject: 'indent',
		neverflatten: true,
	})
