### ISSUE TITLE
Twig issue - "block" function is treated like a block tag

### ISSUE THREAD

**Issue by Notmarrco** [prettydiff/prettydiff#384]
Hi,

Twig has a block function (http://twig.sensiolabs.org/doc/functions/block.html) that seems to be beautified like a block tag , so there is an added indentation on the line after.

Desired output : 
```
{% block body %}
    {{ block('widget') }}
    {{ parent() }}
{% endblock %}
```
beautified output (tried with http://prettydiff.com/ignore/testlocation/index.xhtml?m=beautify ) : 
```
{% block body %}
    {{ block('widget') }}
        {{ parent() }}
    {% endblock %}
```

thanks

**Comment by prettydiff** [comment]
Thanks, I will get to this very soon.

**Comment by prettydiff** [comment]
It seems `{{ block }}` is a start tag in Go Lang Templates and Elm Templates, but fortunately those languages don't have `{%` syntax.  My fix just tests the input for the absence of `{%` style tags.  If there is a Twig file that does not have `{%` tags this defect may still be present.  Please let me know if this is likely to be a problem.

**Comment by Notmarrco** [comment]
Thx

No it won't be a problem, since the file with ```{{ block(xxx) }}``` syntax must already define a ```{% block xxx %}``` either directly in the template or in an inherited template (but the syntax to inherit contains ```{%```).

So to me it's a fix ! 👍
