### ISSUE TITLE
ERB <% conditionals %> not indenting correctly.

### ISSUE THREAD

**Issue by unmultimedio** [prettydiff/prettydiff#390]
This piece of code is not indenting correctly:

```
<ul>
<% if true %>
<li>qwerty</li>
<li>qwerty</li>
<% else %>
<li>qwerty</li>
<li>qwerty</li>
<% end %>
<li>qwerty</li>
</ul>
```

I'd hope to be indented like:

```
<ul>
  <% if true %>
    <li>qwerty</li>
    <li>qwerty</li>
  <% else %>
    <li>qwerty</li>
    <li>qwerty</li>
  <% end %>
  <li>qwerty</li>
</ul>
```

But this is how is doing it:

```
<ul>
  <% if true %>
  <li>qwerty</li>
  <li>qwerty</li>
<% else %>
  <li>qwerty</li>
  <li>qwerty</li>
  <% end %>
  <li>qwerty</li>
</ul>
```

![prettydiff](https://cloud.githubusercontent.com/assets/4431392/20571035/f0fc4416-b173-11e6-8c82-c0e4953fd296.gif)

**Comment by prettydiff** [comment]
This appears to be working correctly in the latest published version at http://prettydiff.com.

Are you using Pretty Diff from NPM or Atom Beautify?

**Comment by unmultimedio** [comment]
I'm using Atom Beautify. How do I update it to the last version?

**Comment by prettydiff** [comment]
Unfortunately, you cannot just yet.  I stepped away from NPM around March/April.  I am working on an alternate distribution scheme right now at https://github.com/prettydiff/biddle and some additional information about how I am using Pretty Diff with it is at https://github.com/prettydiff/prettydiff/issues/291#issuecomment-259951141

The software works right now, but before I certify the software is ready for production usage (aside from Pretty Diff) I need to do some more tests.  My current roadmap is to get the next version of Pretty Diff released and published with biddle and then use the availability of multiple versions of Pretty Diff in production to perform some additional biddle verifications.

I am trying to get this stuff out there as fast as possible.

**Comment by NaldoColella** [comment]
So we still cant have this bug corrected?

**Comment by prettydiff** [comment]
I am working on these issues now:

* https://github.com/prettydiff/biddle/issues/34
* https://github.com/prettydiff/prettydiff/issues/409

Upon completion biddle will be ready for integration.  Once biddle is integrated the latest version of Pretty Diff will be included in Atom Beautify.

**Comment by brandoncc** [comment]
Based on the fact that I still have this issue, I'm guessing we still don't get the fix for this @prettydiff?

**Comment by prettydiff** [comment]
@brandoncc When I beautify the sample code at the top of this issue it seems to beautify correctly.  Could you provide me a code sample that is failing for you?
