### ISSUE TITLE
Got wrong diff output with diffcli=true when comparing two html

### ISSUE THREAD

**Issue by linkeo** [prettydiff/prettydiff#400]
Hi, I want to compare two html, and manually render it into react.js. So I chose to use option `diffcli:true`.
Then I found then result is not corrent.

How I used:

```js
// In order to locate the fault, I tried to beautify htmls before diff,
// and set language to plain text in diff options.
const prettyfrom = (prettydiff({source: originHtml, mode: 'beautify'})[0]);
const prettyto = (prettydiff({source: changedHtml, mode: 'beautify'})[0]);
const diff = prettydiff({
  source: (prettyfrom || ''),
  diff: (prettyto || ''),
  diffcli: true,
  lang: 'text'
});
```

Unexpected content in result (Only show a short one here):

```html
    <!-- origin.html line 729-732 -->
    <a href="?p=8">&laquo;</a>
</li>
<li title="Page 1">
    <a href="?p=1">1</a>
```

```html
    <!-- changed.html line 729-732 -->
    <a href="http://www.qianmu.org/program/88-1118-0.htm?p=8">&laquo;</a>
</li>
<li title="Page 1">
    <a href="http://www.qianmu.org/program/88-1118-0.htm?p=1">1</a>
```

(I tried to format result into unified diff, for original result, see gist at bottom.)

```diff
@@ -729,4 +729,4 @@
-    <a href="?p=8">&laquo;</a>
-    <a href="?p=8">&laquo;</a>
-    <a href="?p=8">&laquo;</a>
-    <a href="?p=1">1</a>
+    <a href="http://www.qianmu.org/program/88-1118-0.htm?p=8">&laquo;</a>
+    <a href="http://www.qianmu.org/program/88-1118-0.htm?p=8">&laquo;</a>
+    <a href="http://www.qianmu.org/program/88-1118-0.htm?p=8">&laquo;</a>
+    <a href="http://www.qianmu.org/program/88-1118-0.htm?p=1">1</a>
```

> Html contents in this case:
>
> - The origin file is https://gist.github.com/linkeo/5d9aabac0e29a7e5e9a36ba82d5599a6#file-prettydiff_origin-html-L729-L732
> - The changed file is https://gist.github.com/linkeo/03656c8faa7ecb92cedf19069e65f90d#file-prettydiff_changed-html-L729-L732
> - Then I got result like https://gist.github.com/linkeo/f9d5bb3a90dbd3f2882d873e16c4c167#file-compare_result-json-L731-L738

**Comment by prettydiff** [comment]
I completely rewrote the primary diff algorithm from scratch.  It is now super high precision and about 50x faster.  Please let me know if you are still getting sloppy results.  Here is a write up about now the new code works:  http://prettydiff.com/guide/unrelated_diff.xhtml
