### ISSUE TITLE
Golang Template Support

### ISSUE THREAD

**Issue by s4l1h** [prettydiff/prettydiff#403]
Tested On latest version.
https://golang.org/pkg/text/template/#hdr-Text_and_spaces

{{end}} ,{{-end}},{{end -}},{{- end -}} : All working fine but..

{{end-}} Have bug.

![pretty](https://cloud.githubusercontent.com/assets/216654/21928185/63b3aa32-d99a-11e6-972f-d143325b5626.png)

**Comment by prettydiff** [comment]
Awesome, thanks for the issue.  Would you be able to do me a quick favor and just dump that code sample as text into a comment.  Just a minor convenience.

**Comment by s4l1h** [comment]
`{{define "css"}}
    {{with .Get "CSS"}}{{end}}
{{end}} {{* Work Fine*}}
{{define "body"}}
    {{.Get "User" | hello}}
    {{with .Get "User"}}
        {{.Title}}
    {{end}}
    {{$conf:=.Get "Ctx"}}
    {{$conf.Get "template"}}
{{-end}}
{{define "kooter"}}
Footer Of The Index.tpl
{{- end}}
{{define "footer"}}
Footer Of The Index.tpl
{{end -}}

{{define "zooter"}}
Footer Of The Index.tpl
{{end-}}
`
