### ISSUE TITLE
Use biddle for dependency

### ISSUE THREAD

**Issue by prettydiff** [prettydiff/prettydiff#409]
Pretty Diff has only 1 dependency, JSLint, which is only used during the unit test build.  Currently Pretty Diff is automatically getting and updating this dependency as a git submodule, which is really unstable cross OS in a distributed manner.  JSLint will be served as a biddle publication.

The owner/maintainer of JSLint confirmed via email that he will only support projects that are fully ES6 compliant.  While Pretty Diff and biddle interpret all manners of JavaScript without issue they are not written using only the most modern conventions.  I am not sure, but I think this is the conflict with JSLint formally publishing via biddle.

As a result I will publish JSLint with biddle myself and serve it from my own domain.  This is issue is blocked biddle issue https://github.com/prettydiff/biddle/issues/34 as biddle also uses JSLint in its validation build.

**Comment by toferj** [comment]
You've marked this as closed and yet, I still get the, "Error: source does not appear to be markup." error when trying to beautify code.

**Comment by prettydiff** [comment]
@toferj That sounds like a different problem.  Could you please create a new issue indicate the steps to reproduce?
