### ISSUE TITLE
Feature Request: Unformatted HTML/Nunjucks Etc Blocks

### ISSUE THREAD

**Issue by thejamespower** [prettydiff/prettydiff#414]
Currently PrettyDiff formats a lot of HTML elements that do not require formatting. Great example of this is putting default-inline elements, like`<span>`, on a newline. This forces spaces in the HTML. Would be great to follow JS Beautify on this.

**Comment by prettydiff** [comment]
Can you provide me a code sample where this occurs?  I suspect it might be two inline adjacent elements.

**Comment by thejamespower** [comment]
Happens even when there's only one inline element. Although other than stylistic concerns, isn't really an issue.

Example 'for each.' gets put on newline.
```
<p class="short-copy">Unlock badges to earn 100<span class="points">pts</span>
  for each.</p>
```

However as you say, it is really an issue when there are more than one inline element

Before PrettyDiff:
```
<p class="prizes-carousel__required">You need <span class="prizes-carousel__required-points"><span class="count">890</span><span class="points">pts</span></span></p>
```

Becomes:
```
<p class="prizes-carousel__required">You need
          <span class="prizes-carousel__required-points">
            <span class="count">890</span>
            <span class="points">pts</span>
          </span>
        </p>
```
Which is an issue because the browser now renders a space between 890 and pts.
