### ISSUE TITLE
Enhancement Request: Asn1 Support

### ISSUE THREAD

**Issue by theshadow27** [prettydiff/prettydiff#416]
Looking to implement an [ASN.1 DER](https://en.wikipedia.org/wiki/Abstract_Syntax_Notation_One) diff utility and you seem to have 99% of what is required here with your modular architecture. The hard part is the hierarchical diff but that was solved in your XML module. Worst case (as I have been doing), DER can be converted to XER which can be run through the plain XML diff, but there are straight-forward ASN.1 libraries in JS - eg [ASN1.js](https://github.com/PeculiarVentures/ASN1.js) - and it would be awesome to have actual byte offsets. On the surface this doesn't seem like too heavy of a lift, but all I can find is minified code so it's hard to say for sure. I'd be glad to contribute if you have the pretty sources somewhere.

**Comment by prettydiff** [comment]
According to the link it looks like there are a couple different technologies at play:

* ASN.1 - syntax looks somewhat like C++
* DER - Looks somewhat like assembly
* XER - XML
* PER - Binary in Hex

I would have to do some work to support the ASN.1 syntax, but it could be done.  Since the XER format is XML that support is already provided.

The way this tool works is that it passes code through a beautifier in an attempt to normalize white space and comments before run the actual diff logic.  This is a primitive approach.  A more intelligent approach would be to parse the code, diff the parsed tokens, and then beautify that result which could more accurately yield a merge capability.  If only I could do this work full time....

I haven't though about adding a new beautifier to this tool, so that documentation is absent.  Here are what needs to be updated for such:

* prettydiff.js - https://github.com/prettydiff/prettydiff/blob/master/prettydiff.js#L159-L195  This library is the heart of the application.  It initiates the management of options, calls the proper library, and provides a result.  The highlighted code are the calls to the various language libraries and managing the results apart from associated meta data.
* lib/options.js - The most important consideration of architecture in this application is how to manage the options.  It still isn't perfect, but it is very modular and flexible across various different libraries independently.  Options are defined and managed here.  If there are options associated with ASN1.js they should be managed from within this file.
* lib/language.js - I don't know if you need to be in here, but this library manages detection and support of various languages.
* lib/diffview.js - Stay out of this one.  This library runs the diff algorithm and produce's its output.  Output comes in two formats: HTML and CLI similar to the old Unix diff utility.  The current (old) diff algorithm is too slow and this weekend I will be working to replace it with something more modern.

Let me know specific pain points you run into and I will try to help.

**Comment by theshadow27** [comment]
To clarify slightly, technically speaking, ASN.1 is the broad specification (ITU/IEC X.680, X.690, etc) under which the definition and encoding rules fall. 

- ASN.1 Notation (X.680) - the human readable syntax 
- XER (X.693) - XML encoding. Works perfectly already. Seldom used because it's extremely verbose, less efficient than normal XML. Sometimes abused with XST for interop with XML applications.
- PER (X.691) - A highly specialized untagged binary encoding; the ASN.1 Schema is required to decode. Kind of like Google Protocol Buffers, if you've used that. I've never seen this in use, not worth implementing.  
- BER, and subsets DER and CER, are a compact binary, octet-aligned, tagged encoding which each type is encoded to a "TLV":
-- T : a numeric tag, which indicates the data type, if it is constructed (containing other types) or primitive, as well as a class (universal, context, application, and private)
-- L : the length of the field in octets 
-- V : the value. X.690 describes how each of the 30 some-odd types are binary encoded/decoded. 
BER/DER/CER can stand alone and still be meaningful, but is extremely compact compared to XML, JSON, etc. CER and DER impose restrictions on BER encoding, but DER is valid BER. (The main difference is that BER allows "indefinite length", like XML with <tag> and </tag>, where as DER requires a length for each Type and there is no </tag>.  There are some obscure string encoding differences as well. Anyway, I digress...)

DER is useful because it is extremely compact, and there is exactly one correct way to encode input data eliminating the need for canonicalization. This makes it perfect for digital signatures; The most widespread application is [RFC5280](https://www.ietf.org/rfc/rfc5280.txt) X.509 Digital Certificates (e.g. on every TLS/SSL site on the web!). It's used in LDAP, CMS (S/MIME aka encrypted email) and P12/PFX/.key files. I think it's the most common encoding that no one has heard of! 

## Implementation

For a DER diff, the actual input file is either binary (often .der/.bin/.cer) or PEM / Base-64 encoded (.pem/.crt). This is totally useless for a diff tool. To match your architecture, the beautifier would be an "ASN.1 dump", the original [dumpasn1.c by Peter Gutmann](https://www.cs.auckland.ac.nz/~pgut001/dumpasn1.c) stands as the reference implementation dating back to the 80s but there have been many ports. The output looks something like this (for thje GitHub TLS cert):

```
    0 1913 :  SEQUENCE <30 82 07 79> constructed 
    4 1633 :    SEQUENCE <30 82 06 61> constructed 
    8    3 :      [0] Context <a0 03> constructed 
   10    1 :        INTEGER <02 01> '2' 
   13   16 :      INTEGER <02 10> '15938810608981134066197160231674485287' 
   31   13 :      SEQUENCE <30 0d> constructed 
   33    9 :        OBJECT IDENTIFIER <06 09> 'SHA256withRSA' (1.2.840.113549.1.1.11) 
   44    0 :        NULL <05 00>  
   46  117 :      SEQUENCE <30 75> constructed 
   48   11 :        SET <31 0b> constructed 
   50    9 :          SEQUENCE <30 09> constructed 
   52    3 :            OBJECT IDENTIFIER <06 03> 'C' (2.5.4.6) 
   57    2 :            PrintableString <13 02> 'US' 
   61   21 :        SET <31 15> constructed 
   63   19 :          SEQUENCE <30 13> constructed 
   65    3 :            OBJECT IDENTIFIER <06 03> 'O' (2.5.4.10) 
   70   12 :            PrintableString <13 0c> 'DigiCert Inc' 
   84   25 :        SET <31 19> constructed 
   86   23 :          SEQUENCE <30 17> constructed 
   88    3 :            OBJECT IDENTIFIER <06 03> 'OU' (2.5.4.11) 
   93   16 :            PrintableString <13 10> 'www.digicert.com' 
  111   52 :        SET <31 34> constructed 
  113   50 :          SEQUENCE <30 32> constructed 
  115    3 :            OBJECT IDENTIFIER <06 03> 'CN' (2.5.4.3) 
  120   43 :            PrintableString <13 2b> 'DigiCert SHA2 Extended Validation Server CA' 
  165   30 :      SEQUENCE <30 1e> constructed 
  167   13 :        UTCTime <17 0d> '2016-03-10 00:00:00 GMT' (160310000000Z) 
  182   13 :        UTCTime <17 0d> '2018-05-17 12:00:00 GMT' (180517120000Z) 
  197  253 :      SEQUENCE <30 81 fd> constructed 
  200   29 :        SET <31 1d> constructed 
  202   27 :          SEQUENCE <30 1b> constructed 
  204    3 :            OBJECT IDENTIFIER <06 03> 'businessCategory' (2.5.4.15) 
  209   20 :            UTF8String <0c 14> 'Private Organization' 
  231   19 :        SET <31 13> constructed 
  233   17 :          SEQUENCE <30 11> constructed 
  235   11 :            OBJECT IDENTIFIER <06 0b> 'jurisdictionOfIncorporationCountryName' (1.3.6.1.4.1.311.60.2.1.3) 
  248    2 :            PrintableString <13 02> 'US' 
  252   25 :        SET <31 19> constructed 
  254   23 :          SEQUENCE <30 17> constructed 
  256   11 :            OBJECT IDENTIFIER <06 0b> 'jurisdictionOfIncorporationStateOrProvinceName' (1.3.6.1.4.1.311.60.2.1.2) 
  269    8 :            PrintableString <13 08> 'Delaware' 
  279   16 :        SET <31 10> constructed 
  281   14 :          SEQUENCE <30 0e> constructed 
  283    3 :            OBJECT IDENTIFIER <06 03> 'serialNumber' (2.5.4.5) 
  288    7 :            PrintableString <13 07> '5157550' 
  297   36 :        SET <31 24> constructed 
  299   34 :          SEQUENCE <30 22> constructed 
  301    3 :            OBJECT IDENTIFIER <06 03> 'STREET' (2.5.4.9) 
  306   27 :            PrintableString <13 1b> '88 Colin P Kelly, Jr Street' 
  335   14 :        SET <31 0e> constructed 
  337   12 :          SEQUENCE <30 0c> constructed 
  339    3 :            OBJECT IDENTIFIER <06 03> 'postalCode' (2.5.4.17) 
  344    5 :            PrintableString <13 05> '94107' 
  351   11 :        SET <31 0b> constructed 
  353    9 :          SEQUENCE <30 09> constructed 
  355    3 :            OBJECT IDENTIFIER <06 03> 'C' (2.5.4.6) 
  360    2 :            PrintableString <13 02> 'US' 
  364   19 :        SET <31 13> constructed 
  366   17 :          SEQUENCE <30 11> constructed 
  368    3 :            OBJECT IDENTIFIER <06 03> 'ST' (2.5.4.8) 
  373   10 :            PrintableString <13 0a> 'California' 
  385   22 :        SET <31 16> constructed 
  387   20 :          SEQUENCE <30 14> constructed 
  389    3 :            OBJECT IDENTIFIER <06 03> 'L' (2.5.4.7) 
  394   13 :            PrintableString <13 0d> 'San Francisco' 
  409   21 :        SET <31 15> constructed 
  411   19 :          SEQUENCE <30 13> constructed 
  413    3 :            OBJECT IDENTIFIER <06 03> 'O' (2.5.4.10) 
  418   12 :            PrintableString <13 0c> 'GitHub, Inc.' 
  432   19 :        SET <31 13> constructed 
  434   17 :          SEQUENCE <30 11> constructed 
  436    3 :            OBJECT IDENTIFIER <06 03> 'CN' (2.5.4.3) 
  441   10 :            PrintableString <13 0a> 'github.com' 
  453  290 :      SEQUENCE <30 82 01 22> constructed 
  457   13 :        SEQUENCE <30 0d> constructed 
  459    9 :          OBJECT IDENTIFIER <06 09> 'RSA' (1.2.840.113549.1.1.1) 
  470    0 :          NULL <05 00>  
  472  271 :        BIT STRING <03 82 01 0f> (2160 bits) 
           :          30 82 01 0a 02 82 01 01 00 e7 88 5c f2 96 5c 97 
           :          18 1c ba 98 e2 03 f1 7f 39 91 91 c2 6f d9 96 e7 
           :          28 40 64 cd 4c a9 81 12 03 6c ae 7f e6 c6 19 e0 
           :          5a 63 f0 6c 0b d4 68 b3 ff fd 3e fd 25 cf b5 59 
           :          73 29 c4 c8 b3 f4 f2 ba c9 94 51 16 e2 28 d1 dd 
           :          9b c7 8d b7 34 0e a1 38 bd 91 4e d6 e7 7e cf b2 
           :          d0 f1 52 fd 84 e9 41 27 a5 4e ea be 16 ec 2d b3 
           :          9b fa 68 0c 1e 37 23 1c 60 3d 07 07 26 e4 91 da 
           :                  [ Another 142 bytes skipped ]
  747  890 :      [3] Context <a3 82 03 7a> constructed 
  751  886 :        SEQUENCE <30 82 03 76> constructed 
  755   31 :          SEQUENCE <30 1f> constructed 
  757    3 :            OBJECT IDENTIFIER <06 03> 'authorityKeyIdentifier' (2.5.29.35) 
  762   24 :            OCTET STRING <04 18> encapuslates 
  764   22 :              SEQUENCE <30 16> constructed 
  766   20 :                [0] Context <80 14> (20b) 
           :                  3d d3 50 a5 d6 a0 ad ee f3 4a 60 0a 65 d3 21 d4 
           :                  f8 f8 d6 0f 
  788   29 :          SEQUENCE <30 1d> constructed 
  790    3 :            OBJECT IDENTIFIER <06 03> 'subjectKeyIdentifier' (2.5.29.14) 
  795   22 :            OCTET STRING <04 16> encapuslates 
  797   20 :              OCTET STRING <04 14> (20b) 
           :                88 5c 48 67 19 cc a0 76 59 2d 11 79 c3 be a2 ac 
           :                87 22 27 5b 
  819   37 :          SEQUENCE <30 25> constructed 
  821    3 :            OBJECT IDENTIFIER <06 03> 'subjectAltName' (2.5.29.17) 
  826   30 :            OCTET STRING <04 1e> encapuslates 
  828   28 :              SEQUENCE <30 1c> constructed 
  830   10 :                [2] Context <82 0a> (10b) 'github.com'
  842   14 :                [2] Context <82 0e> (14b) 'www.github.com'
  858   14 :          SEQUENCE <30 0e> constructed 
  860    3 :            OBJECT IDENTIFIER <06 03> 'keyUsage' (2.5.29.15) 
  865    1 :            BOOLEAN <01 01> 'TRUE' 
  868    4 :            OCTET STRING <04 04> encapuslates 
  870    2 :              BIT STRING <03 02> '101' (3 bits) 
  874   29 :          SEQUENCE <30 1d> constructed 
  876    3 :            OBJECT IDENTIFIER <06 03> 'extKeyUsage' (2.5.29.37) 
  881   22 :            OCTET STRING <04 16> encapuslates 
  883   20 :              SEQUENCE <30 14> constructed 
  885    8 :                OBJECT IDENTIFIER <06 08> 'serverAuth' (1.3.6.1.5.5.7.3.1) 
  895    8 :                OBJECT IDENTIFIER <06 08> 'clientAuth' (1.3.6.1.5.5.7.3.2) 
  905  117 :          SEQUENCE <30 75> constructed 
  907    3 :            OBJECT IDENTIFIER <06 03> 'cRLDistributionPoints' (2.5.29.31) 
  912  110 :            OCTET STRING <04 6e> encapuslates 
  914  108 :              SEQUENCE <30 6c> constructed 
  916   52 :                SEQUENCE <30 34> constructed 
  918   50 :                  [0] Context <a0 32> constructed 
  920   48 :                    [0] Context <a0 30> constructed 
  922   46 :                      [6] Context <86 2e> (46b) 'http://crl3.digicert.com/sha2-ev-server-g1.crl'
  970   52 :                SEQUENCE <30 34> constructed 
  972   50 :                  [0] Context <a0 32> constructed 
  974   48 :                    [0] Context <a0 30> constructed 
  976   46 :                      [6] Context <86 2e> (46b) 'http://crl4.digicert.com/sha2-ev-server-g1.crl'
 1024   75 :          SEQUENCE <30 4b> constructed 
 1026    3 :            OBJECT IDENTIFIER <06 03> 'certificatePolicies' (2.5.29.32) 
 1031   68 :            OCTET STRING <04 44> encapuslates 
 1033   66 :              SEQUENCE <30 42> constructed 
 1035   55 :                SEQUENCE <30 37> constructed 
 1037    9 :                  OBJECT IDENTIFIER <06 09> 'DigiCert EV policy' (2.16.840.1.114412.2.1) 
 1048   42 :                  SEQUENCE <30 2a> constructed 
 1050   40 :                    SEQUENCE <30 28> constructed 
 1052    8 :                      OBJECT IDENTIFIER <06 08> 'cps' (1.3.6.1.5.5.7.2.1) 
 1062   28 :                      IA5String <16 1c> 'https://www.digicert.com/CPS' 
 1092    7 :                SEQUENCE <30 07> constructed 
 1094    5 :                  OBJECT IDENTIFIER <06 05> (2.23.140.1.1) 
 1101  136 :          SEQUENCE <30 81 88> constructed 
 1104    8 :            OBJECT IDENTIFIER <06 08> 'authorityInfoAccess' (1.3.6.1.5.5.7.1.1) 
 1114  124 :            OCTET STRING <04 7c> encapuslates 
 1116  122 :              SEQUENCE <30 7a> constructed 
 1118   36 :                SEQUENCE <30 24> constructed 
 1120    8 :                  OBJECT IDENTIFIER <06 08> 'ocsp' (1.3.6.1.5.5.7.48.1) 
 1130   24 :                  [6] Context <86 18> (24b) 'http://ocsp.digicert.com'
 1156   82 :                SEQUENCE <30 52> constructed 
 1158    8 :                  OBJECT IDENTIFIER <06 08> 'caIssuers' (1.3.6.1.5.5.7.48.2) 
 1168   70 :                  [6] Context <86 46> (70b) 
           :                    68 74 74 70 3a 2f 2f 63 61 63 65 72 74 73 2e 64 
           :                    69 67 69 63 65 72 74 2e 63 6f 6d 2f 44 69 67 69 
           :                    43 65 72 74 53 48 41 32 45 78 74 65 6e 64 65 64 
           :                    56 61 6c 69 64 61 74 69 6f 6e 53 65 72 76 65 72 
           :                    43 41 2e 63 72 74 
 1240   12 :          SEQUENCE <30 0c> constructed 
 1242    3 :            OBJECT IDENTIFIER <06 03> 'basicConstraints' (2.5.29.19) 
 1247    1 :            BOOLEAN <01 01> 'TRUE' 
 1250    2 :            OCTET STRING <04 02> encapuslates 
 1252    0 :              SEQUENCE <30 00> constructed 
 1254  383 :          SEQUENCE <30 82 01 7f> constructed 
 1258   10 :            OBJECT IDENTIFIER <06 0a> (1.3.6.1.4.1.11129.2.4.2) 
 1270  367 :            OCTET STRING <04 82 01 6f> encapuslates 
 1274  363 :              OCTET STRING <04 82 01 6b> (363b) 
           :                01 69 00 76 00 a4 b9 09 90 b4 18 58 14 87 bb 13 
           :                a2 cc 67 70 0a 3c 35 98 04 f9 1b df b8 e3 77 cd 
           :                0e c8 0d dc 10 00 00 01 53 61 89 ea 1e 00 00 04 
           :                03 00 47 30 45 02 21 00 87 1d 21 18 fd 13 8a db 
           :                fb 0e 96 36 ca 68 d1 1c 29 6c fa 07 11 c9 34 f3 
           :                ad 8d 2c ae 56 74 a7 e1 02 20 27 a4 6a bd 86 d2 
           :                5f 5b ca 2d e5 fb be 99 ce 7c 20 1f 4b 66 3c 94 
           :                1e 51 34 cc 24 ea eb 36 42 20 00 76 00 68 f6 98 
           :                        [ Another 235 bytes skipped ]
 1641   13 :    SEQUENCE <30 0d> constructed 
 1643    9 :      OBJECT IDENTIFIER <06 09> 'SHA256withRSA' (1.2.840.113549.1.1.11) 
 1654    0 :      NULL <05 00>  
 1656  257 :    BIT STRING <03 82 01 01> (2048 bits) 
           :      8b 6c db 64 c6 eb 29 ab 27 2a f2 1d 44 a5 b9 80 
           :      5f 4c 0c e4 3a 16 ee 13 3f 15 57 73 e0 b2 77 2a 
           :      67 ed ca 4d 72 77 c8 ff 3d 2c 51 ac 04 0d d8 ca 
           :      ff 7e b2 9e 2b c3 44 d5 c3 23 8b 7d a6 25 b0 6a 
           :      a5 6b 4a ff ec 02 f9 ab cf a6 50 54 6c da 73 3f 
           :      9d dc b9 33 05 fd 0b 2c c4 8b 4f 18 d3 f9 fc e4 
           :      fd 02 3d 41 c4 0f cd a1 f5 99 2a 1e 2e 7d 5e dc 
           :      cf 7a 58 44 34 b8 04 5f 84 10 54 38 97 91 98 fb 
           :              [ Another 128 bytes skipped ] 
1.87KiB, 153 tags, dumped in 0.001016613 sec
```

The first column is octet-offset, the second is length. The indentation illustrates nesting of constructed types. Between carrots is the tag-Id and length. 

The problem with diffing the dumpasn1 is if one byte is added or removed, the byte offset and lengths for all enclosing Types changes and the rest of the lines get flagged as changed. If the byte offset and tLv is not included in the dumpasn1, there is no context to where the changes happened. 

The key functionality here is somehow associating metadata (the dumpasn1 lines) with the diff tokens (whatever is the most convenient structural representation to maximize reuse of existing code; XML, JSON, etc). After the diff, the metadata is retrieved and substituted for the tokens in the diff output.  It sounds like this is a pretty heavy lift considering the current architecture.

Perhaps, as a interim solution, the beautifier could prepare two versions of each input:
1. A full dump, displayed to the user
2. An abridged dump, less all offsets and lengths, and stripping all <tagid lenid> from constructed types, to be diff-ed

The line numbers of 1 and 2 should theoretically be the same, this could be guaranteed by stripping it down using regex rather than running dumpasn1 twice. Then it's just a matter of substituting the full lines from 1 into the diff output afterwards, I guess this would need to go after diffview.js? Maybe while you are rewriting you can add a 'post beautifier' or 'reformatter' stub. 

Does this approach make sense?

**Comment by theshadow27** [comment]
Also thanks for your help and awesome software! 

And thank you for your service!!

**Comment by prettydiff** [comment]
I am reviewing this now (I know it is has been a long delay, but it took me that long to focus on military education and writing the new diff algorithm).  I have no plans to implement a beautifier for the DER format.  You can diff the DER format perfectly fine in this tool, but just ensure the language option is set to `text` value.  If there are improvements that can be made to the beautification for the ASN.1 format please let me know and I can evaluate the feasibility.
