### ISSUE TITLE
How to use in react?

### ISSUE THREAD

**Issue by MobileAppVault** [prettydiff/prettydiff#419]
Hi,

can I use prettydiff in react apps?

thanks for your help!

**Comment by prettydiff** [comment]
Pretty Diff is just JavaScript.  The readme.md document shows several ways to execute the application.  Will none of those work for you?  The application includes an API to run in both the browser and with Node.

**Comment by MobileAppVault** [comment]
Thanks for the answer!

Ok, I've loaded prettydiff with npm install --save prettydiff in my app and then I import the prettydiff script but I got some error in function glib_prettydiff():

`
Cannot find module '//lib/csspretty.js'.
`

and I guess this condition is wrong for my use case:

```
var localPath = (typeof process === "object" && typeof process.cwd === "function" && (process.cwd() === "/" || (/^([a-z]:\\)$/).test(process.cwd()) === true) && typeof __dirname === "string")
            ? __dirname
            : ".";
```
Now I've overwrite the localPath variable with 

`localPath = ".";` 

Now it works perfect... also with "unibeautify".

Do you know if we can fix that condition? I'm not familar with node local structures. 

Maybe this will fix it as well: 

`&& !process.browser`

```
var localPath = (typeof process === "object" && typeof process.cwd === "function" && (process.cwd() === "/" || (/^([a-z]:\\)$/).test(process.cwd()) === true) && typeof __dirname === "string" && !process.browser )
            ? __dirname
            : ".";
```

**Comment by prettydiff** [comment]
I am not sure why it's doing that.  I will investigate.

**Comment by prettydiff** [comment]
Are you Windows or other OS?  What command are you using to execute Pretty Diff?

**Comment by prettydiff** [comment]
I have changed some things and some some things around since this issue was created.  It might be resolved now, but I am not sure as I cannot reproduce it.

**Comment by HenryYong** [comment]
Hi, I'm using pretty diff in my react app. I also have that `Cannot find module '//lib/csspretty.js'` error. I'm using Mac and I installed it by using `npm install prettydiff --save-dev` and the version of pretty diff is `99.0.1`. Did I do something wrong and lead this error? thx!

**Comment by prettydiff** [comment]
Dont worry about the absurd version number.  I had a falling out with NPM.  Here is a far more updated package - https://www.npmjs.com/package/prettydiff2

I dont know the relationship between React and your NPM instance.  What you can try is on your command line just `npm install prettydiff2 -g`.  The `-g` flag means global, so anywhere on the command line the application just works when executed from the command line.

I am not sure how adding a project to your dev dependencies changes the way the package is referenced from a given application.  I would recommend asking about this in IRC.  I recommend irc.freenode.net and the channels ##javascript or #npm.

**Comment by HenryYong** [comment]
I have installed `prettydiff2`, and this time I get an error says: 
![image](https://user-images.githubusercontent.com/7967105/30261848-0af7adf6-9701-11e7-9268-feb0e943d233.png)

**Comment by prettydiff** [comment]
That is a valid bug.  I will have to look into that.

**Comment by abrarmahmood** [comment]
any update on this?

**Comment by frankmariette** [comment]
Is this bug still being looked into?

**Comment by prettydiff** [comment]
Here is what I need to do to achieve this.

Currently everything used by the browser for the Pretty Diff html is 2 files.  One is from the parser dependency and the other is Pretty Diff plus all the DOM stuff.

I need to create a secondary arbitrary artifact so that all of Pretty Diff is jumbled into a single file minus the DOM part for

**Comment by prettydiff** [comment]
It looks like I might have already solved for this.  Download Pretty Diff 3 and include these two files, in this order, directly into your page:

1. prettydiff/node_modules/parse-framework/js/browser.js
1. prettydiff/js/prettydiff.js

Those files are not ECMAScript modules so they need to be included into your page code either using HTML script tags or integrated into the rest of your JS code using your existing build.

Let me know if that breaks things and we can go from there.  Those files are both vanilla JS without any other dependencies.  Aside from a single binding to the *window* object in Parse Framework they are entirely environment agnostic, so you are tied to Pretty Diff's HTML.
