### ISSUE TITLE
Attributes in XML are sorted even if objsort:false

### ISSUE THREAD

**Issue by carnegie-jwilliamson** [prettydiff/prettydiff#420]
I was formatting XML with `mode:beautify textpreserve:true force_attribute:true objsort:none` but the attributes were still being sorted. Changing `lib/markuppretty.js:1300` fixed it for me:

```
@@ -1297,7 +1298,7 @@
                         if (tname.slice(0, 3) === "cf_") {
                             cft = "required";
                         }
-                        if (options.jsx === false && cft === undefined) {
+                        if (objsortop == true && options.jsx === false && cft === undefined) {
                             attstore = safeSort(attstore);
                         }
                         for (ind = 0; ind < len; ind += 1) {
```

**Comment by prettydiff** [comment]
You are absolutely correct.  While I am in the code making this adjustment are there any attribute related preferences you would suggest or behaviors you would like done differently?

**Comment by carnegie-jwilliamson** [comment]
I'm not sure how feasible it would be, but it would be nice to have a way to have each attribute on its own line if there are multiple attributes, but on the same line as the tag opening if it is the only attribute.

**Comment by prettydiff** [comment]
I already have an option for that:  http://prettydiff.com/documentation.xhtml#force_attribute

Unfortunately, I have it configured to work on every attribute regardless of quantity.  I can look at changing this so that it fails if there is only 1 attribute.

**Comment by carnegie-jwilliamson** [comment]
Thanks!
