### ISSUE TITLE
Diff algorithm has duplicate checks that will always be false

### ISSUE THREAD

**Issue by DraagrenKirneh** [prettydiff/prettydiff#426]
in http://prettydiff.com/guide/unrelated_diff.xhtml
in line 127 of the fix function the first expression `one[code[2] - 1] === two[prior[4] - 1]` is identical to the one on line 119. 
if this expression is true then the branch on line 119 will return, thus the same expression on 127 will always be false.

the same issue is present on line 143, where line 135 returns if that expression is true

**Comment by prettydiff** [comment]
Thank you, I will examine this tomorrow and make the appropriate changes.

**Comment by prettydiff** [comment]
Questionable code removed in branch 2.1.18.  Thank you so much!

**Comment by DraagrenKirneh** [comment]
I reviewed and see that i was wrong about line 143, and line 135 they are different:
`one[prior[2] - 1] === two[code[4] - 1]` vs `one[code[2] - 1] === two[prior[4] - 1]`.

**Comment by prettydiff** [comment]
What I modified in this change are these two lines:

* https://github.com/prettydiff/prettydiff/blob/master/lib/diffview.js#L231
* https://github.com/prettydiff/prettydiff/blob/master/lib/diffview.js#L247

It does appear the logic is duplicated exactly as you suggested.

Line 223: `if (one[code[2] - 1] === two[prior[4] - 1]) {`
Line 231: `if (one[code[2] - 1] === two[prior[4] - 1] || one[code[2]] === two[prior[4] - 1]) {`
Line 247: `if (one[code[2] - 1] === two[prior[4] - 1] || one[code[2] - 1] === two[prior[4]]) {`

**Comment by DraagrenKirneh** [comment]
the code is under two different branches to it is only the first duplication that will always be false.
looking just at the if statements:
```
else if (prior[0] === "replace") {
    if (code[0] === "delete") { ... return }
    if (one[code[2] - 1] === two[prior[4] - 1] || one[code[2]] === two[prior[4] - 1]) { ... }
} 
else if (code[0] === "insert") {
    if (one[prior[2] - 1] === two[code [4] - 1]) { ... return }
    if (one[code [2] - 1] === two[prior[4] - 1] || one[code[2] - 1] === two[prior[4]]) { ... }
}
```

The last line under the "insert" branch can be rewritten to `if (prior[4] = 0)` since `code[2]` will always be -1 for "insert" codes, so `one[code[2] -1]` will be Undeclared.

Perhaps the more correct thing is to rewrite it checking the line at code[4] vs prior[2] as in the first if branch? `if (one[code[4] - 1] === two[prior[2]]) { ... }`

**Comment by prettydiff** [comment]
Would you mind creating a pull request for the lib/diffview.js file from the 2.1.18 branch?  That way we can leave comments per line and I can give you credit for this work as a code contributor.
