### ISSUE TITLE
Run prettydiff in the browser (vanilla JS)

### ISSUE THREAD

**Issue by dvlato** [prettydiff/prettydiff#430]
Similar to the reporter in https://github.com/prettydiff/prettydiff/issues/248, I am unable to execute prettydiff with the plain vanilla JS code. 

I believe that it would be really beneficial that you could add a minimalistic sample HTML page which shows a diff using hardcoded filepaths, for those of us who cannot install node in our CI build servers and still would love to benefic from prettydiff's reporting capabilities.   I am not a Javascript developer, so I cannot really figure out how to make it work by studying the index.html example or the event handler logic in dom.js.

**Comment by dvlato** [comment]
This is what I have so far, which throws several errors:

<html>
<head>
</head>
<body>
<script>
        var global = {},
                args   = {
                    source: "asdf",
                    diff  : "asdd",
                    lang  : "text"
                };
                output = prettydiff(args);
    </script>

    <script src="lib/csspretty.js"></script>
    <script src="lib/csvpretty.js"></script>
    <script src="lib/diffview.js"></script>
    <script src="lib/jspretty.js"></script>
    <script src="lib/markuppretty.js"></script>
    <script src="lib/safeSort.js"></script>

    <script src="prettydiff.js"></script>
    <script src="api/dom.js"></script>
</body>
</html>

**Comment by prettydiff** [comment]
I will make this my top priority after I resolve this regression issue #429

**Comment by prettydiff** [comment]
Done and in branch 2.1.18.  I created a new file named barebones.xhtml to address your concern, but please note it will not work on the prettydiff.com domain due to security policy that forbids inline JavaScript.

**Comment by prettydiff** [comment]
I relocated the recently created barebones code examples to test/barebones
