### ISSUE TITLE
Preserve brace style of object declaration

### ISSUE THREAD

**Issue by djoaquing** [prettydiff/prettydiff#437]
Input inside a <script> tag in a .tag file:

var q = { x: "a", b: "c" }

When used, prettydiff changes it to:

var q = {
x: "a",
b: "c"
}

I would like it not to expand - to stay as the original input. JS Beautifier has this feature by changing its brace style to collapse-preserve-inline.  How can I do this?

I'm using Atom, MacOS 10.12, latest version of atom-beautify.

Thank you,

**Comment by prettydiff** [comment]
Try using the `formatObject` option with a value of `inline`.  http://prettydiff.com/documentation.xhtml#formatObject

If this doesn't work please reopen this issue and I will investigate further.

**Comment by djoaquing** [comment]
Indeed it is not shown in Atom Beautify. I tried digging directly in the code, but no dice..

**Comment by prettydiff** [comment]
You will want to look at this answer for guidance.

https://github.com/Glavin001/atom-beautify/issues/1559#issuecomment-294233175

Please let me know if you have any questions.

**Comment by djoaquing** [comment]
Located prettydiff.coffee, tried to emulate a block of code for `formatObject`, but this is as far as I got:
```

  formatObject: (formatObject) ->
        formatObject or false
      preserve: ['preserve_newlines', (preserve_newlines) ->
        if (preserve_newlines is true ) then \
          "inline" else "inline"
      ]
```

Modified it from the `objsort` code block, lost as to how to properly do finish it.

**Comment by prettydiff** [comment]
You are going to want something more like:
```
formatObject: ['formatObject_inline', (formatObject_inline) ->
    if (formatObject_inline is true ) then \
        "inline" else "default"
]
formatObject: ['formatObject_indent', (formatObject_indent) ->
    if (formatObject_indent is true ) then \
        "indent" else "default"
]
```
This code provides the interface between the Atom Beautify settings and the API for the beautifier.  The code is looking for controls of a certain id in the Atom Beautify settings and using the result of those controls to determine which value to assign an object property with the name of the beautifier's option.  That part takes care of the beautifier, but now you need to extend the Atom Beautify settings so that these controls are exposed to the user, which is the second half of that comment I linked to.

This option is a bit tricky because it takes a string data type and has more than two values.  There is probably a more elegant way to go about this, but I am not sure as I am also weak with CoffeeScript.  You will likely get corrected by Glavin when you submit your pull request.

**Comment by djoaquing** [comment]
Alright, managed this:

```
format_object:
      type: 'string'
      default: "default"
      description: "Determines whether JavaScript object properties should always indented, remain on a single line, or left to the default formatting"
      enum: ["default", "indent", "inline"]
```

But the properly doesn't appear on the atom UI, even after restart.

**Comment by prettydiff** [comment]
@Glavin001  Would you mind assisting with this?  It is a future Atom-Beautify pull request to add a Pretty Diff option.

**Comment by Glavin001** [comment]
> But the properly doesn't appear on the atom UI, even after restart.

@djoaquing try updating the docs and options with `npm run docs`. This will generate the options to `src/options.json` file which is loaded as the configuration of Atom-Beautify and displayed in Atom Settings view.

**Comment by djoaquing** [comment]
@Glavin001 I get a "missing script: docs" when I run it, any idea what i'm doing wrong? 

I apologize in advance, not extremely versatile in git/npm.

**Comment by Glavin001** [comment]
@djoaquing are you editing [Atom-Beautify](https://github.com/Glavin001/atom-beautify)? The `docs` script should be available: https://github.com/Glavin001/atom-beautify/blob/master/package.json#L332

**Comment by djoaquing** [comment]
I was able to! I wasn't in the correct atom-beautify folder.

So, output:
```
> atom-beautify@0.29.22 docs /Users/j/.atom/packages/atom-beautify
> npm run build-options && coffee docs/

> atom-beautify@0.29.22 build-options /Users/j/.atom/packages/atom-beautify
> node script/build-options.js

Building options for beautifiers
Done building options for beautifiers
Beautifier options successfully saved to /Users/j/.atom/packages/atom-beautify/src/options.json
Generating options...
Loading options template...
Building documentation from template and options...
Writing documentation to file...
Updating package.json
Done.
```

But, still nothing, even after restarting atom!

**Comment by Glavin001** [comment]
Sounds like something is missing. 

Checklist:
- [ ] Add `format_object` to the language options
  - See https://github.com/Glavin001/atom-beautify/blob/master/src/languages/javascript.coffee#L25 for `JavaScript` language
- [ ] Add `format_object` to the beautifier options
  - See https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/prettydiff.coffee#L7  for `Pretty Diff` beautifier

**Comment by prettydiff** [comment]
I just checked the Pretty Diff documentation for version 1.16.37 and the formatObject option doesn't exist.  It must be something I added this past summer.  @djoaquing hold off on this work for now.  I am working on getting the latest version into Atom Beautify right now.
