### ISSUE TITLE
new option for comment preservation

### ISSUE THREAD

**Issue by mksuper1** [prettydiff/prettydiff#438]
Hi, 
If I set the wrap to 80, the comments line will be wrap into a single line if less than 80. 
Is there a option where I can prevent wrapping of comment lines, alternatively, wrap of comments should be used if it is more than 80 where it will be split into 2 lines. Not merging of comments line into a single line if it is less than 80

Sample
// testing
// 123

output
// testing 123

**Comment by prettydiff** [comment]
Yeah, this is actually intentional.  The idea is that long wordy comments should evolve as a user's preferences change.  Lists are supported though.  Try starting your comments with a `*` or `-`, example:

    //* first point
    //* second point
    //    - sub point

**Comment by mksuper1** [comment]
Hi,
is it possible for you to provide an option something like
preserve_comment_wrap

i.e. if the comments is less than the wrap setting,  do nothing
if comments is more than wrap setting, split into multiple lines.

using //* is not practical as I used ctrl / to comment uncomment lines. //* will break the CTRL / key.

thanks
