### ISSUE TITLE
how to install new version 2.x for vscode

### ISSUE THREAD

**Issue by mksuper1** [prettydiff/prettydiff#439]
Hi,

I am using react-beautifier in vscode which is using a old verison of prettydiff. 
How to install the new version into vscode?

thanks

**Comment by prettydiff** [comment]
The old version is likely 1.16.37 which is the latest version published to NPM.  I am working on an alternative to NPM that I hope to have ready in about 2 week: https://github.com/prettydiff/biddle

In the meantime you can clone down this repository and copy it over the Pretty Diff files used by vscode.

**Comment by mksuper1** [comment]
I tried but it is not working.

**Comment by prettydiff** [comment]
* react-beautify - https://marketplace.visualstudio.com/items?itemName=taichi.react-beautify

**Comment by prettydiff** [comment]
The Pretty Diff options appear to be configured at https://github.com/taichi/react-beautify/blob/master/src/formatters.ts#L38-L49

It appears VSCode as an internal node_modules folder at (in windows) c:\program files (x86)\microsoft vs code\resources\app\node_modules  Did you look for a prettydiff folder in that location?

**Comment by prettydiff** [comment]
I just downloaded react-beautify and here is the directory (in Windows) you want to replace:

C:\Users\austincheney\.vscode\extensions\taichi.react-beautify-0.3.0\node_modules\prettydiff

Just clone this project down.  Copy the cloned directory over the directory that comes with react-beautify and then restart VSCode.
