### ISSUE TITLE
Demo Unresponsive; output.replace is not a function in dom.js @ 2854

### ISSUE THREAD

**Issue by donsequitur** [prettydiff/prettydiff#440]
The Demo on your homepage (http://prettydiff.com/) gives an error when clicking execute.  It seems to happen regardless of the options selected.  Here is the JS error:

Output in Chrome:
```
dom.js:2856 Uncaught TypeError: output.replace is not a function
    at dom__event_recycle_execOutput (dom.js:2856)
    at HTMLButtonElement.dom__event_recycle (dom.js:4492)
dom__event_recycle_execOutput	@	dom.js:2856
dom__event_recycle	@	dom.js:4492
```

Firefox:
```
TypeError: output.replace is not a function[Learn More]  dom.js:2854:30
	dom__event_recycle_execOutput http://prettydiff.com/api/dom.js:2854:30
	dom__event_recycle http://prettydiff.com/api/dom.js:4492:17
```

**Comment by prettydiff** [comment]
Thank you, I made some rush changes late yesterday that can only be tested on the server, functionality regarding cross domain requests.  It seems I did a very poor job of testing everything else and broke the site.  Please let me know if you encounter any additional problems.

**Comment by donsequitur** [comment]
Thanks for the quick response!  I opened another ticket for a more minor issue I found. #441
