### ISSUE TITLE
Fold HTML error

### ISSUE THREAD

**Issue by donsequitur** [prettydiff/prettydiff#441]
![2017-04-18 17_26_25-pretty diff - the difference tool](https://cloud.githubusercontent.com/assets/9997705/25153885/4692d11e-245c-11e7-9366-4b681c8f11ce.png)

Hi,
I found another one. HTML exposed where I think a fold is meant to be. 

`<li xmlns="http://www.w3.org/1999/xhtml">fold" title="folds from line 3 to line 3"&gt;- 3</li>`

**Comment by prettydiff** [comment]
Yeah, that is completely broken.  I am having trouble reproducing though.  Is everything else at the default?

**Comment by donsequitur** [comment]
Hi, 
Here are my settings.  I think the only change from default is inline view, but I could be wrong:

```
{
  "feedreport": {},
  "codereport": {
    "left": 634,
    "top": 362,
    "width": 628,
    "height": 412,
    "min": false,
    "max": false,
    "zindex": "54"
  },
  "statreport": {},
  "feedback": {
    "newb": false,
    "veteran": false
  },
  "knownname": "\"43571360293269499936976072895274\"",
  "mode": "modediff",
  "newlabel": "new1",
  "colorScheme": 0,
  "language": 22,
  "newline": "newline-no",
  "_viewtype": "inline"
}
```

**Comment by prettydiff** [comment]
Yep, I can reproduce it now.  It has to do with the "inline" error.
