### ISSUE TITLE
Markup beautification issue for `do while` in `<%` templates

### ISSUE THREAD

**Issue by lenilsondc** [prettydiff/prettydiff#445]
Found a minor defect while beautifying markup jsp and asp like template delimiters (i.e., `<% .. %>`), the parse is interpreting `<% do %>` as `template_start` and it causes the beautifier to indent one extra level when sometimes it shouldn't do this. I believe the reason for this feature to exist is to support `<% do %>` like loops or something similar, but it's matching every template that has a `do` within the delimiters.

For example, this:
````jsp
<%
    int i = 0;
    
    do {
        i++;
    }while(i < 3);
%>
<!DOCTYPE html>
<html>
    ...
</html>
````

Is beautified to:
````jsp
<%
    int i = 0;
    
    do {
        i++;
    }while(i < 3);
%>
    <!DOCTYPE html>
    <html>
        ...
    </html>
````

The example above describe the `do while` case, but it can also be triggered if you have any `"\sdo\s"` within the template.

````jsp
<%
   // do the harlem shake
%>
    <!DOCTYPE html>
    <html> ...</html>
````

I found out which part of the code is doing this, check the code below:

````javascript
...
else if ((/\sdo\s/).test(element) === true || (/^(<%(%|-)?\s*if)/).test(element) === true) {
    types[types.length - 1] = "template_start";
}
....
````
I managed to solve this by changing the regex to `/^<%\s*do\s` so that the `do` will match the beginning of a template but not every word in the template.

**Comment by prettydiff** [comment]
I found in the code an explicit rule to impose this behavior: https://github.com/prettydiff/prettydiff/blob/master/lib/markuppretty.js#L1253

I am doing some research to determine why I added this rule.

**Comment by prettydiff** [comment]
The rule was added for ERB templates.  I am correcting for this by now also checking that the closing delimiter is `-%>`.
