### ISSUE TITLE
JavaScript "Standard" code style should be added as a "styleguide" option value

### ISSUE THREAD

**Issue by prettydiff** [prettydiff/prettydiff#449]
## Goal
Extend option `styleguide` with new value: "standard" - https://standardjs.com/rules.html#javascript-standard-style

## Already supported options
* inchar: " "
* insize: 2
* correct: true
* quoteConvert: "single"
* space: true
* preserve: 1
* braces: "knr"
* ternaryline: false
* varword: each
* endcomma: "never"
* wrap: 0
* vertical: "none"
* braceline: false
* bracepadding: false
* newline: true

## Additional enhancements
* consider converting `semicolon` option from boolean to a string value with values: "insert", "remove", "ignore".
* consider wrapping all assignments into parens if in a condition
* consider combining multiple import statements into a single collapsed statement of comma separated values
* consider converting floating numbers `.5` into 0 prepended numbers `0.5`.  This could easily be added to the `correct` option
* I might need to enhance comment beautification to ensure they are internally padded with a single space

## Actions deliberately avoided, as there are some things that a linter should catch and cause a code author to manually correct
* Not converting `==` and `!=` to `===` and `!==`
* Not inserting getters
* Not inserting parens after assignment to empty constructor calls
* Not wrapping return statement values in parens
* Not inserting `extends` keyword onto classes
* Not remove arguments.callee
* Not remove parens wrapping functions

**Comment by cucumbur** [comment]
<3  exactly what I was looking for

**Comment by prettydiff** [comment]
Just use value *standard* with option *styleguide*.  Enjoy!
