### ISSUE TITLE
Extra line space added to SCSS

### ISSUE THREAD

**Issue by smlombardi** [prettydiff/prettydiff#45]
This sort of code:

````
.ttl {
  margin-bottom: 10px !important;
  .foo {
      color: red;
     }
}
````

beautifies to this:

````
.ttl {
  margin-bottom: 10px !important;
  .foo {
      color: red;
     }

}
````
There is an empty line before the closing bracket. I would rather that not be there or, if anything, add the empty line AFTER the last bracket.

I logged this first with Atom-Beautify and was told to log it here.

Atom 168.0, Atom Beautify 0.21.2, OS 10.10.1

**Comment by austincheney** [comment]
I am having trouble reproducing this bug. I ran the code through the web tool at http://prettydiff.com and it beautified correctly. I have touched this library in 8 days.

**Comment by smlombardi** [comment]
Here's a sample file.  I just tried atom-beautify on it, and it added the extra lines.

http://cl.ly/code/3A1d0q2Z221q/_icons.scss

I couldn't figure out how to configure the online tool for scss and it kept "assuming javascript" so I coulsn't test there.

**Comment by austincheney** [comment]
I am still having trouble reproducing in the latest code. To manually change the language settings scroll down the page to see the options. Look for the third option: "Code type" and change to value "CSS" or "SCSS".

**Comment by austincheney** [comment]
I am going to close this bug for now, but I will keep it in mind and continue to look for it.

**Comment by Glavin001** [comment]
@prettydiff is the prettydiff.com the same beautifier as the Node package?

Also is there a config option that would change this behaviour? I noticed that my unit tests for Atom Beautify using Node's Prettydiff v1.8.8 fails (adds spaces) however doing it manually works as expected. I believe this has something to do with an option, maybe the default has changed, etc. Thanks.

**Comment by prettydiff** [comment]
Yes, prettydiff.com and the npm package "prettydiff" are the same. I provide a version of the prettydiff.com html (http://prettydiff.com/prettydiff.com.xhtml) for local use in the NPM package.  I also recently added a version number to the HTML in addition to the version date.

This gives me some idea of where to look. Reopening issue.

**Comment by Glavin001** [comment]
I recently updated my unit tests for Atom Beautify and I believe this is working in v1.8.8 of Prettydiff. See https://github.com/Glavin001/atom-beautify/commit/a50c5a3c4c884a2eddec7e36c1723eeef97c3758 and note that I removed the newlines and the tests are passing (Travis CI still has other tests failing, but not Prettydiffs). Thank you!
