### ISSUE TITLE
Where should the `.prettydiffrc` file be located for atom-beautify?

### ISSUE THREAD

**Issue by jfletcher-nuxeo** [prettydiff/prettydiff#455]
I've read the documentation and I still don't understand where the `.prettydiffrc` file should be placed:

http://prettydiff.com/guide/prettydiffrc.xhtml

I've placed it in my home folder and it doesn't appear to work.  

```
{
  "inchar": " ",
  "insize": "2",
  "force_attribute": "true",
  "preserve": 2
}
```

What is "the application folder" as mentioned in the docs? If it's something embedded in Atom I don't really want to go messing with the application package.  Thanks!

**Comment by prettydiff** [comment]
Atom Beautify does not use the .prettydiffrc file.  You would have to put the config details into the .jsbeautifyrc file.

**Comment by jfletcher-nuxeo** [comment]
Ah so I can just merge the prettydiff settings with the js-beautify settings?

**Comment by jfletcher-nuxeo** [comment]
Still doesn't seem to be doing anything, this is what I tried:

```
{
  "indent_size": 2,
  "indent_char": " ",
  "html": {
    "wrap_attributes": "force-aligned"
  },
  "inchar": " ",
  "insize": 2,
  "force_attribute": "true",
  "preserve": 2
}
```

**Comment by prettydiff** [comment]
There are some Pretty Diff options that aren't in Atom Beautify yet as Atom Beautify is using an older version of Pretty Diff.  I know force_attribute has been requested in the past, but I need to get the latest version of Pretty Diff in there.
