### ISSUE TITLE
Revise node-local.js

### ISSUE THREAD

**Issue by mukunku** [prettydiff/prettydiff#459]
Hi,

I wanted to report an issue with the **output** parameter when running the utility in node with the **readmethod: file** option.

Here is my command: 
`node PrettyDiff/api/node-local.js mode:"diff" readmethod:"file" source:"C:\Users\myuser\AppData\Local\Temp\tmp22F7.tmp" diff:"C:\Users\myuser\AppData\Local\Temp\tmp2346.tmp" output:"C:\Users\myuser\AppData\Local\Temp\tmpF7B7.tmp" endquietly:"quiet"`

And here is the error output:
```
{ Error: ENOENT: no such file or directory, mkdir 'C:\Projects\MyProjectName\MyRunningDirectory\C:'
    at Error (native)
  errno: -4058,
  code: 'ENOENT',
  syscall: 'mkdir',
  path: 'C:\\Projects\\MyProjectName\\MyRunningDirectory\\C:' }
```

However the file is succesfully created anyway. 

Also is there a way to adjust the suffix or will it always append the **-diff.html** to the file?

**Comment by prettydiff** [comment]
That is certainly strange.  I will investigate soon.

**Comment by prettydiff** [comment]
The logic in node-local.js is old.  I have written logic to accomplish similar goals in a side project named biddle last year that is faster, fewer instructions, and far more stable.

I need to rewrite this file from scratch to integrate many of the file and path handling capabilities I have written for biddle.

**Comment by prettydiff** [comment]
Pretty Diff no longer uses such a file or convention.  This is all solved by a clean build system that results in a powerful command line utility with really clear instructions and a far more sane logic/flow control.
