### ISSUE TITLE
[Question] Displaying diff output in another format than HTML?

### ISSUE THREAD

**Issue by damien-monni** [prettydiff/prettydiff#461]
I am using the Pretty Diff to compare 2 strings this way:

    prettydiff({
      source: 'toto',
      diff: 'titi',
      lang: 'text',
    })

If I console.log the output, I get an HTML string diplaying the result:

    <p><strong>Number of differences:</strong> <em>2</em> difference from <em>1</em> line of code.</p><div class='diff'><div class='diff-left'><h3 class='texttitle'>Base Sample</h3><ol class='count'><li>1</li></ol><ol class="data" data-prettydiff-ignore="true"><li class="replace">t<em>o</em>t<em>o</em>&#10;</li></ol></div><div class='diff-right'><h3 class='texttitle'>New Sample</h3><ol class='count' style='cursor:w-resize'><li>1</li></ol><ol class="data" data-prettydiff-ignore="true"><li class="replace">t<em>i</em>t<em>i</em>&#10;</li></ol></div><p class="author">Diff view written by <a href="http://prettydiff.com/">Pretty Diff</a>.</p></div>

Is there a way to have a different output, maybe in JSON, so I can use the result in my code algorithm instead of just displaying it (which is not what I want)?

**Comment by prettydiff** [comment]
Your request is absolutely necessary.  I have started thinking about this in issue #454 

I am just starting the planning now, but this will be a feature of Pretty Diff 3.

**Comment by damien-monni** [comment]
Great! Have you an idea about a release date? Just to know if I have to search for another library for my current project or if I can wait.

**Comment by prettydiff** [comment]
Unfortunately, I don't have a release date just yet.  This will be an ambitious initiative.  I have started recording my thoughts here: https://github.com/prettydiff/prettydiff/issues/462

**Comment by damien-monni** [comment]
Thanks for your reply. :)

**Comment by prettydiff** [comment]
Merging this issue into #454
