### ISSUE TITLE
Pretty Diff 3 roadmap

### ISSUE THREAD

**Issue by prettydiff** [prettydiff/prettydiff#462]
# Pretty Diff 3 is coming

## Current technical objectives
* #459 - Rewrite api/node-local.js file to take advantage of smaller, faster, more precise logic from side project, biddle
* #458 - Consolidate the application back into a single file.  The two api files will remain separate, but everything else will be consolidated into a single massive monster file.  To make this less intimidating I will be externalizing things upon request:
   - I will provide a convention so that any function can be exposed by name.  If you want a parser just ask the application for it by name and it will expose what you need.
   - Expose any array that comprised part of a parse table.  This stuff should be available at any time without having to dive into the code.
   - Options settings and values should be exposed as a JSON object upon request so that if something is acting strange anybody can see if it is the result of settings versus an application failure
* Although Pretty Diff will be served as a single application file. The ability to export functions must allow for a write or import method so that these exported function can be overwritten with modifications.  This is essential because I want to rip the parsers out and host them as a separate independent git repository to start a universal parsing framework.  For more information see https://github.com/Unibeautify/unibeautify/issues/8#issuecomment-310282589
* #454 - Provide a single standard option to define output format that works across all features of the entire project
* Revise the UI on the webtool.  I am happy with the UI until you get to the options at which point it is atrocious.  There will not be options per mode, but only a single set of options that will be available per request with appropriate documentation

## NPM and Unibeautify
I am considering putting Pretty Diff back into NPM once this milestone is completed.  NPM is faster now, more stable, and they have introduced hashing for integrity.  There instability around package.json files with regard to redistribution still seems present, the computation around the NPM download counts remains unclear, and I still think the package namespace is a bottleneck with consequences beyond distribution problems.  My primary motivation is to move the unibeautify project forward.

My biggest concern with NPM, looking forward though, is that a package cannot be published in various forms or limitations.  Pretty Diff, for example is a big project, with a weight around 24mb.  All the logic to run the application from the command line is only about 1.1mb.  I have users who wish to play around with the options on the webtool that runs in a browser.  I have users that want to run the unit tests to verify stability or hack around the code.  I have users that want to run the bare minimum code on the command line for integration or bundling with other applications.  I cannot make them all happy with NPM unless I replicate the project on my side and publish as various different packages.  This is a huge pain the ass could be easily configured in the package.json file.

## Tentative plan
1. Rewrite api/node-local.js.  This work will be less intimidating than #458 and can occur in a vacuum.
2. Integrate the lib/options.js into the prettydiff.js file first.  Options handling is foundation of the application's architecture and all further organizational decisions must draw from that foundation.
3. Integrate the actual language parsers into the prettydiff.js file at the same time.  The largest challenge will be resource sharing (closures) while simultaneously accounting for inter-parser recursion like JSX.
4. Step by step integrate all supporting logic for beautification, code formatting, analysis and so forth
5. Account for output formats and write unit tests for this in support of #454 
6. Validate application and project health
7. Add logic to expose all functions by request and as much internal data and settings as possible
8. Removing current options support from the web tool and rebuild this for uniformity and simplicity
9. Evaluate steps for getting Pretty Diff into NPM as various different packages

**Comment by Glavin001** [comment]
Any chance we could try Pretty Diff v2 (current?) on npm and work with it to reduce problems and answer questions in preparation for v3? Also means current Atom-Beautify users could benefit.

**Comment by prettydiff** [comment]
Yeah, I will look at that.

**Comment by prettydiff** [comment]
NPM (latest version) is failing to publish for me on Windows.  I will try again from OSX later.

**Comment by prettydiff** [comment]
Done https://www.npmjs.com/package/prettydiff2

**Comment by Glavin001** [comment]
Awesome! A new PR to replace https://github.com/Glavin001/atom-beautify/pull/1672 can now be done for Atom-Beautify to use https://www.npmjs.com/package/prettydiff2 instead. 😃

**Comment by prettydiff** [comment]
Please see #511 for status updates on version 3 work.
