### ISSUE TITLE
DustJS tags containing interpolated variables aren't parsed properly

### ISSUE THREAD

**Issue by BennyH26** [prettydiff/prettydiff#465]
DustJS allows interpolated values within tags. For example:

`<li class="{@eq key="myKey" value="{url}"}active expanded{:else}inactive{/eq}">`

The above is valid DustJS, but prettydiff does not play well with the embedded {url} variable.

Is there any way to correc this?

**Comment by prettydiff** [comment]
I think the trouble is the quotes more than the attribute value.  This seems to work for me:

`<li class="{@eq key='myKey' value='{url}'}active expanded{:else}inactive{/eq}">`

**Comment by BennyH26** [comment]
DustJS will not compile that line for me with single quotes enclosing parameter values, unfortunately.

**Comment by prettydiff** [comment]
Frustrating...  The only way to solve that would be to recognize that `"{@ + tagname` is a tag as an attribute that gets parsed separately until a terminal delimiter is reached: `{/ + tagname + }"`.

I will look into this.

**Comment by BennyH26** [comment]
prettydiff is an UNBELIEVABLY impressive and complex package. Can't thank you enough for looking into this issue!

**Comment by BennyH26** [comment]
Thank you!! 🙏🏼
