### ISSUE TITLE
Text Difference not getting highlighted in prettyDiff

### ISSUE THREAD

**Issue by Udayk2205** [prettydiff/prettydiff#469]
var api ={
     mode        : "diff",
     context     : 3,
     lang        : "javascript"
 };
api.source = data.data.fromContent;
      api.diff = data.data.toContent;
      api.sourcelabel = data.config.data.fromInternalVersion;
      api.difflabel = data.config.data.toInternalVersion;
      var diffResult = prettydiff(api);
      return diffResult;

In above function i am comparing two json objects,diff has been showing properly side by side,but difference is not getting highlighting.

But when i am comparing in http://prettydiff.com/
in this site the differences is properly getting highlighting.

Is this any further step i need to do so that differences will get highlighted.

Thanks

**Comment by prettydiff** [comment]
Are you running the application with Node?  In order to debug this I will need to produce the problem.  Can you provide text values that you are trying to compare?

**Comment by Udayk2205** [comment]
No i am not using Node. We have one web-app where we have used prettydiff.js file and placed it under our web app application directory and referring from javascript file. I have attached snapshot where you can see there is difference in line number 27 and 28 but it is not highlighting the difference.

I have also attached the prettyDiff.js file . I can see it is going into the 
**function charcomp = function diffview__report_charcomp(c, d)**
but it's not highlighting the difference.
[prettydiff_1.zip](https://github.com/prettydiff/prettydiff/files/1156505/prettydiff_1.zip)


![prettydiff](https://user-images.githubusercontent.com/26274440/28326950-c153398a-6bff-11e7-8040-1dca9d5a66db.jpeg)

**Comment by prettydiff** [comment]
It looks like the JavaScript is writing the HTML correctly, but the CSS is missing.  The highlighting colors come from CSS code.  To verify if it is actually there right click where the text should be highlighted and see if there is an *em* tag inside the table cell.

https://github.com/prettydiff/prettydiff/tree/master/css

At a minimum you will want these files:

* global
* reports
* color_white

**Comment by Udayk2205** [comment]
Hello Austin,
Sorry i am little late to reply. But thank you so much for your prompt reply and guidance to sort out this issue.

Yes, you are correct it's actually a css problem. I didn't added the css file which you have recommended, but i have modified the existing css file which were using in our project. It looks like there were no 
back-ground color defined ,after defining the bg color it worked.

Regards,
Uday

**Comment by prettydiff** [comment]
Awesome, I am glad to hear it is resolved!  Just open an issue any time you run into further roadblocks.
