### ISSUE TITLE
output bad code

### ISSUE THREAD

**Issue by da0ka** [prettydiff/prettydiff#470]
I tested minify below code. but output is bad code.
`if(a)for(;a;);else b` -> `if(a){for(;a;){};else{b}}`
`do do do;while(0);while(0);while(0)` -> `do{do{do{};while(0)}}while(0);while(0){`

**Comment by prettydiff** [comment]
Thanks.  You have found a major defect with the curly brace insertion algorithm.

**Comment by prettydiff** [comment]
What is `->` I am not aware of that operator in JavaScript?

**Comment by prettydiff** [comment]
In the first sample if I insert anything between the `)` and `;` it works.  This is a weird edge condition and I will add a rule to solve for it.

In the second code sample appears to be a compound problem.  Part of it is the semicolon terminating an unexpected empty statement as in the previous code sample.  After that it is having trouble associating a nested `while` to the appropriate `do` block.  I am looking at this.

**Comment by prettydiff** [comment]
Fixed on my local and I cannot push to git from my office.  I will publish tonight.
