### ISSUE TITLE
Line Number doesn't starts with 1 and Number of Differences is also showing in correct data

### ISSUE THREAD

**Issue by Udayk2205** [prettydiff/prettydiff#471]
Hi,

I am trying to compare two json objects where prettydiff shows the exact differences but the line number it was rendering is not correct. i am having two json object which i am trying to comapre which is of total 10 lines, but prettydiff calculate and render the line number from 31. Ideally it should start with 1.

![prettydiff_lnumber](https://user-images.githubusercontent.com/26274440/28837030-ef240268-7708-11e7-9ca9-e1d9262720b8.png)
I have attached the image of pretty diff and also the json object which i am trying to compare.
As you can see in the image i have attached it starts with 31 ,but when you see the json_content.txt file the content difference is in line number 6.

I have also added the prettydiff.js file which i am using in my project.
[prettydiff.zip](https://github.com/prettydiff/prettydiff/files/1191384/prettydiff.zip)

**Also when you see in the last line number of differences it shows 8 differences from 3 lines of code, but there is difference of 2 lines and also not able to identify the 8 differences.**

[Json_Content.txt](https://github.com/prettydiff/prettydiff/files/1191351/Json_Content.txt)

Let me know if anything not clear or you need further more information.

Thank you for help and guidance.

**Comment by prettydiff** [comment]
I have no idea.  I cannot seem to reproduce this defect in the latest version.  I looked at the prettydiff.js code file you are using and it is ancient.  It looks like it was last updated about 4 years ago.  I would recommend just grabbing the latest code from Github.
