### ISSUE TITLE
JSX: Inline If with Logical && Operator does not format properly

### ISSUE THREAD

**Issue by ksb86** [prettydiff/prettydiff#473]
# Description

The result of the beautification is not correct.

# Input Before Beautification

This is what the code looked like before:

```
class Test extends React.Component {
render() {
return (
<div>
{this.props.user && <span>
{this.props.user.displayname}
</span>
}
</div>
)
}
}

```

# Expected Output

The beautified code should have looked like this:

```
class Test extends React.Component {
    render() {
        return (
            <div>
                {this.props.user &&
                    <span>
                        {this.props.user.displayname}
                    </span>
                }
            </div>
        )
    }
}
```

# Actual Output

The beautified code actually looked like this:

```
class Test extends React.Component {
    render() {
        return (
            <div>
                {this.props.user && <span>
                    {this.props.user.displayname}
                </span>
}
            </div>
        )
    }
}
```

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

# Debug

Here is a link to the `debug.md` Gist: https://gist.github.com/ksb86/b9f72702086ffea09e04043b2ba7bbed

# Checklist

I have:
- [x] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [x] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [X] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

**Comment by ksb86** [comment]
originally submitted here: https://github.com/Glavin001/atom-beautify/issues/1814

**Comment by prettydiff** [comment]
Excellent.  I cannot say how fast I will solve this in Atom Beautify.  At the moment I am focusing all my energy on this project: https://github.com/Unibeautify/parse-framework

That Parse Framework project will power Pretty Diff 3 and likely the next major version of JS Beautify.  There has been some interest from Prettier on this as well.  I just need to get it done.

**Comment by ksb86** [comment]
Ok cool. Thanks for responding!

**Comment by RowgerGo** [comment]
How did you solve it?
