### ISSUE TITLE
Prettydiff not found issue while using in local

### ISSUE THREAD

**Issue by sanjaykumar2763** [prettydiff/prettydiff#474]
Hi, i'm trying to use prettydiff in local to show prettified json/xml response from a service call.
i have added the library files this way

    <script src="prettydiff_2.2.1/lib/global.js"></script>
    <script src="prettydiff_2.2.1/lib/csspretty.js"></script>
    <script src="prettydiff_2.2.1/lib/csvpretty.js"></script>
    <script src="prettydiff_2.2.1/lib/diffview.js"></script>
    <script src="prettydiff_2.2.1/lib/finalFile.js"></script>
    <script src="prettydiff_2.2.1/lib/jspretty.js"></script>
    <script src="prettydiff_2.2.1/lib/language.js"></script>
    <script src="prettydiff_2.2.1/lib/markuppretty.js"></script>
    <script src="prettydiff_2.2.1/lib/options.js"></script>
    <script src="prettydiff_2.2.1/lib/safeSort.js"></script>
    <script src="prettydiff_2.2.1/prettydiff.js"></script>

But getting "ReferenceError: prettydiff is not defined" error.
Can you please help with this.

**Comment by prettydiff** [comment]
Here is how I am doing it in the HTML: 
 https://github.com/prettydiff/prettydiff/blob/master/index.xhtml#L2289-L2301

Try referencing the function as `global.prettydiff.prettydiff`

**Comment by sanjaykumar2763** [comment]
Thank you for the response. Now the error is gone and the function call is happening. I have added dom.js also but it is throwing this error "Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document."

I have removed "dom.js" and the error is gone.

But now, i'm getting this error "**options.source is empty!**".
This is my code
`console.log(data.response.data);`
`var options = {`
`     source: data.response.data,`
`     mode: "beautify",`
`     lang: "auto",`
`     inchar: "\t",`
`     insize: 1`
`};`
`console.log(options.source);`
`var pd = global.prettydiff.prettydiff(options);`
`$scope.responseData = pd[0];`

console.log is printing the expected result in two places. But still saying options.source is empty. Can you please tell me how to resolve this?

**Comment by prettydiff** [comment]
The localStorage error is generated by Chrome if you are accessing the tool in a browser via the *file:///* scheme.  Your options are using a different browser or using a local webserver and accessing the tool in chrome using localhost as your domain.

A quick http server for node is available at https://github.com/Unibeautify/parse-framework/blob/tests/runtimes/httpserver.js

**Comment by sanjaykumar2763** [comment]
But i have run the barebones.xhtml. It is working totally fine. That is also running in the same environment i.e in local with no server. Code is also same. Any other configuration needed?

**Comment by prettydiff** [comment]
I don't believe the barebones pages make use of localStorage.

> console.log is printing the expected result in two places. But still saying options.source is empty. Can you please tell me how to resolve this?

As for that I am not sure.  This could very well be a defect in Pretty Diff.  You would have to step through the prettydiff.js file to see where it is getting dropped.  I recommend starting in here: https://github.com/prettydiff/prettydiff/blob/master/prettydiff.js#L210-L239

**Comment by sanjaykumar2763** [comment]
Problem solved. I have set the source as JSON.stringify(object). Now it is working as expected.
Can you please tell me how can i use the beautifier. I'm unable to find it in documentation

**Comment by prettydiff** [comment]
In your options set `mode` to `beautify`

**Comment by sanjaykumar2763** [comment]
Ya i have set that option. But still i'm not getting the output in colors.

**Comment by prettydiff** [comment]
This application doesn't do colors.

**Comment by vietnguyen09** [comment]
I have this issue and can't found anyway to make it work.

**Comment by prettydiff** [comment]
@vietnguyen09 Could you describe the exact error message you are getting?  There were a couple of different problems explored in this issue.
