### ISSUE TITLE
velocity beautify issue: self-closeing tag was wrongly beautified

### ISSUE THREAD

**Issue by luqimin** [prettydiff/prettydiff#479]
With node-local.js, and the result just like #16 

And my option is `{
                source: _data,
                mode: "beautify",
                lang: "velocity",
                spaceclose: true
            }`

**Comment by prettydiff** [comment]
Would you be able to paste in the line of code in which this problem occurred?  I want to ensure I am accurately addressing your concern.

**Comment by luqimin** [comment]
thankyou for your attention 

as blow:
source: 
```
<div>
<input type="text">
<input type="text">
<input type="text">
</div>
```

and result: 
```
<div>
    <input type="text">
        <input type="text">
            <input type="text"></div>
```

and if the `<input>` tag end with `/>`, the beautify result would be correct.

this will also happen when beautify `<meta>`, `<link>`...

**Comment by prettydiff** [comment]
It looks like this is resolved, for me, if the option **html** is set to true.  Does changing this option resolve the problem for you?

**Comment by luqimin** [comment]
yes, that really work! thanks
