### ISSUE TITLE
Do not compare JSON differences correctly in React app

### ISSUE THREAD

**Issue by birmjin10000** [prettydiff/prettydiff#480]
In "http://prettydiff.com/" demo website, comparing JSON shows correct delta. It compares JSONs based on its keys. So even if the order of keys in 2 JSONs are different, it still shows the difference correctly. Put simply, {"a":1, "b":2} is the same as {"b":2, "a":1}.

But, when I did same thing in my React app, it treats JSONs as text. So ordering of keys in JSON affect the delta. In other words, {"a":1, "b":2} is not the same as {"b":2, "a":1}.
I installed prettydiff2 from NPM.

Version from NPM is different from the one on "http://prettydiff.com/" site ?

**Comment by prettydiff** [comment]
Try specifying these options:

* `lang = "json"`
* `objsort = "all"`

**Comment by birmjin10000** [comment]
Thanks! It works.
