### ISSUE TITLE
beautify css adds bad space in less-css syntax: @{class}text {}

### ISSUE THREAD

**Issue by conbracoweb** [prettydiff/prettydiff#481]
@{class}text {} converts to @{class} text {} when my CSS less file gets beautified.  There is an extra space that gets added between the '}' and 'text' which changes the CSS ruleset when rendered in CSS.

**Comment by prettydiff** [comment]
This issue is not present in Pretty Diff 3 due to updated parsing rules in https://github.com/unibeautify/parse-framework
