### ISSUE TITLE
use prettydiff in the browser with require js

### ISSUE THREAD

**Issue by JenneyJ** [prettydiff/prettydiff#482]
HI

I need to use the pretty diff in the browser (AMD)  therefore I use browserfiy 
I did npm install prettydiff -s  and run  the following command

`browserify --standalone someName prettydiff>prettydiff.js  | uglifyjs > bundle.js`

but it’s not working  I got sort file …any idea what could be missing ?

**Comment by prettydiff** [comment]
There is a closed issue about this that was probably never properly resolved: https://github.com/prettydiff/prettydiff/issues/435

Go ahead and look through that other issue and see if that gets you closer to a resolution.  I don't really use require.js myself, so there is probably something I missing on how I am pulling the various files together.

**Comment by prettydiff** [comment]
I am closing this.  I am going to keep with old school vanilla JavaScript approaches.  The application can be included into HTML using HTML script tags or by integrating the Pretty Diff application into your application's build system.

Pretty Diff integrates JavaScript into its webtool HTML using these files:

1. prettydiff/node_modules/parse-framework/js/browser.js
1. prettydiff/js/dom.js

To integrate the Pretty Diff into other HTML use these files instead:

1. prettydiff/node_modules/parse-framework/js/browser.js
1. prettydiff/js/prettydiff.js

The `prettydiff.js` is a vanilla JS function with no dependencies and is completely environment agnostic.  The `browse.js` file contains a single binding the to the browser's `window` object.
