### ISSUE TITLE
Django pipe spaces

### ISSUE THREAD

**Issue by prettydiff** [prettydiff/prettydiff#486]
https://github.com/Glavin001/atom-beautify/issues/321#issuecomment-317775255

Makes this:

    {% if author == request|author_from_request %}

into this:

    {% if author == request | author_from_request %}

**Comment by Zack-83** [comment]
Just a short addition: it also happens with common filters, like `|length`, which becomes --> ` | length` (unreader for a parser).

**Comment by prettydiff** [comment]
Thanks @Zack-83

**Comment by luca-rath** [comment]
Same for twig.

**Comment by prettydiff** [comment]
It looks I have fixed this in the recent slew of updates over the past few days.
