### ISSUE TITLE
Any chance on a Visual Studio Code version?

### ISSUE THREAD

**Issue by bgarrant** [prettydiff/prettydiff#492]
Is there any chance on a prettydiff official extension for visual studio code?  I see someone tried (https://marketplace.visualstudio.com/items?itemName=HexcodeTechnologies.vscode-prettydiff) it but it does not work with .twig.  It is removing the line breaks and also adding a line break before periods.

https://github.com/Microsoft/vscode/issues/37514

**Comment by bgarrant** [comment]
If I use the extension at https://marketplace.visualstudio.com/items?itemName=HexcodeTechnologies.vscode-prettydiff, it is doing this:

original code
```
                                {% if block.headerCaption | length %}
                                    <h2>{{ block.headerCaption }}</h2>
                                {% endif %}
                                {% if block.headerLink | length %}
                                    {% set asset2 = block.headerLink.first() %}
                                    <h2>
                                    <a class="text-warning" href="{{ asset2.url }}">Read More
                                        <i aria-hidden="true" class="fa fa-arrow-right"></i>
                                    </a>
                                    </h2>
                                {% endif %}
```

after Prettydiff
```
                                {% if block.headerCaption | length %}
                                    <h2>{{ block.headerCaption }}</h2>
                                {% endif %}
                                {% if block.headerLink | length %}
                                    {% set asset2 = block
                                        .headerLink
                                        .first() %}
                                    <h2>
                                        <a class="text-warning" href="{{ asset2.url }}">Read More
                                            <i aria-hidden="true" class="fa fa-arrow-right"></i>
                                        </a>
                                    </h2>
                                {% endif %}
```

I cant figure out why it is doing this?

```
                                    {% set asset2 = block
                                        .headerLink
                                        .first() %}
```

**Comment by bgarrant** [comment]
That extension just does not work.  Any chance on an official VS Code version?

**Comment by prettydiff** [comment]
Actually, yes, but it is a little ways off.  I am working this through the Unibeautify project: https://github.com/Unibeautify/

**Comment by bgarrant** [comment]
That sounds great!  There are a lot of CMSs using twig and VS Code has no twig formatter.  I know a lot of people looking for it.  Can't wait to see Unibeautifier for VSC!

**Comment by prettydiff** [comment]
You could help by writing a rough draft of a VS Code interface for the project.  I have no idea what this should look like or how it should work, but there is no work done on this yet.

I need to update Pretty Diff to version 3 in order to make it compatible, and am starting on this effort today.

**Comment by bgarrant** [comment]
Basically most settings go in a settings.json file in VSC to customize the extensions.  The whole process of making extensions is detailed out here https://code.visualstudio.com/docs/extensions/overview.  That is about all I know in that regards.

**Comment by mblode** [comment]
Here is the extension I am working on now to get PrettyDiff working with VSCode: https://marketplace.visualstudio.com/items?itemName=mblode.twig-language

**Comment by prettydiff** [comment]
Awesome @mblode

**Comment by Grv-Singh** [comment]
I was new to everything here, yet I managed to install prettydiff and mblode's extension for twig in VSCode. How to make it work, does it automatically beautify twig files or is there a shortcut for that?

**Comment by mblode** [comment]
Here is my new PrettyDiff 3 extension: https://marketplace.visualstudio.com/items?itemName=mblode.pretty-formatter
