### ISSUE TITLE
Lowercasing on Beautify

### ISSUE THREAD

**Issue by n-for-all** [prettydiff/prettydiff#493]
i am using this plugin as a beautifier for twig templates on atom editor, whenever i beautify it transform the html tags to lowercase ex `<App>` becomes `<app>` on beautify, is this the default behaviour and how can i disable such behaviour?

**Comment by prettydiff** [comment]
I just looked at this and I can reproduce the defect.

## Backstory

For HTML based languages I intentionally convert all tag names to lowercase.  HTML is case insensitive and this keeps everything uniform.  For XML based languages I do not alter tag names as XML is case sensitive.  I am processing Twig as though it is an extension of HTML: https://github.com/prettydiff/prettydiff/blob/master/lib/language.js#L37 .

This is an easy fix.  I could just change that value to `"xml"` and it is fixed.  But before I do that how are custom tags used in Twig?  I thought Twig grammars were defined using `{%` delimiters.

**Comment by n-for-all** [comment]
`{% extends "base.html.twig" %}

{% block title %}Title{% endblock %}
{% block head %}
    <link rel="stylesheet" href="css/style.css"/>
{% endblock %}
{% block content %}
    {% set languages = language.getLanguages() %}
    <div class="mdl-grid">
        <div class="mdl-cell mdl-cell--8-col mdl-cell--2-offset">
            <UiFilter data='{{filter | json_encode | raw }}'></UiFilter>
            <UiGraph languages='{{languages | json_encode | raw}}'></UiGraph>
        </div>
    </div>
{% endblock %}
`

this is a sample twig template using UiFilter and UiGraph as react components, the best is to keep the uppercase notation because it is much more readable and the casing doesn't effect the dom, so why not.

**Comment by prettydiff** [comment]
Hummmmm.  I never considered extending JSX with templating schemes.  In this case I will probably just make the simple change of interpreting Twig code as XML instead of HTML just to play it safe.

**Comment by mblode** [comment]
Have you implemented this fix? I am working on a Pretty Diff VSCode extension for Twig and this issue is breaking all of my Twig documents.

**Comment by mblode** [comment]
Is there anything I can do in the options or some type of quick fix in the PrettyDiff library?

**Comment by prettydiff** [comment]
The fix is not implemented yet.

**Comment by prettydiff** [comment]
I think I have this fixed right now, but I will verify with additional testing later tonight.  When working similar issues in the code yesterday I believe only "html" language gets the lowercase treatment where I am labeling the template code more specifically.  I don't always get the names right when auto-detecting template languages apart from each other, but I am not calling them *html* anymore which fixes this issue.

**Comment by prettydiff** [comment]
I am marking this as fixed and moving on.  If I am wrong please open an issue with a quick code sample so I can address this and have a good unit test.
