### ISSUE TITLE
inline property changed in JSX

### ISSUE THREAD

**Issue by jansohn** [prettydiff/prettydiff#494]
Pretty diff changes the `inline` property in my `JSX` to `inline="inline"`. It is not supposed to do that, right? Here's the complete debug gist:
https://gist.github.com/jansohn/8117ace4745c2446d9e6fa7b1d7f4882

**Original vs. Beautified Diff**: 
```jsx
Index: C:\Users\xyz\workspace\react-app\src\App.js
===================================================================
--- C:\Users\xyz\workspace\react-app\src\App.js	original
+++ C:\Users\xyz\workspace\react-app\src\App.js	beautified
@@ -2,17 +2,15 @@
 import {FormGroup, Radio} from 'react-bootstrap';
 
 class App extends React.Component {
   render() {
-    return (
-      <div>
-          <FormGroup>
-            <Radio name="inlineRadio" value="true" inline>yes</Radio>
-            {' '}
-            <Radio name="inlineRadio" value="false" inline>no</Radio>
-          </FormGroup>
-      </div>
-    );
+    return (<div>
+      <FormGroup>
+        <Radio name="inlineRadio" value="true" inline="inline">yes</Radio>
+        {' '}
+        <Radio name="inlineRadio" value="false" inline="inline">no</Radio>
+      </FormGroup>
+    </div>);
   }
 }
 
 export default App;

```

**Comment by prettydiff** [comment]
Is this breaking your code when it is compiled by React?  If not then this isn't a defect.

The markup islands that exist in JSX are XML compatible syntax, according to the JSX spec.  Valueless attributes are a syntax extended feature of HTML not supported by XML, though this is likely handled by JSX regardless.

**Comment by jansohn** [comment]
It produces a warning in the web console:

    Warning: Failed prop type: Invalid prop `inline` of type `string` supplied to `Radio`, expected `boolean`.
    in Radio (at App.js:8)
    in App (at index.js:5)

**Comment by derwaldgeist** [comment]
This is actually breaking code, if the receiving component defines the property to be of type `boolean`, using PropTypes. If it is handed over as `inline="inline"` it becomes a `string` instead. This is default JSX behaviour.

If I try to set `inline={true}`, it at least breaks my linter (which in fact breaks code compilation in my case, as my webpack scaffold throw an error if linting fails).
