### ISSUE TITLE
Comment is breaking code inside parenthesis

### ISSUE THREAD

**Issue by prettydiff** [prettydiff/prettydiff#496]
https://github.com/Glavin001/atom-beautify/issues/1920#issuecomment-341664823

```javascript
if (participant.user === currentUserId || // ... to the user himself
    participant.observing // ... to participants who are currently observing the conversation
    ) {
      continue;
    }
```

becomes

```javascript
if (participant.user === currentUserId || // ... to the user himself
    participant.observing // ... to participants who are currently observing the conversation) {
      continue;
    }
```

The closing parenthesis becomes part of the comment and thus break's the user's code.  I thinking this is a beautification defect and not a parsing defect.

**Comment by shinepd** [comment]
Will you be updating the placement of tags in return statements as well? I tried replicating the issue stated at the top of https://github.com/Glavin001/atom-beautify/issues/1920 on prettydiff.com, though my code formatted as expected on the site. Is the site not on 0.30.6 yet?

**Comment by prettydiff** [comment]
This issue only involves line comments.  Line comments **must** terminate with a new line character otherwise code will break.

Pretty Diff 2 is in maintenance mode right now while I am adapting the code base to fit new requirements for Pretty Diff 3 and Unibeautify
