### ISSUE TITLE
Raw output

### ISSUE THREAD

**Issue by tomitrescak** [prettydiff/prettydiff#50]
Hi, can your tool produce raw output like in the form of Git?
I need to store deltas in the database and your output is rather verbose.
If not, would you be please so kind and point me towards the possible tool?
I need output like:

+ ... changed
- changed

Thanks!

**Comment by prettydiff** [comment]
By raw output I am thinking you mean performing a code comparison without language parsing. If my assumption is correct try changing the language setting to "Plain Text". If you are using the tool in a browser scroll down just a bit make the options appear and it will be the third option labeled "Code Type".

Please let me know if I completely misunderstand the concern.

**Comment by prettydiff** [comment]
Sorry, I completely misunderstood. This tool can process raw output that is not an HTML table of differences. So far the raw output is only available using the Node.js (io.js) API.

http://prettydiff.com/guide/diffcli.xhtml

This will work when comparing files, a directory of files, or even directory trees. Let me know if this is still not what you are looking for.

**Comment by tomitrescak** [comment]
Thanks for your comments, in the end I wrote my own parser that uses the `difflib.js` library and outputs result in the form:

```
+ (1,) Change 1
- (,4) Change 2
```

I needed it only to keep deltas in the database.

**Comment by prettydiff** [comment]
Cool. If you are only interested in indicating lines where changes occurred and not the characters on those lines you might look into removing the "charcomp" function. This will vastly improve the speed of the application.

**Comment by tomitrescak** [comment]
Wow, thanks for your help! It really made miracles;)

**Comment by prettydiff** [comment]
No problem. If you need additional features please open a new issue and I will work it in.
