### ISSUE TITLE
Twig formatting expands `checked` to `checked="checked"`

### ISSUE THREAD

**Issue by mblode** [prettydiff/prettydiff#502]
I have found an issue which is present in my VSCode Twig Language extension along with Atom-Beautify. 

If I have some Twig code: 
```
<div class="orbit" value="{{ siteName }}" {% if loop.first %}checked{% endif %} data-orbit></div>
```

It will be beautified to:

```
<div class="orbit" value="{{ siteName }}" {% if loop.first %} checked{% endif %}="checked{% endif %}" data-orbit="data-orbit"></div>
```

### Quick fix:
One quick fix is to add a space after "checked" and it will not break the output but then it expands the tags.

### Permanent fix?
Is there any way to fix this issue or to tell PrettyDiff not to expand those kinds of attributes?`unformatted: true` fixes this but then makes all of the text in the document lowercase which breaks the template.

Thanks for your awesome work!

**Comment by Glavin001** [comment]
I have also experienced with with TSX (TypeScript + JSX). It completely breaks the code since the interface is now incorrect.

```diff
-                  <Route exact path="/" component={Home} />
+                  <Route exact="exact" path="/" component={Home} />		
```

**Comment by jimblue** [comment]
Hi there!

Any input / update / fix about this issue?

**Comment by prettydiff** [comment]
The issue is valid, but I have not resolved it yet.  I plan to resolve this before the end of the month.  All current work is occurring in the 3.0.0 branch of this repository.  The work is taking a while as I convert this project into TypeScript and more modern code.  It is basically a rewrite from scratch.

**Comment by jimblue** [comment]
@prettydiff alright good luck then and thank you so much !

**Comment by Glavin001** [comment]
Reproducing JSX: https://playground.unibeautify.com/#N4IgNghgdg5grhGBTAchAtkkAuEApAZQA0QAaEAewAcAXASwqgGcdQBhAYlZACMkI49AGZ0kAJxbYA2iAAKYpDRoBPAAQAROkKEgAugF9ybAgW58Bw0RJwz5ilRq07ydpVbL4CAWgBC-QVrKeoYgxgBqZv6W4pK2CkpqmtrBRhRgACYAYnBMDFCRFlpWsXLxDkk6BuQAooQFASIxNqX2iU4ehL5RgSkgAOJiEFQAFgCKADL10dbSLW7ivQASACoAspPYoOYNxc2u5e3knX6FQkFVICvrANTVAEo+U0VNs-ttyReL0OlgSDwQMy23UaMzirUcySO3hODXOIUIAHkUE8QSU3hDnHN6AsoV1TnCoSRNrxgbtXmV3pVyHQoOkkFAaAB9ADudBow0ZNAgPEkNDEcCQ1Np9KZAGNhgCcCBVB4aXSGYzcgAvLDYAAs5CoCiY4gAbkhGVAkMywDSkLz+YKQEaTWbGXwaMykPTGfzfhaBUL5WKKOhMAyPVahBQxKKDXKRRB6IwcEIIGAdeQAI5wCg0c1SqCMLDkeN0GBQRkQJi5Av+miSOMJq3MwZURmmo0N+kwdk4AAcAAZyEwqBAw0WhOmxEWs4WhHAoKLo-lsFXE9aKM2IOkaTBGSqxBRY-GF-T0iy2RzRb70BAd9XyDwFBAANaM8UQM0HzDsijpSu7q3oOBgeiNg1hygAEglweNmQgZQWFzMQt2ZRk+wUZgpXAyDoMoHgACskGnB84DEMBlEVPtRTXHA+U9EAtUQM9GRpHUxBoC8F0wpgAA97UGUVb0UT9LyowYYFohQUzoBRmKtfdD3ZRUkHQOgTzAGM5y-cgFHQCh9U5QY6EbddmWGNlzRI1V5yta9+wNJgVF+KVFMgKgdQ8ScIwVR9n0ZV9hnfPiFzPDitXNPUDRtADJAARm7EBe0sujC0Q+kJJ7Ey4sZOTaCIhLZzM8hWMbJkJSoKhQJykAeKQesAUGIjXK5GckuilK+GDBQH0YVcZ3jcjLXISdzVFIYrL5NdfMk2lpI5UKzQak8-QgRkRAkJiVOreEIF1c9iW2aY0QpDFejwdaIAIUUxDoWgUTJMEEn23QvRFCbOW5QN7rciUxClGVXqZZVVQ1ASgrELSpqNF7rWNAD7UUJ0XTdDNsAoq1arav0RTBlqB1qqM8galM03hxcjQ8PMCyLEt8ygctRvIWshgbO1flgNtsC7ZLYogIdxFHRgFsnaccZWhcs2XVdYA3cRt0FsaD1ZGTZrPBrr34e93KNF9FG8j8Gp-P9dLtICQJQsAIKg4nYIoeCsskEBUNN8gKCwnCxXwwjiP7MiEZ6gSaPm+jxGW0rWI4izuN4hrqKE+aRLgMTTNUkApNljkdXkxTlNK9TNMAnS9JZQz0xisNFa4oblFs3B7KGJzeqgZHVaQdW3y1qXyH8hDtWCw0IbNCKosL8N4oBRKW8a2KaTS9AMoQofsvjvKaQKoZioa8rKtgyC4u9bH0-j-uoZag0T1pNk8i6z3KL6pgBqoIaztgamE-GpOu9tImR-l+bFusiSQnGc1JCBKcK6WJKQeH2O4C44w6CiXSJdF4MhjjAgJCAVYAJbzpAtrOQBOx4FYggSEVYOQuTilVNgnazREH4l6HcBgy0yHPFBCA26IQCDGFMFtUkuD0QVDAWUfB5ACBhD6HAxh3D2gXAIMWABJIgFcL2jwiRJl-iAhkTg0R8jxEsNZDAERu1wQKJCMsNk0A6BwHQKoAgNkkAWOGM6Csui9gaI+IY7RDjyT6M0eQZYygb4nTOhdDhsj1EeMhHghYFwwh0CYAgMAGNSGqPIe4m6BjyBhAFG4662IPoXCIOsDJTCeG4hhMIZBRBljpUgOmfJYjnEhBDPmGk8ZylsWWiAOgk8Qw0FUAAKlUMWVQdx+DTlUEILc5iAA6IAbzTkmQAbnGbXDpjFVDAFUD4OCDE7gUEEOIPpTABnbOHKQA5OzVD6BGWM1Qkzpk0C8FuHZYgvAYPQHMhZ7SqCdJWaoNgjAuRmjEGci5vorkgAAHQAHofkMifEaMQryoDR1jgACkmRC6yZdzTgrPDSUFooSyTIAJTzKgAspAbEPnLLpHGX8XTRSQBLKoAAgkVVQZL0y0n2YM-sNBQU-I6UaBkAAeaAyhjkioAHwrIWaoVQSE6RiCRQSqVUAZUyviPhFVKKVWqplYKrZDzxXSp1aqwVq5dSGu1cak1+r0ysrYty1QfZ2QAF5JngsmaoWaHyBU0GdcAKFfzYXnPBRaq1urwVmtDcawV4KbXiCjTKolRr9ALJTfkfQQA
