### ISSUE TITLE
XML elements that contains mapping values are not beautified {@mapvalue}

### ISSUE THREAD

**Issue by avizov** [prettydiff/prettydiff#503]
Hi,
I tried to beautify with the open source the following XML element but without success. I am getting following error: string does not match the current start tag name

                                           <String>{@dd}</String> <Path>ooo</Path>

As far as I know, this is a valid XML element. If I remove the prefix "{@" it's beautifying correctly. 
please check.

**Comment by prettydiff** [comment]
Yeah,

The beautifier believes the `{@dd}` is a template start tag in something like Apache Velocity and excepts there will be an end tag like `{@}`.  This code sample works just fine: `<String>{@dd}asdf{@}</String> <Path>ooo</Path>`

What kind of template scheme are you working in?
