### ISSUE TITLE
The DOM Explained, Quick and Simple - Typo on Guide

### ISSUE THREAD

**Issue by attilagen** [prettydiff/prettydiff#505]
Hello,
On the guide you have published on link below there is a typo on previousSibling - DOM Level 2 section example code.

http://prettydiff.com/guide/unrelated_dom.xhtml

myNode.nextSibling; => myNode.previousSibling;
//returns prior adjacent node

Thank you for the guide. I enjoyed reading it.

**Comment by prettydiff** [comment]
You are correct.  I will fix this.
