### ISSUE TITLE
Configured for double quotes incorrectly converts '"' to "'"

### ISSUE THREAD

**Issue by Glavin001** [prettydiff/prettydiff#508]
# From
https://github.com/Unibeautify/beautifier-prettydiff/pull/11#discussion_r169851216

# Reproduce
See http://playground.unibeautify.com/#N4IgNghgdg5grhGBTAchAtkkAuEApCANwgGUBjAJwEsAHAFxABoQB7eqlqAZx1AOPLV6vEACMkEOHSoAzKkgo9sAbRAAFCkjp0AngAIAIrJkgAuswhgqMKAH0IXLtaiYodJTMtckFihRYA7rY0EJrcOCAOALRQSEgAJglMYpoQANa2ZAAWEFSx8baYdFks8Up0FHA+IEhQBQFUxZks6OgQOBVVzLX1jVm23uhUZCxgnB2V1XmJbpk5FBF6ydO1dANUAF5Y2ABMzABWXAAetqIUEGRpWh5e1ehwYNJWsbZ0ClChOhNdrKL7SGQ1mQ4BQwDoBiEyHkYN9qgBHOAsN5KEDxFhwURgLDMLiQpD2GRvCj2KCcWwyOBQQEcKA4TxgbzMALnGi2Z74rGwYo4AAcAAYAL4C5gsagwPKWAAqSCODFwFKp0k4eiySDAYwA6qKwPEABQASj0wAAOlTOFxRkgAHRjGC6gDkxpA9v1AG5TQKQAKgA

## Desired output
```
"
```

## Code before
```
console.log('"');
```

## Code after
```
console.log("'");
```

## Which outputs

```
'
```

## Expected after

Either not change ( [like Prettier](http://playground.unibeautify.com/#N4IgNghgdg5grhGBTAchAtkkAuEApCANwgGUBjAJwEsAHAFxABoQB7eqlqAZx1AOPLV6vEACMkEOHSoAzKkgo9sAbRAAFCkjrSFIALrMIYKjCgB9CFy4momKHSUyjXJIYoUWAdzM0Im7jgglgC0UEhIACaRTGKaEADWZmQAFhBUYRFmmHTJLBFKdBRwriBIUJmeVDlJLOjoEDiFxcxlFVXJZi7oVGQsYJyNRSXpUfZJqRSBAAQxI2V0nVQAXljYAEzMAFZcAB5mohQQZPFajs4l6HBg0sZhZnQKUH4AnoPNrKKbSGQLZHAUYGenV8ZHSMDeJQAjnAWA8lCAIiw4KIwFhmFwQUgLDIHhQLFBOGYZHAoD8OFAcE4wC5mJ5DjQzLcsajYDkcAAOAAMAF9ucwWNQYOkjAAVJA7Bi4Ymk6ScKbJJBgfoAdQFYAiAAoAJRTYAAHVJnC4fSQADp+jANQByPUgK1agDcBu5IG5QA) ) or escape:
```
console.log("\"");
```

**Comment by prettydiff** [comment]
Fixed in parse-framework 2.2.0.
