### ISSUE TITLE
Pretty Diff 3.0.0 status

### ISSUE THREAD

**Issue by prettydiff** [prettydiff/prettydiff#511]
**Not production ready and can break your code**

To play around with this version:

* Run it in the browser - http://prettydiff.com/
* Run it from the command line by cloning this project and running:

```
tsc
node js/services build
node js/services commands
```

Status:

* master branch is now version 3.  The old code is moved to 2.2.9 branch
* I am closing Pretty Diff to new features.  I will only be focusing on writing tests, finding defects, and preparing for launch

### simulation tests
  * stored in `tests/simulations`
  * these tests validate the various features and commands of the **services.ts** file are working correctly
  * these tests run as child processes and validation that certain commands to the services.ts file generate certain specified output

### unit tests
  * stored in files in the directories `tests/formatted` and `tests/raw` directories.  Files of identical names from those directory structures are compared after the files from the *raw* directory are run through Pretty Diff.
  * Files have a naming convention of `mode_lexer_language_options.txt`.  Any number of options may be specified and are separated by underscores.  Options and their values are separated by a dash `-` and the absence of a value assumes a boolean of `true` if the specified option is of boolean data type.

### diff tests
  * stored in files in the directories `tests/diffbase` and `tests/diffnew` directories.
  * this mode of testing is under-developed and welcomes expansion

**Comment by mblode** [comment]
Amazing work Austin! I am the developer of the TWIG Language extension for VSCode and I'm currently utilising Pretty Diff 2 for formatting. After some testing with Pretty Diff 3.0, I believe that some spacing issues are fixed but there are still major problems that break users code. I have compiled a list of the fixed and broken twig code so you are able to fix and test if you have a chance. All of these examples are formatted correctly but Pretty Diff is changing and sometimes breaking the code. Thank you so much for your hard work 👍 

## Fixed:

**Fixed example 1:**

`{% for module in page.collection() if module.advanced.nav.enabled %}`

**Fixed example 2:**

`{% for value in ['foo', 'bar', 'baz'] %}`

**Fixed example 3:**

`{{var}}`

## Still broken:

**Broken example 1:**

`<form class="form form-login" action="{{ path("fos_user_security_check") }}" method="post">`

*Becomes...*

```
<form class="form form-login" action="{{ path(" fos_user_security_check") }}"="fos_user_security_check") }}"" method="post">
```

**Broken example 2:**

`<p class="hello">Copyright {{ Testing }}{{ Testing }}</p>`

*Becomes...*

```
<p class="hello">Copyright
    {{ Testing }}
    {{ Testing }}
</p>
```

**Broken example 3:**

`<input type="hidden" name="test" value="{{ id["index"] }}">`

*Becomes...*

`<input type="hidden" name="test" value="{{ id[" index"] }}"="index"] }}"">`

**Broken example 4:**

```
{% switch variable %}
  {% case "value1" %}
  {% case "value2" %}
  {% default %}
{% endswitch %}

{% some other statement %}
```

*Becomes...*

```
{% switch variable %}
{% case "value1" %}
    {% case "value2" %}
        {% default %}
        {% endswitch %}
        {% some other statement %}
```

**Broken example 5:**

```
<div>
Variable1: {{ variable1 }} / Variable2: {{ Variable2 }}
</div>
```

*Becomes...*

```
<div>
    Variable1:
    {{ variable1 }}
    / Variable2:
    {{ Variable2 }}
</div>
```

**Comment by prettydiff** [comment]
Thank you so very much for these test scenarios.  I don't have a time line of when I will have these resolved an integrated, but I will get to these.  I am doing a lot of work up front, hence the delay with version 3, to ease maintenance later and allow a degree of extensibility not possible in the previous versions.

**Comment by williamzhao87** [comment]
How do I run the beautifier?

I tried the following commands without success:
```node js/services beautify source="D:\Work\Git\adv-ui\advisors\src\client" mode:"beautify" readmethod:"subdirectory" output:"D:\Work\Git\Output" lang:"html" insize:2 nodeerror:"true"```

**Comment by prettydiff** [comment]
@williamzhao87 

What kind of output did you get to the console?

**Comment by prettydiff** [comment]
@mblonde

Sorry, for the long delay.  I was currently enhancing the parser as it now identifies declared references as a new data type apart from other word like tokens.

I would absolutely appreciate help.  Please feel free to bring the code down and toy around with it.  I am coming to the conclusion that I cannot ship this software in a reasonable timeframe without contributors.

Version 3 is TypeScript so my only ask is that all primitives, arrays, and functions are declared against a data type.  I am not so concerned with creating interfaces to define object structures unless the object in question is substantial to various aspects of the code.

I also require that code pass the build and include test samples.  I am not going to challenge any difference of code style or beautification or any other petty factor so long as the build, which includes ESLint, passes.  If there is something that raises concerns I will let you know during a code review of a pull request, and I will write this down into documentation so that rules are laid out objectively.

You can clone down a specific branch with something like:

    git clone git@github.com:prettydiff/prettydiff.git -b 3.0.0

Clone it to a specific directory, such as `prettydiff3` with something like:

        git clone git@github.com:prettydiff/prettydiff.git -b 3.0.0 prettydiff3

Once cloned down do your work in a new branch created from that branch, 3.0.0.  **If your custom branch is based off of *master* instead of *3.0.0* I won't be able to merge it.**  Since the 3.0.0 branch is a complete rewrite and in a different language it is completely incompatible to master and will simply replace master when it is ready.

**Comment by prettydiff** [comment]
@williamzhao87 I am working the readmethod functionality now.  Directory traversal has been abstracted and works well.  I can traverse a git repo containing 280,000 file system artifacts at 2.6gb in about 9.5 seconds plus 1 second for each specified exclusion.

I have some organizational decisions to make in the apps.mode function of services.ts.  Here is a matrix of output types by processing considerations from least complex to most complex

output|non-diff|diff
---|---|---
screen||
file||
directory||

## Additional considerations

### Path evaluation
* [x] If readmethod is not specified then stat the source and diff to determine if they are a file, directory, or screen input.
* [x] if options.output is not specified throw error, but not if readmethod is evaluated to *screen*
* [x] if options.output is an existing file but readmethod is evaluated to *subdirectory* or *directory* throw an error
* [x] if options.output is a directory but readmethod evaluates to "file" then options.output becomes the specified filename in options.source at the directory specified in options.output.
* [x] if options.mode is diff and the previous point occurs then options.output is the same as the previous point but "-diff.txt" is added to the end.
* [x] if readmethod is not evaluated to *screen* then pass options.source and options.diff (only if mode is diff) through apps.directory.  Do this even if readmethod is file since it will resolve paths and identify file system object type.
* [x] if first item of the generated directory list is a file or symbolic link but readmethod is *subdirectory* or *directory* throw an error
* [x] if first item of the generated directory list is a directory but readmethod is *file* throw an error

### Reading files
* [x] if readmethod is *file* or *filescreen* then read the file in the first index of the generated directory list from options.source and options.diff (if mode is diff)
* [x] once both files are read, or just source if not diff, then proceed to output

### Output
* [x] If option.diffcli is true (default) and mode is diff then readmethod becomes "screen" and verbose becomes *true*
* [x] if options.mode is parse and options.parseFormat is clitable then readmethod becomes "screen" and verbose becomes *true*
* [x] if readmethod is screen or filescreen then log output to shell
* [x] if readmethod is file then write output to file


This is where I am at right now.  Diff with diffcli option isn't working, this is probably a regression.  The remaining challenge with directory output is:

* accounting for missing and inserted files
* only diff files with same file paths starting from the specified base directory and if their file contents aren't identical
* I haven't even tried Pretty Diff on files whose contents are binary buffers, so I have no idea how this will work yet
* I have to write the files in a specific order to avoid collisions.  I can probably create all the directories first while reading files so then when it comes time to write the files there won't be any collisions
* Artifacts are only written to the file system if diffcli is false
* If diffcli is true and mode is diff then I have to log everything to the terminal in an organized way

There is probably more I haven't thought of yet.

**Comment by mblode** [comment]
@prettydiff That is super exciting news! When do you think PrettyDiff 3 would be ready to replace PrettyDiff 2 for my VSCode extension or something like atom-beautify?

**Comment by prettydiff** [comment]
I want to have it ready over the next couple of weeks

**Comment by prettydiff** [comment]
Published to NPM https://www.npmjs.com/package/prettydiff

**Comment by mblode** [comment]
@prettydiff You absolute weapon! I'm starting to migrate my VSCode extension to Prettydiff 3 which is super exciting!! What is the equivalent to https://www.npmjs.com/package/prettydiff2 for integrating Prettydiff 3 with VSCode? I'm just not 100% the best way to approach the migration because the extension isn't specifically the DOM or a Node server. Thank you for your hard work and happy holidays 😄 

https://github.com/mblode/vscode-twig-language-2

**Comment by prettydiff** [comment]
Actually, I am looking at my build code and I am thinking this is a defect.  The js/prettydiff.js file should contain the parser directly embedded and I need to investigate why this isn't happening.

https://github.com/prettydiff/prettydiff/issues/550

I will work this tonight.  I really want to make inclusion of Pretty Diff easy.  I suspect there will be a fair amount of work to wire up support for the various options and other configurations, but aside from configuration I want Pretty Diff to be an application somebody can simply drop into their application and it just works immediately with defaults.  I also need to be sure the documentation addresses all installation concerns.  These pain points are where I am really going to need help to identify.  Once the pain points are identified I will work a resolution into the code.

**Comment by prettydiff** [comment]
Now pulling in Pretty Diff should be as easy as:

```javascript
let output = "",
    prettydiff = require("prettydiff"),
    options = prettydiff.defaults;
options.source = "my code";
output = prettydiff.mode(options);
```

Please continue to let me know if this fails for you, if I am missing anything, or if I need to look at another way of doing things.

**Comment by mblode** [comment]
So simple to integrate 👍 The migration is going smoothly and I'm testing it against all the formatting issues people had with my extension. Here are the final two bugs that I'm having when are formating Twig code. Where both are expected to remain unchanged.

#### Example 1
Before:
```
<div>
Variable1: {{ variable1 }} / Variable2: {{ Variable2 }}
</div>
```

After:
```
<div>
Variable1:
{{ variable1 }}
/ Variable2:
{{ Variable2 }}
</div>
```
#### Example 2
Before:
```
<widget
  template="flexbox"
  class="active-tickets"
  status="active"
  component-template="active"
  time-frame="0"
></widget>
```

After:
```
<widget class="active-tickets" component-template="active" status="active" template="flexbox" time-frame="0"></widget>
```

-----

Thank you so much for making this incredible piece of software!

**Comment by prettydiff** [comment]
I will think about how to approach example 1.  This isn't a defect, but rather a design decision.  I am providing the same spatial relationships to the template tags as I do to text and self-closing tags.  White space in XML/HTML rendering is tokenized by default which means in the rendering of output all adjacent white space is collapsed into a single space character.  My design decision is to indent where text/self-closing tags are separated by space which helps in identifying tags among long paragraphs of text without regard for word wrap.

Change the value of options.wrap to 80 in order to fix example 2.

In Pretty Diff 2 all the option configurations were manual.  Everything was manual and in a bunch of different places.  For the DOM the default was value for option *wrap* was 80 (i think) and 0 for node apps.  In the current version the default value is 0 across the board, which turns off word wrap.

**Comment by mblode** [comment]
Thank you for the response, the second issue was successfully resolved when using the wrap of 80. In regards to issue 1, I believe that makes sense, however, it causes Twig to format in odd ways because of how common the curly braces are which prints the result of an expression to the template. Could there be an option to disable this feature? 95% of the time when writing Twig code you don't really want it to format like the result. It might be too language specific of an option to toggle whether curly braces with a space character after go to a new line but I think it would be a useful feature. Thanks again!

**Comment by prettydiff** [comment]
So, yeah, I was thinking about a compromise on the way to the gym this morning.  For template tags I can leave them on the same line as the neighboring text and force them onto a new line when word wrapping takes effect.  I will work on this shortly: https://github.com/prettydiff/prettydiff/issues/552

**Comment by mblode** [comment]
Amazing thank you that seems like a great solution and I hope you have a happy new year! 🎆
