### ISSUE TITLE
Source sample is missing in 99.0.1

### ISSUE THREAD

**Issue by TomasHubelbauer** [prettydiff/prettydiff#512]
FYI I am still experiencing source sample is missing as reported in Glavin001/atom-beautify#1182. I am using 99.0.1 from NPM and am running `prettydiff` in Node. 

I am able to trigger it with as little as this:

```typescript
response.send(prettydiff.api({ source: '', diff: '', lang: 'markdown' })[0]);
```

**Comment by TomasHubelbauer** [comment]
I am also getting `pd.d` is `undefined` while executing the returned HTML each time I invoke the above (even with non-empty values where it is working). I am not sure if it is related, but it doesn't seem to interfere with the function or render in any way.

**Comment by prettydiff** [comment]
Instead try using https://www.npmjs.com/package/prettydiff2

Version 2 is far more stable.  I am currently working on version 3 and most of the way through it.

**Comment by TomasHubelbauer** [comment]
Should this repository be [archived](https://help.github.com/articles/archiving-a-github-repository/)?
