### ISSUE TITLE
Incorrect indentation on Twig's Block Shortcuts

### ISSUE THREAD

**Issue by italodr** [prettydiff/prettydiff#514]
Hi.
Is it possible that prettydiff does not take into account [Block shortcuts](https://twig.symfony.com/doc/2.x/tags/extends.html#block-shortcuts)?
I'm using Twig-language for VSCode to format my code, and now is indenting the code below as if it were inside the `{% block %}` tag.

<img width="448" alt="block-shortcut-indentation" src="https://user-images.githubusercontent.com/2691320/39749853-00ec46a4-52b4-11e8-86a3-a079a3b06664.png">

**Comment by prettydiff** [comment]
What can I look for to know that a block statement doesn't have a matching *endblock* statement?

**Comment by prettydiff** [comment]
This issue is stale, so closing for now.
