### ISSUE TITLE
Nested double quotes in HTML attributes trigger wrong behaviour

### ISSUE THREAD

**Issue by Billybobbonnet** [prettydiff/prettydiff#515]
Since JS beautify does not handle double bracket notation, I wanted to switch to pretty diff for `*.html` files.

However, while it mainly works, it has an unexpected behaviour with nested double quotes. This is a Blaze syntax and the underscore _ is an i18n helper.

When I run pretty diff, `title="{{_ "edit"}}"`turns into `title="{{_ " edit"}}"="edit"}}""`

**Comment by prettydiff** [comment]
I fixed this either yesterday or the day before.
