### ISSUE TITLE
[Question] How do I enable side by side view in prettydiff2?

### ISSUE THREAD

**Issue by yeikel** [prettydiff/prettydiff#518]
I am trying to create a side by side comparison using version 2 , but I haven't been able to do it. Did the api change? 

In version 1 , running the following code : 

```
const fs = require('fs');
const before = {count : 1};
const after = {count : 1};


let prettydiff = require("prettydiff"),
    args       = {
        source: JSON.stringify(before),
        diff  : JSON.stringify(after),
        lang  : "json"
    },
    output     = prettydiff.api(args);


fs.writeFile("test.html", output, (err)=> {
    if(err) {
        return console.log(err);
    }
    console.log("The file was saved!");
}); 
```
Produces the desired output I am looking for : https://jsfiddle.net/s8pqhdko/

On the other hand , running version 2 

```
const fs = require('fs');
const before = {count : 1};
const after = {count : 1};


let prettydiff = require("prettydiff2"),
    args       = {
        source: JSON.stringify(before),
        diff  : JSON.stringify(after),
        lang  : "json"
    },
    output     = prettydiff(args);


fs.writeFile("test.html", output, (err)=> {
    if(err) {
        return console.log(err);
    }
    console.log("The file was saved!");
}); 
```

It produces the following output : https://jsfiddle.net/od47rbuy/

How can archive the same result of v1 in v2? Do I need to maintain both versions?

**Comment by prettydiff** [comment]
@yeikel It appears the CSS is missing.  If you are running Pretty Diff from a browser look for an option *Complete Document*.  I am making this option universally available in Pretty Diff 3.

**Comment by yeikel** [comment]
I am using the NodeJS version. But I will take a look at your suggestion

**Comment by prettydiff** [comment]
This file probably has all the CSS you need:  https://github.com/prettydiff/prettydiff/blob/master/css/reports.css

**Comment by yeikel** [comment]
I am creating multiple sides by side reports programmatically, so ideally, I would like to have that CSS embedded rather than adding it manually.

**Comment by yeikel** [comment]
@prettydiff Any ideas about this issue? Thank you

**Comment by prettydiff** [comment]
Sorry, but I am not provide any code updates to version 2.  All updates and development are to version 3 which will launch soon.
