### ISSUE TITLE
Liquid: liquid markup - issue with {% unless current_tags %} 

### ISSUE THREAD

**Issue by TClilMouse** [prettydiff/prettydiff#520]
Version:
3.0.0

**Source** (should be)
`<li{% unless current_tags %} class="active-filter"{% endunless %}>`
**Output** (error)
`<li{%unlesscurrent_tags%} class="active-filter" {% endunless %}>`

**Comment by prettydiff** [comment]
I can reproduce the error and am looking at it now.
