### ISSUE TITLE
Report parse error on strings wrapped in MS-like quotes: “This looks like a string”

### ISSUE THREAD

**Issue by jau88** [prettydiff/prettydiff#521]
# Description
> No detection of invalid or unexpected token mismatches. Need to check against mismatches like  simple quotes ( " ) vs non-standard quotation marks ( “ ).

# Input
The code looked like this before beautification:
```
<“This looks like a string”>
```

# Expected Output
The code should have looked like this after beautification, note the quotation marks:
```
<"This is actually a string">
```

# Actual Output
The  code actually looked like this after beautification (no change):
```
<“This looks like a string”>
```

**Comment by jau88** [comment]
The issue occurs with JavaScript, the interpreter does not understand non-standard quotations. More information on the issue can be found in the link below.

http://docs.w3cub.com/javascript/errors/illegal_character/

**Comment by prettydiff** [comment]
I am looking at this now.  This is only a parse error if the proposed string contains white space.  Otherwise it is an undeclared variable.

**Comment by prettydiff** [comment]
dec: 8220, 8221
hex: 201C, 201D
