### ISSUE TITLE
Use prettydiff in the browser

### ISSUE THREAD

**Issue by Chaniro** [prettydiff/prettydiff#525]
Hi,

I would like to import prettydiff in my app.
I followed the instruction to build (README) and those you gave on #482 but I couldn't use it correctly even after importing `node_modules/parse-framework/js/browser.js` and `js/prettydiff.js` in my page.

Am I missing something ?

Thank you !

**Comment by prettydiff** [comment]
Try calling Pretty Diff like this:

`myResult = window.prettydiff.mode(options);`

Let me know if that doesn't work either.  Are you getting any errors?

**Comment by prettydiff** [comment]
Try this:  https://prettydiff.com/thirdparty.html

That should solve this problem.  I am wrong and still don't my stuff together please please please reopen this issue and I will continue to work this.
