### ISSUE TITLE
Documentation discrepancy:  force_indentation doesn't work, force_indent works

### ISSUE THREAD

**Issue by phpdave11** [prettydiff/prettydiff#53]
The documentation says:

`force_indentation`
**Allows every piece of code and content in a markup language to be indented without regard for the creation of white space tokens or code semantics.**

However, I think the actual API option is "`force_indent`".

Here's the command I am using:
`/usr/bin/node /usr/lib/node_modules/prettydiff/api/node-local.js source:"/tmp/prettydiff1aVuu7Z" mode:"beautify" readmethod:"file" html:"true" insize:"2" force_indent:"true" output:"/tmp/prettydiff2jKU4CO""`

**Comment by prettydiff** [comment]
You are correct. The actual option is *force_indent". I will update the documentation shortly. Thank you so much for bringing this to my attention.
