### ISSUE TITLE
SilverStripe

### ISSUE THREAD

**Issue by prettydiff** [prettydiff/prettydiff#531]
https://github.com/Glavin001/atom-beautify/issues/2248#issuecomment-441715741

https://docs.silverstripe.org/en/4/developer_guides/templates/syntax/

Comment
`<%-- whatever --%>`

These keywords appear to be start types:

* cached
* if
* loop
* uncached
* with

End types are `end_<start keyword>`.  Else types are:

* else_if
* else

```
<% with Element %>
<% end_with %>
<% control Element %>
<% end_control %>
<% loop Elements %>
<% end_loop %>
<% if $MyDinner == "quiche" %>
    Real men don't eat quiche
<% else_if $MyDinner == $YourDinner %>
    We both have good taste
<% else %>
    Can I have some of your chips?
<% end_if %>
```

**Comment by intwebg** [comment]
That's a good start, but there are also :
<% include Something %>: to include parts of HTML code 
<%t PageType.ENGLISHTEXT 'Do something' %> : to translate some part of text
<%-- some notes to remember --%> : add notes inside a template

I think that's all. If I missed some tag, can I submit them for the next release? Thanks!!

**Comment by prettydiff** [comment]
Do the *include* and *t* tags have a closing tag?

Also it looks like all the tags, aside from the comment, are delimited as `<% ` with a space.  Is the *t* tag an exception to requiring a space in its delimiter?  Are there other exceptions?

**Comment by intwebg** [comment]
_include_ and _t_ tags are self closing. No _end__. And _<%t_ have a space after _t_.

**Comment by prettydiff** [comment]
Thank you very much.  I will be working in support this week.

**Comment by intwebg** [comment]
Thanks very appreciated!

**Comment by prettydiff** [comment]
All the code examples showed spaces in the delimiters.  Are the spaces required or is this valid: 
`<%with Element%>`

**Comment by intwebg** [comment]
There are so many tags. I've updated my first post on top to show others possibilities. But to awnser your question. There are some with ans without spaces.

**Comment by prettydiff** [comment]
I know this is long overdue but I just added support for SilverStripe.  Try it out and let me know if you have any problems.

**Comment by intwebg** [comment]
Hi! Long time no see. I tested the SilverStripe support. There are some tags not formated: `<% with something %>` `<% end_with %>` and `<% loop something %>` `<% end_loop %>`

The `<% end_if %>` not closing the `<% if something %>`

Well, not working as expected. I'm sure that's not complicated for you to fix.

**Comment by intwebg** [comment]
Long time no see. What I notice, it's the `<!--`, `--!>` and `<%--`, `--%>` not working well on multi-line inside the html body. There are also old IE condition comment tags breaking the formater.
