### ISSUE TITLE
Bug when diff'ing HTML that contains inline script that itself contains HTML

### ISSUE THREAD

**Issue by bluepeter** [prettydiff/prettydiff#534]
This manifests in multiple ways, but basically HTML tags within inline `<script>` on a page. For example, the [HTML of this page](http://y8.com) contains snippets like the following:

```
<script id="live-search-template" type="text/x-handlebars-template">
  <li>
    <a href="{{path}}">
      <img src="{{thumbnail}}" class="thumb">
      {{name}}
    </a>
  </li>
</script>
```

For me, this results in `TypeError: Cannot read property '0' of undefined`.

We are using prettydiff with great success for diff'ing multitudes of pages. But pages with inline scripts that themselves contain HTML tags always cause problems for us. Currently, we are replacing these tags, but this is not ideal.

**Comment by prettydiff** [comment]
Which version of Pretty Diff are you using?  Are you using it in the browser or with Node?  Does any comparison cause this error or do I need to alter the page in some specific way before performing a diff?

**Comment by prettydiff** [comment]
Thank you, that is very thorough.  I will be releasing Pretty Diff 3 before the end of the month (hopefully much sooner than that).  I will attempt to reproduce this in version 2 and then see if the defect is present in version 3.

**Comment by prettydiff** [comment]
Is this issue still relevant in the latest version of Pretty Diff?

**Comment by bluepeter** [comment]
Probably.

However, I have tried to upgrade to the latest version and there have clearly been a lot of changes. I am having with the documentation in terms of migrating... there's not a migration guide, and nothing seems to work for me now.

Just my 2 cents but it would be great to get all documentation on this repo's README.md... I'd say that the README generally could use some attention in terms of ES6 usage, too.

I will spend some more time trying to get things working, and report back.

**Comment by bluepeter** [comment]
@prettydiff perhaps you can point out the new syntax for me? The documentation is not clear. This used to work in an earlier PR I had trying to get `100.2.8` working (where I encountered some of the `style` issues):

```
      import prettydiff from "prettydiff";

      const args = {
        ...prettydiff.defaults,
        source: "<h1>hi</h1>",
        diff: "<h2>hi</h2>",
        mode: "diff",
        diff_view: "inline",
        diff_format: "json",
        diff_space_ignore: true,
        preserve_comment: false,
        preserve_text: true,
      };

      console.log("Pretty diffing...");
      const results = JSON.parse(prettydiff.mode(args)).diff;
```

Now when I run this I get `TypeError: R.a.mode is not a function` (I assume `R.a.mode` is Webpack shortening for `prettydiff.mode`.)

**Comment by bluepeter** [comment]
I have confirmed that this is no longer an issue in the latest release. Thanks!
