### ISSUE TITLE
Trouble instantiating (Likely user error)

### ISSUE THREAD

**Issue by All-Mike** [prettydiff/prettydiff#536]
Hello, just having some trouble instantiating. It is likely user error, but I've tried with the npm package prettydiff2, and also with the built thirdparty.js

```
prettydiff.defaults={"api":"node","binary_check":{}};window.prettydiff=prettydiff;}());
                                                     ^
ReferenceError: window is not defined
```

When I try to require the thirdparty.js bundle I get the above. The documentation is a little tough to follow, I often end up at outdated solutions. No blame to the author, I'm sure it's just user error.

I've compared many diff tools and this seems like by far the best. Please let me know which tutorial or guide would be best to follow, just so I'm sure the source is correct. Thanks in advance!

.

PS, to be clear, I am using a node server & angular frontend, trying to create the diff data on some JSON objects through the backend and send it up front. I will gladly load from the frontend if necessary (since there's a window issue) but I'm having trouble doing that from the Angular frontend as well. Thanks in advance!

**Comment by prettydiff** [comment]
Its ok.  Please ask with details.  I want to see if there is an error in the build or unclear instructions.  At the very least I might be able to answer a question.
