### ISSUE TITLE
Sublime Text plugin

### ISSUE THREAD

**Issue by prettydiff** [prettydiff/prettydiff#55]
Create allow execution of Pretty Diff on active code file in Sublime Text.

**Comment by paazmaya** [comment]
:+1:

**Comment by tommmyy** [comment]
+1

**Comment by tnrich** [comment]
I would really love this feature ! It seems like there isn't any sort of jsx parser in sublime yet.

**Comment by ezrafree** [comment]
+1 here too! I've been searching around for something that can format my Sass code without any blank lines, and so far the only tool I've come across has been prettydiff.com, because the other tools all use the `sass-convert` command which adds new lines in between statements and double new lines between @include statements. I can't help but to wonder what it would take to make a Sublime Text package that could support PrettyDiff in this way.

**Comment by prettydiff** [comment]
Sublime Text is written in Python and so are its plugins.  This could be as simple as a shallow API to define settings or a context menu that gets passed to the Pretty Diff application.  Pretty Diff options are just an object so this could be as simple as using the plugin to define a JSON object and passing it off.

The challenge is that you would need some sort of JS run time, would could just be Node.js.  Most web developers probably already have Node installed and it would just need to be indicated as a required dependency.  The other half of the challenge is that Pretty Diff will generate output, which is probably a JavaScript string that needs to be passed back to the python plugin so that it can be dumped back into the editor.

On top of all this is that the plugin would have to be maintained as new options arise or as changes occur.  New options creep up about every two to three months.  Changes to the existing API do happen, but that is extremely rare.  Even when options change name or supported value type I almost always secretly support the old objects for backwards compatibility.  In the seven years I have been maintaining this application I have only removed an option maybe 2 times.

If anybody is willing to setup and own this I will definitely contribute maintenance towards it.  I am contributor to the Atom Beautify project because I am more than happy to triage issues and help out a project that exposes the application.

**Comment by prettydiff** [comment]
This might be coming thanks to Atom-Beautify:

https://github.com/Glavin001/atom-beautify/issues/664#issuecomment-237888125

**Comment by Glavin001** [comment]
+1 Atom-Beautify will eventually support Sublime and will support Pretty Diff as a beautifier.

**Comment by prettydiff** [comment]
I will defer this effort to the Unibeautify project: https://github.com/Unibeautify/

**Comment by possibleworlds** [comment]
I currently have prettydiff working well in sublime with https://github.com/jeffomatic/SublimeFmt. I did need to amend the command string replacement within SublimeFmt to work a bit better with cli's that expect specifying file location in a specific ways (like prettydiff does). This works for me... 

1. Replace SublimeFmt.py line 96  `cmd = '%s "%s"' % (fmt_cmd, p)` with `cmd = fmt_cmd % (p)`

2. Specify SublimeFmt config as eg:

```json
{
  "formatters": [
    {
      "cmd": "prettydiff beautify config:'/path/to/.prettydiffrc' source:'%s'",
      "extensions": [".html",".liquid",".twig"]
    }
  ]
}
```

`'%s'` becomes tmpfile location in all SublimeFmt cmd prefs.

This is literally the first time I have ever had real auto-formatting working for template languages in sublime. Thanks @prettydiff !
