### ISSUE TITLE
SCSS formatting problem

### ISSUE THREAD

**Issue by wmaurer** [prettydiff/prettydiff#56]
I am using prettydiff as part of the the atom.io atom-beautify package.
I have a problem with formatting of SCSS. Given the following:
```
$grid-row-cells: 4;
.tile {
    @for $x from 1 through $grid-row-cells {
        @for $y from 1 through $grid-row-cells {
            &.tile-position-#{$x}#{$y} {
            }
        }
    }
}
```
Unfortunately prettydif inserts a space after the closing curly braces, which means that `&.tile-position-#{$x}#{$y} {` will be formatted as `&.tile-position-#{$x} #{$y} {`. This will result in bad-formed CSS, i.e. the class name will be `&.tile-position-1 -1 {`

I think no space should follow a closing curly brace if it's part of the definition of a class name.

I look forward to your feedback.

**Comment by prettydiff** [comment]
When a  curly brace is used in a selector value is it always immediately preceded with a #?

**Comment by wmaurer** [comment]
I'm a long way from being a SCSS expert, but your analysis for pattern matching sounds right. I see you've already made a fix. Thanks a lot!
