### ISSUE TITLE
Trailing Whitespace?

### ISSUE THREAD

**Issue by jlpoolen** [prettydiff/prettydiff#565]
I need to identify any whitespace differences.

Example:

     abc

compared with

     abc

 
2nd example has an additional linefeed after "c".

I've reviewed the settings and do not see something that will strictly identify any discrepancy of whitespace.  Is there a switch that will invoke checking whitespace and highlight the results?

**Comment by jlpoolen** [comment]
I'm having problems making the example demonstrate the difference.  The difference should simply be that in the first example, the character "c" is the last character.  In the second example, the last character is a linefeed which follows the "c".

**Comment by prettydiff** [comment]
Yes, I need to be more explicit about this.  The default value for option *language* is either `auto` or an empty string.  Change the value to `text` and each character will be explicitly compared.

I will leave this issue upon until I resolve it with better documentation.

**Comment by jlpoolen** [comment]
Thank you, empty string in the language field worked.

Note for others: if I enter the word "text" in the language field, pressing Execute does nothing.  If I erase all characters from the language field, then Execute works.
