### ISSUE TITLE
Liquid: support for capture/endcapture tags

### ISSUE THREAD

**Issue by clyons** [prettydiff/prettydiff#571]
@prettydiff I was testing Liquid code with the uglified source of the Shopify [SEOManager](https://seomanager.com) app. 

Prettydiff is not beautifying `capture` / `endcapture` tags properly.

**Input:**

```
{%- capture NYDUHGWUGA -%}{{ current_tags }}{%- endcapture -%}
```

**Output:**
```

{%- capture NYDUHGWUGA -%}
    {{ current_tags }}{%- endcapture -%}
```

**Expected output:**

```
{%- capture NYDUHGWUGA -%}
    {{ current_tags }}
{%- endcapture -%}
```

**Prettydiff comment:**

```
/*prettydiff.com mode: "beautify" */
```

**Comment by prettydiff** [comment]
Both of these two issues should be a quick fix.  I just launched a new major version of my parser, a separate application, so I have integrate that back into Pretty Diff first.  I want to have both of these two issues complete this weekend.
