### ISSUE TITLE
HTML <img> tag enforcing XHTML rules

### ISSUE THREAD

**Issue by panoply** [prettydiff/prettydiff#576]
Given the following code:

```
<div>
<img src="1.jpg" class="img">
</div>
```

PrettyDiff will beautify and output:

```
<div>
    <img class="img" src="1.jpg"></div>
```

If you close the `<img>` tag inline (`<img src="1.jpg" class="img" />`) code will output as expected.

**Comment by prettydiff** [comment]
Because the markup portion of the tools supports many languages it defaults to XML when it cannot identify the language.  Ensure the language is set to HTML or that enough of the document is present to identify the language as HTML, such as a doctype or HTML tag.

**Comment by prettydiff** [comment]
What I can do to help with this problem specifically is that I can associate `img` tags to HTML auto-detection to solve this specific case.

**Comment by prettydiff** [comment]
This is the test I will use to solve this problem:

```javascript
(/<img(\s+\w+=("|')?\S+("|')?)*\s+src\s*=/).test(sample) === true
```

The fix will be in the lib/language.ts file of the parser:  https://github.com/Unibeautify/sparser/blob/master/libs/language.ts

**Comment by prettydiff** [comment]
Just update your Pretty Diff dependencies and this should be all better.

`npm update`

If you are still running into problem let me know and I will try something else.

**Comment by panoply** [comment]
Updating sparser and applying `HTML`  language resolved the issue. I was using `liquid` language previously but `HTML` applies formatting to liquid code too. 

I speak for many developers when I say that PrettyDiff is truly a poetic project. The time and upkeep you maintain is both inspiring and does not go unnoticed. Thank you.
