### ISSUE TITLE
JSON output when comparing two highly complex HTML documents

### ISSUE THREAD

**Issue by bluepeter** [prettydiff/prettydiff#579]
I am upgrading from prettydiff2 2.2.7 to prettydiff 100.2.8. As noted, things are very different.

I save the rendered DOM from fandango.com which consists of several 1000s lines of inlined Javascript and CSS. For testing, I do a comparison of the exact same file. Surprisingly, I get an array of arrays whose first item is each `-` incorrectly indicating, I believe, a deletion of that line. When I add or remove one or two lines to either file, the parser will sometimes correctly show a `r` replacement, but not consistently.

- Can someone please help me understand the JSON output? It looks like `r` = replacement, `+` = addition, `=` = no change, and `-` = deletion, right?
- Are there known issues parsing highly complex HTML pages with inlined Javascript, CSS? 2.2.7 would usually handle these w/o issue. But, unless I am mis-understanding the JSON output, I am now experiencing "whole page deletions" when comparing the complex rendered DOM from, e.g., fandango.com, cnn.com, nytimes.com

**Comment by prettydiff** [comment]
Please describe the exact steps I would need to reproduce the result you got and I can better answer any questions or identify defects.

**Comment by bluepeter** [comment]
Sure, let me get you an example momentarily. I have been working w/ this for about 8 hours and it's honestly been quite frustrating. The diffs just aren't... reliable at least w/ how I am operating it.

**Comment by bluepeter** [comment]
I have moved on from the originating JSON issue and to more basic operations of prettydiff on the CLI level so I can understand what's going on.

Using this HTML https://gist.github.com/bluepeter/381513a02daceeee1007db33a673cb38 for a.html, I then attempt a diff against b.html which is the exact same HTML. It strangely results in an apparent diff?

See CLI here:

```
src$ cp a.html b.html 
src$ diff a.html b.html 
src$ prettydiff diff source:"a.html" diff:"b.html"

Line: 1
<html class="" lang="en" xml:lang="en" xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <style type="text/css">
            .tippy-iOS {
                cursor: pointer !important
            }
            .tippy-notransition {
            (function (w, d, s, l, i) {
(function (w, d, s, l, i) {

Line: 523
        </script>
        <script charset="utf-8" src="https://platform.twitter.com/js/moment~timeline~tweet.6e5b62723488aee38af0c77681396a5b.js"></script>
        <script charset="utf-8" src="https://platform.twitter.com/js/tweet.2b7769d244a8dfeb3ab9d97583412dec.js"></script>
    </head>
    <body class="loggedOut forceGrey">
        <div id="holder_for_footer">
            <div id="internal_for_footer">


Pretty Diff found 2 differences on 3 lines.
```

**Comment by bluepeter** [comment]
Separately, using the same HTML as in the previous comment, and comparing two identical files, when I attempt to output the diff in json, I get completely different results.

CLI: `prettydiff diff source:"a.html" diff:"b.html" diff_format:"json" diff_view:"inline`

As expected, the HTML is escaped characters. But instead of just seeing the same lines as previously mentioned as diff, I now get every line as an array with `-`, which I presume means deletion?

<img width="1749" alt="Screen Shot 2019-03-18 at 8 39 10 PM" src="https://user-images.githubusercontent.com/2158187/54578692-eb7d1300-49bd-11e9-84e6-fd837b0027ad.png">

I am getting similar inconsistent, strange results when comparing identical or near-identical HTML from multiple different sites (e.g., cnn.com, fandango.com, etc).

I'd really appreciate any help! prettydiff is a big part of our differencing system.

**Comment by bluepeter** [comment]
And, finally, when I edit `b.html` in the same referenced files, and add `<p>this is a test</p>` and run the same command, it doesn't detect the change.

<img width="1514" alt="Screen Shot 2019-03-18 at 8 51 05 PM" src="https://user-images.githubusercontent.com/2158187/54579218-b07bdf00-49bf-11e9-9d77-fe8f7f744efe.png">

I am sure it's just some basic error on my part... but I've been at this for 8+ hours now, and I just can't get reliable or consistent results.

**Comment by bluepeter** [comment]
After playing around w/ more options, I think at core this comes to issues with prettyDiff and inlined styles and Javascript? Perhaps related to the one I raised in https://github.com/prettydiff/prettydiff/issues/534. That is to say, if I strip the relatively straightforward inlined css/js from the referenced HTML in this issue, then results start to look ok.

What's frustrating is that there may have been a reversion in how prettydiff now handles css/js. In previous versions, prettydiff would only choke on complex js that itself included HTML/etc snippets (e.g., Angular, etc). But now it may be having problems with relatively basic Javascript from Google Analytics?

It seems as though, when analyzing an HTML document, inlined styles/js should be tokenized and marked wholly as different if there's any change within them, versus trying to do a line by line comparison within inlined scripts?

**Comment by prettydiff** [comment]
I am working on a CSS defect right now and I promise I will get to this next.  Honestly, the diff library needs a lot of work so a superior solution might be shipped over a couple of commits.

**Comment by bluepeter** [comment]
Okay, thanks Austin. Much appreciated. Prettydiff is a vital tool for us, so we look forward to seeing progress on these! Let us know if we can provide anymore data or help.

**Comment by bluepeter** [comment]
Hi @prettydiff I'm wondering how things were coming on this issue?

**Comment by prettydiff** [comment]
I will start working on it this week.  Sorry for the delay.  I have switched tracks at work to criminal investigations and this has consumed some of my focus.

**Comment by prettydiff** [comment]
I have identified the problem.  Pretty Diff modifies some options for internal use, namely:
* end
* indent_level
* start

This is an easy fix in the case of diff operations, but this is sloppy architecture on my part resulting in second order consequences if a third party application were to use Pretty Diff multiple times from cached settings.

I will fix this problem for all users today.  I will remove the *end* and *start* options and pass in the starting indentation to each of the beautification functions.  This will not be a massive change, but it is a breaking change to the API and will require a new major version number.

**Comment by bluepeter** [comment]
Thank you @prettydiff !!!

**Comment by prettydiff** [comment]
This is resolved in the new major version 101.  Just let me know if you continue to experience any problems.

**Comment by bluepeter** [comment]
Woo hoo, thank you @prettydiff
