### ISSUE TITLE
Can't diff rendered HTML

### ISSUE THREAD

**Issue by bernd-wechner** [prettydiff/prettydiff#580]
I'm just taking it for a spin at:

https://prettydiff.com

and am confused on a few things and seem unable to get what I'm hoping for, a diff of rendered HTML. I load two HTML files (local) with one word different. I then select options that it summarises as:

`/*prettydiff.com diff_format: "html", diff_rendered_html: true, language_name: "HTML" */`

and yet when I click Execute I see at top:

`Code type is set to auto. Presumed language is HTML/PHP.`

which puzzles me as I specified HTML as the language and then a popup that shows me the source HTML code and correctly identifies the different word.

But what I was hoping for and sent here to find I guess, is something that rendered the HTML page and perhaps marked up that changed work in an easily spotted way. A diff of the rendered HTML presented in rendered HTML.

Perhaps I misunderstood? Or perhaps I'm just not seeing how this can be done.

**Comment by prettydiff** [comment]
Sorry for the delayed response.  I have an option `diff_rendered_html` that adds CSS to a complete HTML document submitted as source material.  The added CSS will visually indicate the changes that occur in the code.
