### ISSUE TITLE
Formatting messes up code when not using self-closing tags for <br> or <img>

### ISSUE THREAD

**Issue by mblode** [prettydiff/prettydiff#581]
When I format TWIG markup, the formatter messes up my code. Because it is not able to handle non closed tags like `<br>`, `<img>` or `<meta>`

For instance this simple page:

```html

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
```

```html

</body>
</html>
Turns into this abomination, after formatting:

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
            <meta content="width=device-width, initial-scale=1.0" name="viewport">
                <meta content="ie=edge" http-equiv="X-UA-Compatible">
                    <title>Document</title>
                </head>
                <body></body>
            </html>

```

**Comment by prettydiff** [comment]
Its just processing with XML rules (the default).  HTML supplies a couple of rules on top of the XML stuff so that list items are closed and tags like those you mentioned are closed.  For the moment **changing the language setting to HTML** will fix this problem and still get you support for the various template language tags.

I need to think of a better architectural solution to differential between XML and HTML language support when the language specified is neither of those.

**Comment by mblode** [comment]
@prettydiff Thank you! That seems to have fixed the XML tag issue 👍 Another issue I'm having is that when I have some HTML such as...

```html

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta content="width=device-width, initial-scale=1.0" name="viewport">
        <meta content="ie=edge" http-equiv="X-UA-Compatible">
        <title>Document</title>
    </head>
    <body>
        <script>console.log("Hello")</script>
    </body>
</html>

```

Then when I beautify as HTML it becomes...

```html

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta content="width=device-width, initial-scale=1.0" name="viewport">
        <meta content="ie=edge" http-equiv="X-UA-Compatible">
        <title>Document</title>
    </head>
    <body>
        <script>console.log("Hello")</script>
    </body>
</html>

```

But finally, if I run the formatter for a second time, the contents of the beautify become...

```html

console.log("Hello")

```

This is breaking formatting for many people who have a script tag within their HTML file. How can I fix this issue?
