### ISSUE TITLE
Usage from NodeJs / Typescript

### ISSUE THREAD

**Issue by jobe451** [prettydiff/prettydiff#583]
I would like to use prettydiff as a module in a nodejs/typescript script not from command line.

I would like to get:
a) number of diffs
b) a structured analysis/json
c) a HTML visualisation that can be stored as file

I was able to that with a 2017-version, that is now lost. 

How can I do that with latest prettydiff?

**Comment by jobe451** [comment]
sorry, I didn't sufficiently rtfm

**Comment by prettydiff** [comment]
No problem.  Just let me know if the application proves frustrating or unclear for you.  I will do what I can to make it easier to use and the documentation more clear.
