### ISSUE TITLE
Indentation style ALLMAN disappeared??

### ISSUE THREAD

**Issue by BarbzYHOOL** [prettydiff/prettydiff#589]
I used to use prettydiff only for that option.

I had even made a local backup but even in my fuckin local backup, when I click on "ALLMAN" option, it does not convert. I suppose my backup gets some CSS or JS from your actual site and since you removed that option, I can't convert my code.

Why??? :'(

**Comment by prettydiff** [comment]
The feature is still available.  I am just not labeling it as clearly as I used to.  Set option *braces* to true.  I will update the options so that they are described as Allman and K&R like they used to.

**Comment by BarbzYHOOL** [comment]
ok ty
