### ISSUE TITLE
Is it broken ?

### ISSUE THREAD

**Issue by nitinsurana** [prettydiff/prettydiff#591]
1. Open https://demo.borland.com/testsite/stadyn_largepagewithimages.html
2. `View Source`
3. Copy the html
4. Paste in both the boxes at prettydiff.com
5. Click on Execute (nothing happens, bug!?)

PS : There is no error in chrome developer tools console

**Comment by prettydiff** [comment]
I do see error messaging in the Firefox console.  The error is in the Ace code editor.  I will report this error to the Ace team.  In the mean time look for an option labeled: *Disable Ace Code Editor (Faster and more accessible)* and there will be no defects.

**Comment by nitinsurana** [comment]
Please re-open, the demo is still unusable.
I'm unable to understand what is expected!
1. Get html from https://demo.borland.com/testsite/stadyn_largepagewithimages.html
2. Paste in both Source/New code (Am I supposed to select files, instead of pasting in textarea ?!)
3. Disable ace-editor
4. Click on Execute 
5. Notice nothing happens. 
Expected : Some kind of indication that the html are same

**Comment by nitinsurana** [comment]
If pasting html in the textboxes is not what is the expected use-case, then please show some kind of error message.

**Comment by nitinsurana** [comment]
Also, if you can provide a quick video (as a GIF) and add to README.md to demonstrate how to use https://prettydiff.com/, that'll be awesome.

**Comment by nitinsurana** [comment]
Finally, found what is going wrong.
I'm using this chrome extension titled "Deluminate" & when the extension is enabled, clicking on "Execute" doesn't work.
This is the first site, I've ever seen had such an issue with Deluminate. 
Regardless, I'll file a bug with Deluminate developer.
Thanks for all the help & sorry for the trouble :-)

**Comment by prettydiff** [comment]
Thanks, for investigating that.
