### ISSUE TITLE
Twig language bugs

### ISSUE THREAD

**Issue by mblode** [prettydiff/prettydiff#592]
Hey @prettydiff,
Thanks again for excellent work on the new version and it has fixed a majority of bugs. I'd just like to centralise a list of bugs and formatting issues that some people are facing.

### Bug no. 1

In one of my templates, I have an empty block short tag as a placeholder, to be extended in other templates. Then tag is duplicated causing compile errors:

```html
  {% block head '' %}
```

**After formatting:**

```html
            {% block head '' %}
        {% block head '' %}
```

*Full source code:*

```
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <title>
    {% if block('htmlTitle') is defined %}{{ block('htmlTitle') ~ ' - ' }}{% endif %}
    Administration
  </title>
  <link rel="stylesheet" href="...link-to-file">

  <script>
    let config = {
      dateFormat: "{{ site.settings.dateFormat }}",
      weekStart: {{ site.settings.dateFormat == 'mm/dd/yyyy' ? '0' : '1' }},
      csrfTokenName: "{{ site.csrf.name }}",
      csrfTokenValue: "{{ site.csrf.value }}",
      {% block jsConfig '' %}
    };
  </script>

  {% block head '' %}
</head>

<body>
  {% include "@admin/includes/_alert.html" %}

  <section id="default" class="content-wrapper">
    <div class="sidebar">
      {% block sidebar '' %}
    </div>

    <main role="main" class="content">
      {% block content '' %}
    </main>
  </section>

  <script src="...link-to-file"></script>

  {% block foot '' %}
</body>

</html>
```

### Bug no. 2

Formatting JSON incorrectly:

```html
{% for item in [
{
    "name": "Matthew"
},
{
    "name": "Austin"
}
] %}
  <div></div>
{% endfor %}
```

**After formatting:**

```html
{% for item in [
    {
        "name": "Matthew"
    },
    {
        "name": "Austin"
    }
] %}
  <div></div>
{% endfor %}
```

### Bug no. 3

Formatting wrap text will result in the infinite indentation:

```html
<div class="p">
    <h4>Market — your business
        {{ i + 1 }}</h4>
    <p class="mt-sm">
        Take the guesswork out of marketing with 
        built-in tools that help you create, execute,
        and analyze campaigns on Facebook and Google.
    </p>
</div>
```

**After formatting:**

```html
<div class="p">
    <h4>Market — your business
        {{ i + 1 }}</h4>
    <p class="mt-sm">
        Take the guesswork out of marketing with
                built-in tools that help you create, execute,
                and analyze campaigns on Facebook and Google.
    </p>
</div>
```

### Bug no. 4

Automatically indents block when it doesn't have a closing "endblock" tag.

```html
{% block presentation %}
{% block header %}
{% block footer %}
```

**After formatting:**

```html
{% block presentation %}
    {% block header %}
        {% block footer %}
```

### Bug no. 5

Adds Linebreaks before {{ and after }} if there are a whitespace.
Is it possible to prevent this?

```html
<div>
Variable1: {{ variable1 }} / Variable2: {{ Variable2 }}
</div>
```

**After formatting:**

```html
<div>
    Variable1:
    {{ variable1 }}
    / Variable2:
    {{ Variable2 }}
</div>
```

### Bug no. 6

When I use anchor tags with a twig variable for the href inside of a li tag, the formatter is combining the a and href into a single tag.

```html
<li><a href="{{ path_for('home') }}">Home</a></li>
```

**After formatting:**

```html
<li><ahref="{{path_for('home')}}">Home</a></li>
```

### Bug no. 7

My DOCTYPE tag keeps moving to the previous line on format if the previous line contains {%%}

```html
{% import "/_macros.twig" as macros %} 
<!DOCTYPE html>
```

**After formatting:**

```html
{% import "/_macros.twig" as macros %} <!DOCTYPE html>
```

### Bug no. 8

When outputting twig variables, I prefer to have spaces before and after for readability.

Dislike:

```html
{{var}}
```

Like:

```html
{{ var }}
```

**Comment by prettydiff** [comment]
Here is my summary so far:

* **Bug 1** - Illustrated several defects in the parser, including bug 4.  I will have this resolved soon.
* **Bug 2** - It appears you are requesting objects as array indexes not be indented an extra step from the parent array.  I prefer that each step in a data structure be indented to visually call out the depth of a given structure.  In my opinion this is working correct, but I can be persuaded to shift on any position provided stronger evidence.
* **Bug 3** - Beautification defect. I will fix this.
* **Bug 4** - Fixed this in the parser, but I need to test a few more things.
* **Bug 5** - I cannot specifically remember, but I think this was specifically requested by a different user, and before it was requested I used to beautify the code exactly as you are suggesting.
* **Bug 6** - Beautification defect.  I will fix this.
* **Bug 7** - Beautification defect.  I will fix this.
* **Bug 8** - Fixed in the parser.

**Comment by prettydiff** [comment]
At this time I am having some trouble reproducing Bug 3.  I am getting the following output with a wrap limit of 40 characters:

```html
<div class="p">
    <h4>Market — your business {{ i + 1 }}</h4>
    <p class="mt-sm">
        Take the guesswork out of marketing with
        built-in tools that help you create,
        execute, and analyze campaigns on
        Facebook and Google.
    </p>
</div>
```

**Comment by mblode** [comment]
Amazing! Thank you for the quick response 👍 

Regarding Bug 2, I definitely agree with you here and think the way it formats seems correct. One user just had that preference and there is no option to alter the indentation.

**Comment by mblode** [comment]
I think the user does not have any wrap set and uses the enter key to define the spacing.

**Comment by prettydiff** [comment]
I am also having some trouble reproducing Bug 6.

**Comment by prettydiff** [comment]
I have to get ready for work in a few minutes, but I am 90% done with this and will have the code updates this evening once I return from the office.  Thanks so much for reporting these to me.

**Comment by mblode** [comment]
A user just found another bug after the update:

I have setup visual studio code with atom beautify and although most of the twig formatting works correctly, there seems to be a problem with {% block %} statements.

e.g.
```html
{% block A %}
  {% set foo = 'bar' %}
{% endblock A %}

{% block B %}
  {% set bar = 'foo' %}
{% endblock B %}
```

is converted to

```html
{% block A %}
{% set foo = 'bar' %}{% endblock A %}{% block B %}{% set bar = 'foo' %}{% endblock B %}
```

Is there any configuration that prevents this?

**Comment by prettydiff** [comment]
This is going to take some effort to resolve.  I spent some effort ensuring that *block* behaves like a singleton tag but in this example it is clearly a start tag with a matching end tag.

**Comment by prettydiff** [comment]
This should be fixed in the latest version of Pretty Diff.

**Comment by mblode** [comment]
Hey @prettydiff, I've just realised this morning that this statement is technically incorrect in some cases, "{% block name %} is always the start of a structure with an end tag."

From the Twig docs:

1. When a template uses inheritance and if you want to print a block multiple times, use the block function:

```html
<title>{% block title %}{% endblock %}</title>
<h1>{{ block('title') }}</h1>
{% block body %}{% endblock %}
```

2. The block function can also be used to display one block from another template:

```html
{{ block("title", "common_blocks.twig") }}
```

-----

The "block" tag can, therefore, function with or without an "endblock" tag...

**Comment by prettydiff** [comment]
In that latest example the two `{% block %}` tags have matching `{% endblock %}` tags, but `{{ block... }}` does not.  That said everything should be working correctly right now unless I am still not understanding the structure of it.

**Comment by mblode** [comment]
Oh sorry, I got confused! I probably shouldn't submit an issue right when I wake up 😬 

Here is the sample that was breaking for a user where {% block %} doesn't have an {% endblock %} tag, therefore, breaking the indentation of the document.

```html
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <title>
    {% if block('htmlTitle') is defined %}{{ block('htmlTitle') ~ ' - ' }}{% endif %}
    Administration
  </title>
  <link rel="stylesheet" href="...link-to-file">

  {% block head '' %}
</head>

<body>
  {% include "@admin/includes/_alert.html" %}
  {% block maintTitle 'CMS' %}
  {% block leadText 'Lead text goes here...' %}

  <section id="default" class="content-wrapper">
    <div class="sidebar">
      {% block sidebar '' %}
    </div>

    <main role="main" class="content">
      {% block content '' %}
    </main>
  </section>

  <script src="...link-to-file"></script>

  {% block foot '' %}
</body>

</html>
```

Is formatted like this:

```html
<!doctype html>
<html lang="en">

    <head>
        <meta charset="utf-8">
        <meta content="width=device-width, initial-scale=1, shrink-to-fit=no" name="viewport">

        <title>
            {% if block('htmlTitle') is defined %}
                {{ block('htmlTitle') ~ ' - ' }}
            {% endif %}
            Administration
        </title>
        <link href="...link-to-file" rel="stylesheet">

        {% block head '' %}
        </head>

        <body>
            {% include "@admin/includes/_alert.html" %}
            {% block maintTitle 'CMS' %}
                {% block leadText 'Lead text goes here...' %}

                    <section class="content-wrapper" id="default">
                        <div class="sidebar">
                            {% block sidebar '' %}
                            </div>

                            <main class="content" role="main">
                                {% block content '' %}
                                </main>
                            </section>

                            <script src="...link-to-file"></script>

                            {% block foot '' %}
                            </body>

                        </html>
```

**Comment by prettydiff** [comment]
This should be fixed now.  The behavior is as follows:

* a `{% block %}` tag is a singleton by default
* a `{% block %}` tag becomes a start type only when a `{% endblock %}` tag is encountered
* a `{% endblock %}` with a name that matches the name of a `{% block %}` will modify only that first encountered tag to become a start type skipping other block tags in between.
* a `{% endblock %}` with no name will modify the first prior `{% block %}` tag into a start type.
* a `{% endblock %}` with a name that doesn't match a `{% block %}` in the resolvable structure will have unexpected results and the document will not format correct.
