### ISSUE TITLE
webste https://prettydiff.com - favicon.ico is not displayed / missing favicon

### ISSUE THREAD

**Issue by Tset-Noitamotua** [prettydiff/prettydiff#597]
Just bootmarked your site and noticed favicon is not displayed.
Browser: Google Chrome (Version 74.0.3729.169)  on Linux (Deepin 15.10)

![image](https://user-images.githubusercontent.com/5635462/58955135-607d0f00-879b-11e9-9110-7436bd865b57.png)

**Comment by prettydiff** [comment]
Updated favicon.ico generated and uploaded to site.  It is probably locked behind cache control right now, but the cache will expire tomorrow.
