### ISSUE TITLE
Feature Request: Collapse similar items/tags/lines

### ISSUE THREAD

**Issue by nitinsurana** [prettydiff/prettydiff#599]
I tried comparing 2 different tutorials from w3schools.com and they gave `Number of differences: 2373 differences from 1939 lines of code.` 

Scrolling through 1939 lines to find the differences, is time taking. If we can somehow collapse the similar code (just like github diff - https://github.com/BrowserSync/browser-sync/pull/1659/files#diff-a8f173800f0aeeecdf24ec9f4e9c8658L56, notice EXPAND_DOWN, EXPAND_UP icons for package.json) and let the user focus on what matters most - differences, that'll be great.

**Comment by prettydiff** [comment]
I have an option for that: `diff_context`.  The default value is -1 which disables the option.  Other values will show only the differences in the output padded by a number of lines provided by the option value.

For example if the value provided to `diff_context` is 2 then you would get output that organized something like:

* equal line
* equal line
* difference
* equal line
* equal line
* separator
* equal line
* equal line
* difference
* equal line
* equal line

That way you aren't having to scroll through the whole document.  I think this addresses the issue so I am closing it.  Please play around with this option and if it fails to address your concern please let me know and I will reopen the issue.
