### ISSUE TITLE
Bug : text diff format breaks for html input on http://prettydiff.com

### ISSUE THREAD

**Issue by nitinsurana** [prettydiff/prettydiff#602]
Steps to reproduce : 
1. Take 2 sample html (I took from w3schools.com)
2. Disable ace_editor
3. Set the diff_format to text (instead of html)
4. Click on Execute
5. Notice it fails with the following error in browser console : 
```
Uncaught TypeError: Cannot read property 'replace' of undefined
    at diffview_report_htmlfix (webtool.js?1559746292226:18519)
    at diffview_report (webtool.js?1559746292226:19060)
    at Object.diffview_ [as diffview] (webtool.js?1559746292226:19584)
    at mode (webtool.js?1559746292226:6267)
    at dom_event_execute_app (webtool.js?1559746292226:3373)
    at HTMLButtonElement.dom_event_execute (webtool.js?1559746292226:3648)
```
Expected : It should work.

**Comment by prettydiff** [comment]
Something is horribly wrong.  The stack trace is definitely functions out of the application, but the locations are bizarre. 

`webtool.js?1559746292226:18519`

The webtool.js file is a generated file containing all the libraries, so it is going to be large at around 23000 lines of code, but your stack trace is pointing to character 18519 on line 1559746292226.

From the function names alone I fix this error though and will have a patch out soon.

**Comment by prettydiff** [comment]
One possible cause for the absurd line numbers is if you are building the application from the TypeScript files (instead of installing from NPM) and using an older version of TypeScript.  Try updating TypeScript to the latest version.

**Comment by nitinsurana** [comment]
> One possible cause for the absurd line numbers is if you are building the application from the TypeScript files (instead of installing from NPM) and using an older version of TypeScript. Try updating TypeScript to the latest version.

I got this bug on http://prettydiff.com

**Comment by littleninja** [comment]
@nitinsurana can you still reproduce this? Would you mind including the code samples that break on https://prettydiff.com?

**Comment by nitinsurana** [comment]
I am no longer able to reproduce it. It works as expected.
Looks like the fix worked! :-)
