### ISSUE TITLE
Possible Bug: Html structure aware comparator not working

### ISSUE THREAD

**Issue by nitinsurana** [prettydiff/prettydiff#603]
The differentiator ignores the language and simply does text difference even if the input is html and language is set to html. Different html markups can mean the same thing.

For e.g.
<img width="1605" alt="Screen Shot 2019-06-06 at 4 48 57 PM" src="https://user-images.githubusercontent.com/7137160/59073266-2daa4800-887b-11e9-8286-adb0ade0b36a.png"> makes sense when language is `plain/text`, but if the language is `html` then it is not a difference.

I used html from different tutorials at w3schools.com and the total number of differences for text & html are same.

**Comment by nitinsurana** [comment]
I have been evaluating DaisyDiff on the side. Looks like it does html structure aware comparison but it's pretty slow :-|
A javascript port of https://github.com/DaisyDiff/DaisyDiff for html comparison could be better.

**Comment by prettydiff** [comment]
I found the problem:

`if (prettydiff.beautify[options.lexer] === undefined && options.lexer !== "text") {`

should be:

`if (prettydiff.beautify[options.lexer] === undefined && options.lexer !== "auto" && options.lexer !== "text") {`

https://github.com/prettydiff/prettydiff/blob/master/api/prettydiff-webtool.ts#L3492

I will publish the fix soon.
