### ISSUE TITLE
Bug: bad formatted img path in styles

### ISSUE THREAD

**Issue by PersonalityFox** [prettydiff/prettydiff#606]
Hi

In the course of my work I encountered an unpleasant feature of formatting styles when the path to the image breaks.

Before
`body:after {
    content: url('/img/loading.png,a157648x15b.webp')
}`

After
`body:after {
    content: url('/img/loading.png, a157648x15b.webp') 
}`

I don’t think that someone else might face this, but I hope that my message will not be ignored

**Comment by prettydiff** [comment]
Thanks for pointing that out.  Let's see how fast I can nail this and add test samples.

**Comment by prettydiff** [comment]
I have confirmed the problem comes from https://github.com/Unibeautify/sparser/blob/master/lexers/style.ts#L346 so I need to ensure that alteration to values is specific to values that are not quoted or not wrapped in `url(` and `)`.
