### ISSUE TITLE
SCSS defect - conflict between variables and quoting in url references

### ISSUE THREAD

**Issue by prettydiff** [prettydiff/prettydiff#63]
Input:

    background: $gray-light url($images-path+"bg-conseil-1.jpg") bottom right no-repeat;

Becomes:

    background: $gray-light url("$images-path+"bg-conseil-1.jpg") bottom right no-repeat;

**Comment by prettydiff** [comment]
Up for review:

prettydiff.com/ignore/testlocation/prettydiff.com.xhtml

**Comment by Bodhiz** [comment]
Looks fine :+1:  
Thank you very much !
