### ISSUE TITLE
Add docopt compatible cli app

### ISSUE THREAD

**Issue by nilsboy** [prettydiff/prettydiff#64]
I have now tried for ~30min to understand the cli interface.

It would be nice to ship a cli app with the npm that adheres to the docopt[1][2] spec.
With the -g option of npm it should install into the $PATH.
A good name would be prettydiff instead of node-local.js.

Thank you.

[1] http://docopt.org/
[2] https://www.npmjs.com/package/docopt

**Comment by prettydiff** [comment]
I have recently been thinking about writing a man page as well. This is a very necessary idea, and I will commit to it.

**Comment by prettydiff** [comment]
Download these:

* http://prettydiff.com/ignore/testlocation/prettydiff.js
* http://prettydiff.com/ignore/testlocation/api/node-local.js

The node-local.js file needs to be a sub-directory.  Run this file without any options and let me know if the command line help is better.  I am completely open to suggestions so if there is anything you think would make this more helpful please let me know.

**Comment by prettydiff** [comment]
I will experiment with making command line access global tonight.

Requirements:

* update documentation and README.md files to suggest installing the package globally
* add a bin property to the package.json file - https://docs.npmjs.com/files/package.json#bin
* create a bin file named `prettydiff` that refers back to the api/node-local.js file
* the `prettydiff` bin file should contain:

    #!/usr/bin/env node
    require('../api/node-local');

The goal will be to allow execution by command `prettydiff` without the `node node_modules/prettydiff/api/node-local.js` insanity.

* I will need to test what happens to relative paths used against a globally installed package.

**Comment by prettydiff** [comment]
Command line help is updated and documentation is updated.  Install globally and run with far greater ease:

    npm install prettydiff -g

    prettydiff source:"someFile.js" mode:"beautify"
