### ISSUE TITLE
shebang line should be ignored during formatting

### ISSUE THREAD

**Issue by nilsboy** [prettydiff/prettydiff#67]
If a node script starts with a shebang line like this:

```
#!/usr/bin/env node
```

It gets formatted to:

```
# !/usr/bin / env node;
```

Please fix this - thank you!

**Comment by prettydiff** [comment]
Reference: https://en.wikipedia.org/wiki/Shebang_%28Unix%29

Should the shebang always be an absolute path from root?  Will it always be at the top of a file?

**Comment by prettydiff** [comment]
Up for your review:

http://prettydiff.com/ignore/testlocation/prettydiff.com.xhtml

**Comment by nilsboy** [comment]
Works - but if it is followed by a comment the comment gets joint with the shebang line - try this file for example:

https://raw.githubusercontent.com/nilsboy/bin/666bca7bb05857116064d89d7fd9583de050c305/js-format-using-prettydiff

**Comment by prettydiff** [comment]
Out of curiosity how did you find or hear about this tool?

**Comment by nilsboy** [comment]
I found about prettydiff on stackoverflow while researching js beautifiers - as far as I found your tool is the only one that can add missing curlies and semicolons - corrections like that are a great feature for reading code others wrote.

If you're tasking about the js-format-using-prettydiff script above - I wrote that yesterday.

**Comment by prettydiff** [comment]
Is there any possibility the shebang could appear in a CSS file or something that gets compiled to CSS, such as LESS or Sass?

**Comment by nilsboy** [comment]
No - I don't think it would ever be used outside of node scripts - so concatenation can be ignored.
