### ISSUE TITLE
Small bug in TSS with empty blocks

### ISSUE THREAD

**Issue by m1ga** [prettydiff/prettydiff#73]
~~~
".lbl_header_list": {
    left: 5
}

"NavigationWindow": {}


"TextField": {
    width: 200
}
~~~

will be beautified to

~~~
".lbl_header_list": {
    left: 5
}

"NavigationWindow": {}"TextField": {
    width: 200
}
~~~

which leads to an error in Titanium because it can't handle ""NavigationWindow": {}"TextField": {" in one row

**Comment by prettydiff** [comment]
This can be tested at http://prettydiff.com/ignore/testlocation/prettydiff.com.xhtml

**Comment by m1ga** [comment]
:+1: awesome. Thanks
