### ISSUE TITLE
Markup tags with spaces between attribute names improperly reorders attributes

### ISSUE THREAD

**Issue by prettydiff** [prettydiff/prettydiff#74]
<p att1="4" att2="4" att3="6"  att4="a" att3="6" att4 ="a"/>

Becomes:

    <p ="a" att1="4" att2="4" att3="6" att3="6" att4 att4="a"/>

But should be:

    <p att1="4" att2="4" att3="6" att3="6" att4="a" att4="a"/>

**Comment by prettydiff** [comment]
This can be tested at http://prettydiff.com/ignore/testlocation/prettydiff.com.xhtml

**Comment by kaizer200** [comment]
Hi,
tested on http://prettydiff.com/ignore/testlocation/prettydiff.com.xhtml
results:
1) Tested OK:
     when leaving a space between the attribute name and the equal sign.
     tested: <tag att1 =val2></tag>  result: <tag att1=val2></tag>
2) Test False:
   2.1) space between attribute's value and equal sign (no change,the value should be tied to equal)
        tested: <tag att1=  val2></tag>    result: <tag att1=  val2></tag>
    2.2) attribute's value with quotation sign and not tied to the equal sign. Beautification is not ordered   
         correct
        tested:<tag att1= "val2"></tag>   result:<tag "val2" att1=></tag>

**Comment by prettydiff** [comment]
Updated and ready for review: http://prettydiff.com/ignore/testlocation/prettydiff.com.xhtml

**Comment by kaizer200** [comment]
Tested good :-)
