### ISSUE TITLE
Markup tag with processing-instruction imporly written gets prettyDiff stuck when beautify

### ISSUE THREAD

**Issue by kaizer200** [prettydiff/prettydiff#75]
example for processing-instruction in xml (declared by '?'): <?display table-view?>
if the processing-instruction node is complete (by copy-paste to the prettyDiff.com editor), the beautification result of the xml is OK.
example:
\<?display table-view?>
\<person att1="4">\<to>\</to>\</person>

if the processing-instruction node is imporly closed, or a '?' is missing, the editor and the browser GET STUCK (long running script...)
example 1:
\<?display table-view?
\<person att1="4">\<to>\</to>\</person>

example 2:
<?

**Comment by prettydiff** [comment]
Thanks for reporting this critical bug. I plan to issue a fix this evening.

**Comment by prettydiff** [comment]
Error reproduced when the passing code sample and deleted the first ">" character.  Error is verified in the codemirror.js library.

**Comment by prettydiff** [comment]
Problem identified as an endless loop in function `toTagEnd` on call to function `tagAt`.  Patched by creating a flag to see if variable `gt` is value 0 for two consecutive intervals and if so issue a `return`.

Available for review at http://prettydiff.com/ignore/testlocation/prettydiff.com.xhtml

**Comment by kaizer200** [comment]
Tested OK
