### ISSUE TITLE
Markup tag with document type not closed get prettyDiff stuck when beautify

### ISSUE THREAD

**Issue by kaizer200** [prettydiff/prettydiff#76]
steps to reproduce:
1) write the following xml:
\<!DOCTYPE html>
\<person att3="3">\<\person>
2) click beautify - works ok
3)remove the closing '>' sign from the first line
4) prettyDiff editor / browser get stuck (long running script problem...)

**Comment by prettydiff** [comment]
I believe this issue is a duplicate of issue #75.  Please feel free to reopen if I am wrong.

**Comment by kaizer200** [comment]
tested OK
