### ISSUE TITLE
Considering remove CodeMirror

### ISSUE THREAD

**Issue by prettydiff** [prettydiff/prettydiff#78]
I am considering removing [CodeMirror](http://codemirror.com/).  Code Mirror is the cool editor that transforms simple HTML textareas into code editors with line numbers, syntax coloring, code folding and so forth. CodeMirror is a fantastic tool that greatly enhances Pretty Diff, but I cannot have it continuously crashing the application and reflecting negatively upon this tool.

It is extremely buggy and its code is a web of spaghetti that creates numerous regression issues once providing a simple patch.

If I get 100 responses before Monday I will keep it and find a way to work in solutions to the numerous bugs. If I do not get a **strong** show of support then I am ripping it out.

**Comment by kaizer200** [comment]
I vote to keep it for the meanwhile; 
I also experienced crushes of the codeMirror and believe it should be replaced, but this is the shopping-window of the tool (every such other open-source tool has it). 

I suggest you the following mitigation plan:
1) remove functionality from the online-editor, and keep the functionality that is expressed in the online configuration options and related to the open-source only(syntax-coloring for example is the code-mirror functionality and can be removed)
2) supply notification to end-user when code-mirror crush, and ask to refresh/click-button which will refresh and do some cleaning...
3) provide a remark at prettyDiff.com, that: the editor is experiencing some know issues but differentiate it from library itself.
4) replace code-mirror

**Comment by TechplexEngineer** [comment]
Have you tried Ace?

**Comment by prettydiff** [comment]
I was not aware of ACE. I will look into this further.  So far it looks nice on their site: http://ace.c9.io/#nav=about

**Comment by prettydiff** [comment]
I will convert codeMirror to Ace this weekend.

**Comment by kaizer200** [comment]
checkout ACE's http://ace.c9.io/build/kitchen-sink.html
for its online editor (showcasing all its possibilities)

**Comment by kaizer200** [comment]
HI,
checkout orion, from the eclipse open-source project (https://orionhub.org/).
Its highly profiled, immensely contributed.
UI and functionality wise (wide and depth of features) - **its better then ACE**.

it contains server and client sides - you need only the client side.
