### ISSUE TITLE
Request for wrapping configuration for markup CDATA

### ISSUE THREAD

**Issue by kaizer200** [prettydiff/prettydiff#80]
Hi,
I would like to be able to configure the line length of XML's CDATA element's type.
The wrap limit for CDATA should have DIFFERENT configuration-option then the one for xml tag's attributes (2 wrapping for different usages).
-- CDATA may express any content that the xml parser would not parse (code, comment etc.). For this reason, no content other then newLine should be entered to conform to the wrapping-limit.
When wrap limit is reached:
if fall on space/s - the space/s can dropped to the newLine - but in any case be kept (as this could be part of code syntax);
if fall in the middle of a token, again - spaces can be kept in the original or the newLine; but - then should be kept

**Comment by prettydiff** [comment]
Initial thoughts:

* What about SGML annotations like: `<!DOCTYPE.... >` or XML pragmas like: `<?xml.... ?>`?
* In addition to the work for this issue I also need to write a guide that explains how wrapping works in markup.
* This rule will not apply to JavaScript wrapped in a CDATA block if that CDATA block occurs inside a script tag.
* It sounds like wrapping should occur in CDATA much the same as with start tags, but a new line character is added to the CDATA block at appropriate wrapping limit and does not replace the space character at this location.

**Comment by kaizer200** [comment]
I think that SGML annotations and XML pragma line-wrapping, are nice-to-have features.
