### ISSUE TITLE
diffcli broken for diffing two files

### ISSUE THREAD

**Issue by gautamvasudevan** [prettydiff/prettydiff#86]
Attempting the following command line:
prettydiff source:"test1.txt" lang:"text" diff:"test2.txt" diffcli:"true" mode:"diff" readmethod:"file" output:"output.txt"

Results in 

/usr/local/lib/node_modules/prettydiff/api/node-local.js:1003
                pdlen  = output[0].length;
                                  ^
TypeError: Cannot read property 'length' of undefined
    at cliWrite (/usr/local/lib/node_modules/prettydiff/api/node-local.js:1003:35)
    at fileComplete (/usr/local/lib/node_modules/prettydiff/api/node-local.js:1095:21)
    at /usr/local/lib/node_modules/prettydiff/api/node-local.js:1128:17
    at fs.js:334:14
    at FSReqWrap.oncomplete (fs.js:95:15)

It appears that cliWrite now assumes that output[0] exists when it does not.  Output, in my case, looked like:
{ absolutepath: 'test1.txt',
  index: 0,
  last: true,
  localpath: 'test1.txt',
  type: 'source',
  file: 'whatever\n\n' }

**Comment by prettydiff** [comment]
If you continue to have problems please feel free to reopen this bug or open a new one.
