### ISSUE TITLE
Xml comparison ignoring child element order

### ISSUE THREAD

**Issue by askheaves** [prettydiff/prettydiff#89]
Hi.

I would find a lot of use comparing two xml files while ignoring the order of child elements (with the logical extension of attributes), if that's a possibility for v2.0. I know that's a trickier process with a bit more state, though an easy cheat could be to allow alphabetizing nodes and attributes.

**Comment by prettydiff** [comment]
I could make that an optional feature. I would just need to sort child elements of any given element.

**Comment by askheaves** [comment]
Fantastic!

**Comment by prettydiff** [comment]
This is up in an experimental form at

http://prettydiff.com/ignore/testlocation/prettydiff.com.xhtml
