### ISSUE TITLE
preserve indenting

### ISSUE THREAD

**Issue by rickdog** [prettydiff/prettydiff#94]
how do I preserve indenting on something like this (jQuery) with jspretty?

```
$('<input>')
    .attr('type', 'file')
    .attr('id', 'file')
    .prependTo('body');
```

**Comment by prettydiff** [comment]
You don't. I could create a new option to indent methods. It would be all or nothing though. That would mean every method would be indented, which might also be something you are not interested in, particularly if the chain of properties is inside a condition.

Would you really want this:

    if (obj.getSession().getMode().$id === "xml) {

To become:

    if (obj
        .getSession()
        .getMode().$id === "xml) {
